// source: librarian/v0/app_bind.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var librarian_v0_base_pb = require('../../librarian/v0/base_pb.js');
goog.object.extend(proto, librarian_v0_base_pb);
goog.exportSymbol('proto.librarian.AddAppBindReq', null, global);
goog.exportSymbol('proto.librarian.AddAppBindResp', null, global);
goog.exportSymbol('proto.librarian.AppBindInfo', null, global);
goog.exportSymbol('proto.librarian.ListAppBindReq', null, global);
goog.exportSymbol('proto.librarian.ListAppBindResp', null, global);
goog.exportSymbol('proto.librarian.RemoveAppBindReq', null, global);
goog.exportSymbol('proto.librarian.RemoveAppBindResp', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.AddAppBindReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.librarian.AddAppBindReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.AddAppBindReq.displayName = 'proto.librarian.AddAppBindReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.AddAppBindResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.librarian.AddAppBindResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.AddAppBindResp.displayName = 'proto.librarian.AddAppBindResp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.RemoveAppBindReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.librarian.RemoveAppBindReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.RemoveAppBindReq.displayName = 'proto.librarian.RemoveAppBindReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.RemoveAppBindResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.librarian.RemoveAppBindResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.RemoveAppBindResp.displayName = 'proto.librarian.RemoveAppBindResp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.ListAppBindReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, proto.librarian.ListAppBindReq.repeatedFields_, null);
};
goog.inherits(proto.librarian.ListAppBindReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.ListAppBindReq.displayName = 'proto.librarian.ListAppBindReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.ListAppBindResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, proto.librarian.ListAppBindResp.repeatedFields_, null);
};
goog.inherits(proto.librarian.ListAppBindResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.ListAppBindResp.displayName = 'proto.librarian.ListAppBindResp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.AppBindInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.librarian.AppBindInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.AppBindInfo.displayName = 'proto.librarian.AppBindInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.AddAppBindReq.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.AddAppBindReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.AddAppBindReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.AddAppBindReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    appid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    sentinelreportid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    base: (f = msg.getBase()) && librarian_v0_base_pb.BaseReq.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.AddAppBindReq}
 */
proto.librarian.AddAppBindReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.AddAppBindReq;
  return proto.librarian.AddAppBindReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.AddAppBindReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.AddAppBindReq}
 */
proto.librarian.AddAppBindReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAppid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSentinelreportid(value);
      break;
    case 2047:
      var value = new librarian_v0_base_pb.BaseReq;
      reader.readMessage(value,librarian_v0_base_pb.BaseReq.deserializeBinaryFromReader);
      msg.setBase(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.AddAppBindReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.AddAppBindReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.AddAppBindReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.AddAppBindReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAppid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getSentinelreportid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getBase();
  if (f != null) {
    writer.writeMessage(
      2047,
      f,
      librarian_v0_base_pb.BaseReq.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 AppId = 1;
 * @return {number}
 */
proto.librarian.AddAppBindReq.prototype.getAppid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.librarian.AddAppBindReq} returns this
 */
proto.librarian.AddAppBindReq.prototype.setAppid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 SentinelReportId = 2;
 * @return {number}
 */
proto.librarian.AddAppBindReq.prototype.getSentinelreportid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.librarian.AddAppBindReq} returns this
 */
proto.librarian.AddAppBindReq.prototype.setSentinelreportid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional BaseReq Base = 2047;
 * @return {?proto.librarian.BaseReq}
 */
proto.librarian.AddAppBindReq.prototype.getBase = function() {
  return /** @type{?proto.librarian.BaseReq} */ (
    jspb.Message.getWrapperField(this, librarian_v0_base_pb.BaseReq, 2047));
};


/**
 * @param {?proto.librarian.BaseReq|undefined} value
 * @return {!proto.librarian.AddAppBindReq} returns this
*/
proto.librarian.AddAppBindReq.prototype.setBase = function(value) {
  return jspb.Message.setWrapperField(this, 2047, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.librarian.AddAppBindReq} returns this
 */
proto.librarian.AddAppBindReq.prototype.clearBase = function() {
  return this.setBase(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.librarian.AddAppBindReq.prototype.hasBase = function() {
  return jspb.Message.getField(this, 2047) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.AddAppBindResp.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.AddAppBindResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.AddAppBindResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.AddAppBindResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    base: (f = msg.getBase()) && librarian_v0_base_pb.BaseResp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.AddAppBindResp}
 */
proto.librarian.AddAppBindResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.AddAppBindResp;
  return proto.librarian.AddAppBindResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.AddAppBindResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.AddAppBindResp}
 */
proto.librarian.AddAppBindResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2047:
      var value = new librarian_v0_base_pb.BaseResp;
      reader.readMessage(value,librarian_v0_base_pb.BaseResp.deserializeBinaryFromReader);
      msg.setBase(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.AddAppBindResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.AddAppBindResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.AddAppBindResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.AddAppBindResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBase();
  if (f != null) {
    writer.writeMessage(
      2047,
      f,
      librarian_v0_base_pb.BaseResp.serializeBinaryToWriter
    );
  }
};


/**
 * optional BaseResp Base = 2047;
 * @return {?proto.librarian.BaseResp}
 */
proto.librarian.AddAppBindResp.prototype.getBase = function() {
  return /** @type{?proto.librarian.BaseResp} */ (
    jspb.Message.getWrapperField(this, librarian_v0_base_pb.BaseResp, 2047));
};


/**
 * @param {?proto.librarian.BaseResp|undefined} value
 * @return {!proto.librarian.AddAppBindResp} returns this
*/
proto.librarian.AddAppBindResp.prototype.setBase = function(value) {
  return jspb.Message.setWrapperField(this, 2047, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.librarian.AddAppBindResp} returns this
 */
proto.librarian.AddAppBindResp.prototype.clearBase = function() {
  return this.setBase(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.librarian.AddAppBindResp.prototype.hasBase = function() {
  return jspb.Message.getField(this, 2047) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.RemoveAppBindReq.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.RemoveAppBindReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.RemoveAppBindReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.RemoveAppBindReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    appid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    sentinelreportid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    base: (f = msg.getBase()) && librarian_v0_base_pb.BaseReq.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.RemoveAppBindReq}
 */
proto.librarian.RemoveAppBindReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.RemoveAppBindReq;
  return proto.librarian.RemoveAppBindReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.RemoveAppBindReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.RemoveAppBindReq}
 */
proto.librarian.RemoveAppBindReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAppid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSentinelreportid(value);
      break;
    case 2047:
      var value = new librarian_v0_base_pb.BaseReq;
      reader.readMessage(value,librarian_v0_base_pb.BaseReq.deserializeBinaryFromReader);
      msg.setBase(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.RemoveAppBindReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.RemoveAppBindReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.RemoveAppBindReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.RemoveAppBindReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAppid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getSentinelreportid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getBase();
  if (f != null) {
    writer.writeMessage(
      2047,
      f,
      librarian_v0_base_pb.BaseReq.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 AppId = 1;
 * @return {number}
 */
proto.librarian.RemoveAppBindReq.prototype.getAppid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.librarian.RemoveAppBindReq} returns this
 */
proto.librarian.RemoveAppBindReq.prototype.setAppid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 SentinelReportId = 2;
 * @return {number}
 */
proto.librarian.RemoveAppBindReq.prototype.getSentinelreportid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.librarian.RemoveAppBindReq} returns this
 */
proto.librarian.RemoveAppBindReq.prototype.setSentinelreportid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional BaseReq Base = 2047;
 * @return {?proto.librarian.BaseReq}
 */
proto.librarian.RemoveAppBindReq.prototype.getBase = function() {
  return /** @type{?proto.librarian.BaseReq} */ (
    jspb.Message.getWrapperField(this, librarian_v0_base_pb.BaseReq, 2047));
};


/**
 * @param {?proto.librarian.BaseReq|undefined} value
 * @return {!proto.librarian.RemoveAppBindReq} returns this
*/
proto.librarian.RemoveAppBindReq.prototype.setBase = function(value) {
  return jspb.Message.setWrapperField(this, 2047, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.librarian.RemoveAppBindReq} returns this
 */
proto.librarian.RemoveAppBindReq.prototype.clearBase = function() {
  return this.setBase(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.librarian.RemoveAppBindReq.prototype.hasBase = function() {
  return jspb.Message.getField(this, 2047) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.RemoveAppBindResp.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.RemoveAppBindResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.RemoveAppBindResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.RemoveAppBindResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    base: (f = msg.getBase()) && librarian_v0_base_pb.BaseResp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.RemoveAppBindResp}
 */
proto.librarian.RemoveAppBindResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.RemoveAppBindResp;
  return proto.librarian.RemoveAppBindResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.RemoveAppBindResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.RemoveAppBindResp}
 */
proto.librarian.RemoveAppBindResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2047:
      var value = new librarian_v0_base_pb.BaseResp;
      reader.readMessage(value,librarian_v0_base_pb.BaseResp.deserializeBinaryFromReader);
      msg.setBase(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.RemoveAppBindResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.RemoveAppBindResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.RemoveAppBindResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.RemoveAppBindResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBase();
  if (f != null) {
    writer.writeMessage(
      2047,
      f,
      librarian_v0_base_pb.BaseResp.serializeBinaryToWriter
    );
  }
};


/**
 * optional BaseResp Base = 2047;
 * @return {?proto.librarian.BaseResp}
 */
proto.librarian.RemoveAppBindResp.prototype.getBase = function() {
  return /** @type{?proto.librarian.BaseResp} */ (
    jspb.Message.getWrapperField(this, librarian_v0_base_pb.BaseResp, 2047));
};


/**
 * @param {?proto.librarian.BaseResp|undefined} value
 * @return {!proto.librarian.RemoveAppBindResp} returns this
*/
proto.librarian.RemoveAppBindResp.prototype.setBase = function(value) {
  return jspb.Message.setWrapperField(this, 2047, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.librarian.RemoveAppBindResp} returns this
 */
proto.librarian.RemoveAppBindResp.prototype.clearBase = function() {
  return this.setBase(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.librarian.RemoveAppBindResp.prototype.hasBase = function() {
  return jspb.Message.getField(this, 2047) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.librarian.ListAppBindReq.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.ListAppBindReq.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.ListAppBindReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.ListAppBindReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.ListAppBindReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    appidList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    sentinelreportidList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    base: (f = msg.getBase()) && librarian_v0_base_pb.BaseReq.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.ListAppBindReq}
 */
proto.librarian.ListAppBindReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.ListAppBindReq;
  return proto.librarian.ListAppBindReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.ListAppBindReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.ListAppBindReq}
 */
proto.librarian.ListAppBindReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addAppid(values[i]);
      }
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addSentinelreportid(values[i]);
      }
      break;
    case 2047:
      var value = new librarian_v0_base_pb.BaseReq;
      reader.readMessage(value,librarian_v0_base_pb.BaseReq.deserializeBinaryFromReader);
      msg.setBase(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.ListAppBindReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.ListAppBindReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.ListAppBindReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.ListAppBindReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAppidList();
  if (f.length > 0) {
    writer.writePackedInt64(
      1,
      f
    );
  }
  f = message.getSentinelreportidList();
  if (f.length > 0) {
    writer.writePackedInt64(
      2,
      f
    );
  }
  f = message.getBase();
  if (f != null) {
    writer.writeMessage(
      2047,
      f,
      librarian_v0_base_pb.BaseReq.serializeBinaryToWriter
    );
  }
};


/**
 * repeated int64 AppId = 1;
 * @return {!Array<number>}
 */
proto.librarian.ListAppBindReq.prototype.getAppidList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.librarian.ListAppBindReq} returns this
 */
proto.librarian.ListAppBindReq.prototype.setAppidList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.librarian.ListAppBindReq} returns this
 */
proto.librarian.ListAppBindReq.prototype.addAppid = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.librarian.ListAppBindReq} returns this
 */
proto.librarian.ListAppBindReq.prototype.clearAppidList = function() {
  return this.setAppidList([]);
};


/**
 * repeated int64 SentinelReportId = 2;
 * @return {!Array<number>}
 */
proto.librarian.ListAppBindReq.prototype.getSentinelreportidList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.librarian.ListAppBindReq} returns this
 */
proto.librarian.ListAppBindReq.prototype.setSentinelreportidList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.librarian.ListAppBindReq} returns this
 */
proto.librarian.ListAppBindReq.prototype.addSentinelreportid = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.librarian.ListAppBindReq} returns this
 */
proto.librarian.ListAppBindReq.prototype.clearSentinelreportidList = function() {
  return this.setSentinelreportidList([]);
};


/**
 * optional BaseReq Base = 2047;
 * @return {?proto.librarian.BaseReq}
 */
proto.librarian.ListAppBindReq.prototype.getBase = function() {
  return /** @type{?proto.librarian.BaseReq} */ (
    jspb.Message.getWrapperField(this, librarian_v0_base_pb.BaseReq, 2047));
};


/**
 * @param {?proto.librarian.BaseReq|undefined} value
 * @return {!proto.librarian.ListAppBindReq} returns this
*/
proto.librarian.ListAppBindReq.prototype.setBase = function(value) {
  return jspb.Message.setWrapperField(this, 2047, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.librarian.ListAppBindReq} returns this
 */
proto.librarian.ListAppBindReq.prototype.clearBase = function() {
  return this.setBase(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.librarian.ListAppBindReq.prototype.hasBase = function() {
  return jspb.Message.getField(this, 2047) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.librarian.ListAppBindResp.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.ListAppBindResp.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.ListAppBindResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.ListAppBindResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.ListAppBindResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    infosList: jspb.Message.toObjectList(msg.getInfosList(),
    proto.librarian.AppBindInfo.toObject, includeInstance),
    total: jspb.Message.getFieldWithDefault(msg, 10, 0),
    base: (f = msg.getBase()) && librarian_v0_base_pb.BaseResp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.ListAppBindResp}
 */
proto.librarian.ListAppBindResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.ListAppBindResp;
  return proto.librarian.ListAppBindResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.ListAppBindResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.ListAppBindResp}
 */
proto.librarian.ListAppBindResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.librarian.AppBindInfo;
      reader.readMessage(value,proto.librarian.AppBindInfo.deserializeBinaryFromReader);
      msg.addInfos(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTotal(value);
      break;
    case 2047:
      var value = new librarian_v0_base_pb.BaseResp;
      reader.readMessage(value,librarian_v0_base_pb.BaseResp.deserializeBinaryFromReader);
      msg.setBase(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.ListAppBindResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.ListAppBindResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.ListAppBindResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.ListAppBindResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInfosList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.librarian.AppBindInfo.serializeBinaryToWriter
    );
  }
  f = message.getTotal();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = message.getBase();
  if (f != null) {
    writer.writeMessage(
      2047,
      f,
      librarian_v0_base_pb.BaseResp.serializeBinaryToWriter
    );
  }
};


/**
 * repeated AppBindInfo Infos = 1;
 * @return {!Array<!proto.librarian.AppBindInfo>}
 */
proto.librarian.ListAppBindResp.prototype.getInfosList = function() {
  return /** @type{!Array<!proto.librarian.AppBindInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.librarian.AppBindInfo, 1));
};


/**
 * @param {!Array<!proto.librarian.AppBindInfo>} value
 * @return {!proto.librarian.ListAppBindResp} returns this
*/
proto.librarian.ListAppBindResp.prototype.setInfosList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.librarian.AppBindInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.librarian.AppBindInfo}
 */
proto.librarian.ListAppBindResp.prototype.addInfos = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.librarian.AppBindInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.librarian.ListAppBindResp} returns this
 */
proto.librarian.ListAppBindResp.prototype.clearInfosList = function() {
  return this.setInfosList([]);
};


/**
 * optional int64 Total = 10;
 * @return {number}
 */
proto.librarian.ListAppBindResp.prototype.getTotal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.librarian.ListAppBindResp} returns this
 */
proto.librarian.ListAppBindResp.prototype.setTotal = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional BaseResp Base = 2047;
 * @return {?proto.librarian.BaseResp}
 */
proto.librarian.ListAppBindResp.prototype.getBase = function() {
  return /** @type{?proto.librarian.BaseResp} */ (
    jspb.Message.getWrapperField(this, librarian_v0_base_pb.BaseResp, 2047));
};


/**
 * @param {?proto.librarian.BaseResp|undefined} value
 * @return {!proto.librarian.ListAppBindResp} returns this
*/
proto.librarian.ListAppBindResp.prototype.setBase = function(value) {
  return jspb.Message.setWrapperField(this, 2047, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.librarian.ListAppBindResp} returns this
 */
proto.librarian.ListAppBindResp.prototype.clearBase = function() {
  return this.setBase(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.librarian.ListAppBindResp.prototype.hasBase = function() {
  return jspb.Message.getField(this, 2047) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.AppBindInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.AppBindInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.AppBindInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.AppBindInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    appid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    sentinelreportid: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.AppBindInfo}
 */
proto.librarian.AppBindInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.AppBindInfo;
  return proto.librarian.AppBindInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.AppBindInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.AppBindInfo}
 */
proto.librarian.AppBindInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAppid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSentinelreportid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.AppBindInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.AppBindInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.AppBindInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.AppBindInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAppid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getSentinelreportid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional int64 AppId = 1;
 * @return {number}
 */
proto.librarian.AppBindInfo.prototype.getAppid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.librarian.AppBindInfo} returns this
 */
proto.librarian.AppBindInfo.prototype.setAppid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 SentinelReportId = 2;
 * @return {number}
 */
proto.librarian.AppBindInfo.prototype.getSentinelreportid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.librarian.AppBindInfo} returns this
 */
proto.librarian.AppBindInfo.prototype.setSentinelreportid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


goog.object.extend(exports, proto.librarian);
