// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: librarian/sephirah/v1/yesod.proto

package v1

import (
	v1 "github.com/tuihub/protos/pkg/librarian/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedConfigStatus int32

const (
	FeedConfigStatus_FEED_CONFIG_STATUS_UNSPECIFIED FeedConfigStatus = 0
	FeedConfigStatus_FEED_CONFIG_STATUS_ACTIVE      FeedConfigStatus = 1
	FeedConfigStatus_FEED_CONFIG_STATUS_SUSPEND     FeedConfigStatus = 2
)

// Enum value maps for FeedConfigStatus.
var (
	FeedConfigStatus_name = map[int32]string{
		0: "FEED_CONFIG_STATUS_UNSPECIFIED",
		1: "FEED_CONFIG_STATUS_ACTIVE",
		2: "FEED_CONFIG_STATUS_SUSPEND",
	}
	FeedConfigStatus_value = map[string]int32{
		"FEED_CONFIG_STATUS_UNSPECIFIED": 0,
		"FEED_CONFIG_STATUS_ACTIVE":      1,
		"FEED_CONFIG_STATUS_SUSPEND":     2,
	}
)

func (x FeedConfigStatus) Enum() *FeedConfigStatus {
	p := new(FeedConfigStatus)
	*p = x
	return p
}

func (x FeedConfigStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedConfigStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_librarian_sephirah_v1_yesod_proto_enumTypes[0].Descriptor()
}

func (FeedConfigStatus) Type() protoreflect.EnumType {
	return &file_librarian_sephirah_v1_yesod_proto_enumTypes[0]
}

func (x FeedConfigStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedConfigStatus.Descriptor instead.
func (FeedConfigStatus) EnumDescriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{0}
}

type FeedConfigSource int32

const (
	FeedConfigSource_FEED_CONFIG_SOURCE_UNSPECIFIED FeedConfigSource = 0
	FeedConfigSource_FEED_CONFIG_SOURCE_COMMON      FeedConfigSource = 1
)

// Enum value maps for FeedConfigSource.
var (
	FeedConfigSource_name = map[int32]string{
		0: "FEED_CONFIG_SOURCE_UNSPECIFIED",
		1: "FEED_CONFIG_SOURCE_COMMON",
	}
	FeedConfigSource_value = map[string]int32{
		"FEED_CONFIG_SOURCE_UNSPECIFIED": 0,
		"FEED_CONFIG_SOURCE_COMMON":      1,
	}
)

func (x FeedConfigSource) Enum() *FeedConfigSource {
	p := new(FeedConfigSource)
	*p = x
	return p
}

func (x FeedConfigSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedConfigSource) Descriptor() protoreflect.EnumDescriptor {
	return file_librarian_sephirah_v1_yesod_proto_enumTypes[1].Descriptor()
}

func (FeedConfigSource) Type() protoreflect.EnumType {
	return &file_librarian_sephirah_v1_yesod_proto_enumTypes[1]
}

func (x FeedConfigSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedConfigSource.Descriptor instead.
func (FeedConfigSource) EnumDescriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{1}
}

type CreateFeedConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *FeedConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *CreateFeedConfigRequest) Reset() {
	*x = CreateFeedConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFeedConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedConfigRequest) ProtoMessage() {}

func (x *CreateFeedConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateFeedConfigRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFeedConfigRequest) GetConfig() *FeedConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateFeedConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *v1.InternalID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateFeedConfigResponse) Reset() {
	*x = CreateFeedConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFeedConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedConfigResponse) ProtoMessage() {}

func (x *CreateFeedConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateFeedConfigResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFeedConfigResponse) GetId() *v1.InternalID {
	if x != nil {
		return x.Id
	}
	return nil
}

type UpdateFeedConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *FeedConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *UpdateFeedConfigRequest) Reset() {
	*x = UpdateFeedConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFeedConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedConfigRequest) ProtoMessage() {}

func (x *UpdateFeedConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateFeedConfigRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateFeedConfigRequest) GetConfig() *FeedConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateFeedConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFeedConfigResponse) Reset() {
	*x = UpdateFeedConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFeedConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedConfigResponse) ProtoMessage() {}

func (x *UpdateFeedConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateFeedConfigResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{3}
}

type ListFeedsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paging         *v1.PagingRequest  `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	IdFilter       []*v1.InternalID   `protobuf:"bytes,2,rep,name=id_filter,json=idFilter,proto3" json:"id_filter,omitempty"`
	AuthorIdFilter []*v1.InternalID   `protobuf:"bytes,3,rep,name=author_id_filter,json=authorIdFilter,proto3" json:"author_id_filter,omitempty"`
	SourceFilter   []FeedConfigSource `protobuf:"varint,4,rep,packed,name=source_filter,json=sourceFilter,proto3,enum=librarian.sephirah.v1.FeedConfigSource" json:"source_filter,omitempty"`
	StatusFilter   []FeedConfigStatus `protobuf:"varint,5,rep,packed,name=status_filter,json=statusFilter,proto3,enum=librarian.sephirah.v1.FeedConfigStatus" json:"status_filter,omitempty"`
}

func (x *ListFeedsRequest) Reset() {
	*x = ListFeedsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedsRequest) ProtoMessage() {}

func (x *ListFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedsRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{4}
}

func (x *ListFeedsRequest) GetPaging() *v1.PagingRequest {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListFeedsRequest) GetIdFilter() []*v1.InternalID {
	if x != nil {
		return x.IdFilter
	}
	return nil
}

func (x *ListFeedsRequest) GetAuthorIdFilter() []*v1.InternalID {
	if x != nil {
		return x.AuthorIdFilter
	}
	return nil
}

func (x *ListFeedsRequest) GetSourceFilter() []FeedConfigSource {
	if x != nil {
		return x.SourceFilter
	}
	return nil
}

func (x *ListFeedsRequest) GetStatusFilter() []FeedConfigStatus {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

type ListFeedsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paging          *v1.PagingResponse                  `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	FeedsWithConfig []*ListFeedsResponse_FeedWithConfig `protobuf:"bytes,2,rep,name=feeds_with_config,json=feedsWithConfig,proto3" json:"feeds_with_config,omitempty"`
}

func (x *ListFeedsResponse) Reset() {
	*x = ListFeedsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedsResponse) ProtoMessage() {}

func (x *ListFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedsResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{5}
}

func (x *ListFeedsResponse) GetPaging() *v1.PagingResponse {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListFeedsResponse) GetFeedsWithConfig() []*ListFeedsResponse_FeedWithConfig {
	if x != nil {
		return x.FeedsWithConfig
	}
	return nil
}

type ListFeedItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paging                *v1.PagingRequest `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	FeedIdFilter          []*v1.InternalID  `protobuf:"bytes,2,rep,name=feed_id_filter,json=feedIdFilter,proto3" json:"feed_id_filter,omitempty"`
	AuthorIdFilter        []*v1.InternalID  `protobuf:"bytes,3,rep,name=author_id_filter,json=authorIdFilter,proto3" json:"author_id_filter,omitempty"`
	PublishPlatformFilter []string          `protobuf:"bytes,4,rep,name=publish_platform_filter,json=publishPlatformFilter,proto3" json:"publish_platform_filter,omitempty"`
}

func (x *ListFeedItemsRequest) Reset() {
	*x = ListFeedItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFeedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemsRequest) ProtoMessage() {}

func (x *ListFeedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedItemsRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{6}
}

func (x *ListFeedItemsRequest) GetPaging() *v1.PagingRequest {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListFeedItemsRequest) GetFeedIdFilter() []*v1.InternalID {
	if x != nil {
		return x.FeedIdFilter
	}
	return nil
}

func (x *ListFeedItemsRequest) GetAuthorIdFilter() []*v1.InternalID {
	if x != nil {
		return x.AuthorIdFilter
	}
	return nil
}

func (x *ListFeedItemsRequest) GetPublishPlatformFilter() []string {
	if x != nil {
		return x.PublishPlatformFilter
	}
	return nil
}

type ListFeedItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paging *v1.PagingResponse                            `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	Items  []*ListFeedItemsResponse_FeedItemIDWithFeedID `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListFeedItemsResponse) Reset() {
	*x = ListFeedItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFeedItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemsResponse) ProtoMessage() {}

func (x *ListFeedItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedItemsResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{7}
}

func (x *ListFeedItemsResponse) GetPaging() *v1.PagingResponse {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListFeedItemsResponse) GetItems() []*ListFeedItemsResponse_FeedItemIDWithFeedID {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetFeedItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *v1.InternalID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetFeedItemRequest) Reset() {
	*x = GetFeedItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFeedItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedItemRequest) ProtoMessage() {}

func (x *GetFeedItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedItemRequest.ProtoReflect.Descriptor instead.
func (*GetFeedItemRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{8}
}

func (x *GetFeedItemRequest) GetId() *v1.InternalID {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetFeedItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *v1.FeedItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *GetFeedItemResponse) Reset() {
	*x = GetFeedItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFeedItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedItemResponse) ProtoMessage() {}

func (x *GetFeedItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedItemResponse.ProtoReflect.Descriptor instead.
func (*GetFeedItemResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{9}
}

func (x *GetFeedItemResponse) GetItem() *v1.FeedItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetBatchFeedItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []*v1.InternalID `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetBatchFeedItemsRequest) Reset() {
	*x = GetBatchFeedItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBatchFeedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchFeedItemsRequest) ProtoMessage() {}

func (x *GetBatchFeedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchFeedItemsRequest.ProtoReflect.Descriptor instead.
func (*GetBatchFeedItemsRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{10}
}

func (x *GetBatchFeedItemsRequest) GetIds() []*v1.InternalID {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetBatchFeedItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*v1.FeedItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetBatchFeedItemsResponse) Reset() {
	*x = GetBatchFeedItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBatchFeedItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchFeedItemsResponse) ProtoMessage() {}

func (x *GetBatchFeedItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchFeedItemsResponse.ProtoReflect.Descriptor instead.
func (*GetBatchFeedItemsResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{11}
}

func (x *GetBatchFeedItemsResponse) GetItems() []*v1.FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type FeedConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            *v1.InternalID       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FeedUrl       string               `protobuf:"bytes,2,opt,name=feed_url,json=feedUrl,proto3" json:"feed_url,omitempty"`
	AuthorAccount *v1.InternalID       `protobuf:"bytes,3,opt,name=author_account,json=authorAccount,proto3" json:"author_account,omitempty"`
	Source        FeedConfigSource     `protobuf:"varint,4,opt,name=source,proto3,enum=librarian.sephirah.v1.FeedConfigSource" json:"source,omitempty"`
	Status        FeedConfigStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=librarian.sephirah.v1.FeedConfigStatus" json:"status,omitempty"`
	PullInterval  *durationpb.Duration `protobuf:"bytes,6,opt,name=pull_interval,json=pullInterval,proto3" json:"pull_interval,omitempty"`
	// response only
	LatestPullTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=latest_pull_time,json=latestPullTime,proto3,oneof" json:"latest_pull_time,omitempty"`
}

func (x *FeedConfig) Reset() {
	*x = FeedConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedConfig) ProtoMessage() {}

func (x *FeedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedConfig.ProtoReflect.Descriptor instead.
func (*FeedConfig) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{12}
}

func (x *FeedConfig) GetId() *v1.InternalID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FeedConfig) GetFeedUrl() string {
	if x != nil {
		return x.FeedUrl
	}
	return ""
}

func (x *FeedConfig) GetAuthorAccount() *v1.InternalID {
	if x != nil {
		return x.AuthorAccount
	}
	return nil
}

func (x *FeedConfig) GetSource() FeedConfigSource {
	if x != nil {
		return x.Source
	}
	return FeedConfigSource_FEED_CONFIG_SOURCE_UNSPECIFIED
}

func (x *FeedConfig) GetStatus() FeedConfigStatus {
	if x != nil {
		return x.Status
	}
	return FeedConfigStatus_FEED_CONFIG_STATUS_UNSPECIFIED
}

func (x *FeedConfig) GetPullInterval() *durationpb.Duration {
	if x != nil {
		return x.PullInterval
	}
	return nil
}

func (x *FeedConfig) GetLatestPullTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LatestPullTime
	}
	return nil
}

type ListFeedsResponse_FeedWithConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Feed   *v1.Feed    `protobuf:"bytes,1,opt,name=feed,proto3" json:"feed,omitempty"`
	Config *FeedConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ListFeedsResponse_FeedWithConfig) Reset() {
	*x = ListFeedsResponse_FeedWithConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFeedsResponse_FeedWithConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedsResponse_FeedWithConfig) ProtoMessage() {}

func (x *ListFeedsResponse_FeedWithConfig) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedsResponse_FeedWithConfig.ProtoReflect.Descriptor instead.
func (*ListFeedsResponse_FeedWithConfig) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListFeedsResponse_FeedWithConfig) GetFeed() *v1.Feed {
	if x != nil {
		return x.Feed
	}
	return nil
}

func (x *ListFeedsResponse_FeedWithConfig) GetConfig() *FeedConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ListFeedItemsResponse_FeedItemIDWithFeedID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeedId *v1.InternalID `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	ItemId *v1.InternalID `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
}

func (x *ListFeedItemsResponse_FeedItemIDWithFeedID) Reset() {
	*x = ListFeedItemsResponse_FeedItemIDWithFeedID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFeedItemsResponse_FeedItemIDWithFeedID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemsResponse_FeedItemIDWithFeedID) ProtoMessage() {}

func (x *ListFeedItemsResponse_FeedItemIDWithFeedID) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_yesod_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemsResponse_FeedItemIDWithFeedID.ProtoReflect.Descriptor instead.
func (*ListFeedItemsResponse_FeedItemIDWithFeedID) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_yesod_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListFeedItemsResponse_FeedItemIDWithFeedID) GetFeedId() *v1.InternalID {
	if x != nil {
		return x.FeedId
	}
	return nil
}

func (x *ListFeedItemsResponse_FeedItemIDWithFeedID) GetItemId() *v1.InternalID {
	if x != nil {
		return x.ItemId
	}
	return nil
}

var File_librarian_sephirah_v1_yesod_proto protoreflect.FileDescriptor

var file_librarian_sephirah_v1_yesod_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2f, 0x73, 0x65, 0x70, 0x68,
	0x69, 0x72, 0x61, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x79, 0x65, 0x73, 0x6f, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x73,
	0x65, 0x70, 0x68, 0x69, 0x72, 0x61, 0x68, 0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x6c, 0x69, 0x62,
	0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x39, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x73, 0x65,
	0x70, 0x68, 0x69, 0x72, 0x61, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x44, 0x0a, 0x18,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x54, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x73, 0x65, 0x70, 0x68, 0x69, 0x72,
	0x61, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x1a, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0xde, 0x02, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x65,
	0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x69, 0x62, 0x72,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x12, 0x35,
	0x0a, 0x09, 0x69, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x52, 0x08, 0x69, 0x64, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x10, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f,
	0x69, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x52, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x49, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x4c, 0x0a, 0x0d, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0e,
	0x32, 0x27, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x73, 0x65, 0x70,
	0x68, 0x69, 0x72, 0x61, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x4c, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x27,
	0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x73, 0x65, 0x70, 0x68, 0x69,
	0x72, 0x61, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0xa3, 0x02, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65,
	0x65, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6c, 0x69,
	0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x67, 0x12, 0x63, 0x0a, 0x11, 0x66, 0x65, 0x65, 0x64, 0x73, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x6c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x73, 0x65, 0x70, 0x68, 0x69, 0x72, 0x61,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x65, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x57, 0x69, 0x74, 0x68, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0f, 0x66, 0x65, 0x65, 0x64, 0x73, 0x57, 0x69, 0x74, 0x68,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x73, 0x0a, 0x0e, 0x46, 0x65, 0x65, 0x64, 0x57, 0x69,
	0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x26, 0x0a, 0x04, 0x66, 0x65, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69,
	0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x52, 0x04, 0x66, 0x65, 0x65, 0x64,
	0x12, 0x39, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x73, 0x65, 0x70,
	0x68, 0x69, 0x72, 0x61, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x87, 0x02, 0x0a, 0x14,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x12, 0x3e, 0x0a, 0x0e, 0x66, 0x65, 0x65,
	0x64, 0x5f, 0x69, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x52, 0x0c, 0x66, 0x65, 0x65,
	0x64, 0x49, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x10, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x52, 0x0e, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x36, 0x0a,
	0x17, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x15,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0xa4, 0x02, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65,
	0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x34, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x67, 0x12, 0x57, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x2e, 0x73, 0x65, 0x70, 0x68, 0x69, 0x72, 0x61, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x46, 0x65, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x57, 0x69, 0x74,
	0x68, 0x46, 0x65, 0x65, 0x64, 0x49, 0x44, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x7c,
	0x0a, 0x14, 0x46, 0x65, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x57, 0x69, 0x74, 0x68,
	0x46, 0x65, 0x65, 0x64, 0x49, 0x44, 0x12, 0x31, 0x0a, 0x07, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49,
	0x44, 0x52, 0x06, 0x66, 0x65, 0x65, 0x64, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x07, 0x69, 0x74, 0x65,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x62,
	0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x49, 0x44, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x46, 0x65, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22,
	0x46, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x46, 0x65, 0x65, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x03, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x49, 0x44, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x49, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x46, 0x65, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0xb4, 0x03, 0x0a, 0x0a, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x66,
	0x65, 0x65, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66,
	0x65, 0x65, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x3f, 0x0a, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x69, 0x61, 0x6e, 0x2e, 0x73, 0x65, 0x70, 0x68, 0x69, 0x72, 0x61, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x2e, 0x73, 0x65, 0x70, 0x68, 0x69, 0x72, 0x61, 0x68, 0x2e, 0x76, 0x31,
	0x2e, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3e, 0x0a, 0x0d, 0x70, 0x75, 0x6c,
	0x6c, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x70, 0x75, 0x6c,
	0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x49, 0x0a, 0x10, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x5f, 0x70, 0x75, 0x6c, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48,
	0x00, 0x52, 0x0e, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x50, 0x75, 0x6c, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x88, 0x01, 0x01, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f,
	0x70, 0x75, 0x6c, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x2a, 0x75, 0x0a, 0x10, 0x46, 0x65, 0x65,
	0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a,
	0x1e, 0x46, 0x45, 0x45, 0x44, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x1d, 0x0a, 0x19, 0x46, 0x45, 0x45, 0x44, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01,
	0x12, 0x1e, 0x0a, 0x1a, 0x46, 0x45, 0x45, 0x44, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x55, 0x53, 0x50, 0x45, 0x4e, 0x44, 0x10, 0x02,
	0x2a, 0x55, 0x0a, 0x10, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x1e, 0x46, 0x45, 0x45, 0x44, 0x5f, 0x43, 0x4f, 0x4e,
	0x46, 0x49, 0x47, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x46, 0x45, 0x45, 0x44,
	0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x43,
	0x4f, 0x4d, 0x4d, 0x4f, 0x4e, 0x10, 0x01, 0x42, 0x5d, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x75, 0x69, 0x68, 0x75, 0x62, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x2f, 0x73, 0x65, 0x70, 0x68, 0x69, 0x72, 0x61, 0x68, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0xaa, 0x02, 0x23, 0x54, 0x75, 0x69, 0x48, 0x75, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x2e, 0x53, 0x65, 0x70, 0x68, 0x69,
	0x72, 0x61, 0x68, 0x2e, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_librarian_sephirah_v1_yesod_proto_rawDescOnce sync.Once
	file_librarian_sephirah_v1_yesod_proto_rawDescData = file_librarian_sephirah_v1_yesod_proto_rawDesc
)

func file_librarian_sephirah_v1_yesod_proto_rawDescGZIP() []byte {
	file_librarian_sephirah_v1_yesod_proto_rawDescOnce.Do(func() {
		file_librarian_sephirah_v1_yesod_proto_rawDescData = protoimpl.X.CompressGZIP(file_librarian_sephirah_v1_yesod_proto_rawDescData)
	})
	return file_librarian_sephirah_v1_yesod_proto_rawDescData
}

var file_librarian_sephirah_v1_yesod_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_librarian_sephirah_v1_yesod_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_librarian_sephirah_v1_yesod_proto_goTypes = []interface{}{
	(FeedConfigStatus)(0),                              // 0: librarian.sephirah.v1.FeedConfigStatus
	(FeedConfigSource)(0),                              // 1: librarian.sephirah.v1.FeedConfigSource
	(*CreateFeedConfigRequest)(nil),                    // 2: librarian.sephirah.v1.CreateFeedConfigRequest
	(*CreateFeedConfigResponse)(nil),                   // 3: librarian.sephirah.v1.CreateFeedConfigResponse
	(*UpdateFeedConfigRequest)(nil),                    // 4: librarian.sephirah.v1.UpdateFeedConfigRequest
	(*UpdateFeedConfigResponse)(nil),                   // 5: librarian.sephirah.v1.UpdateFeedConfigResponse
	(*ListFeedsRequest)(nil),                           // 6: librarian.sephirah.v1.ListFeedsRequest
	(*ListFeedsResponse)(nil),                          // 7: librarian.sephirah.v1.ListFeedsResponse
	(*ListFeedItemsRequest)(nil),                       // 8: librarian.sephirah.v1.ListFeedItemsRequest
	(*ListFeedItemsResponse)(nil),                      // 9: librarian.sephirah.v1.ListFeedItemsResponse
	(*GetFeedItemRequest)(nil),                         // 10: librarian.sephirah.v1.GetFeedItemRequest
	(*GetFeedItemResponse)(nil),                        // 11: librarian.sephirah.v1.GetFeedItemResponse
	(*GetBatchFeedItemsRequest)(nil),                   // 12: librarian.sephirah.v1.GetBatchFeedItemsRequest
	(*GetBatchFeedItemsResponse)(nil),                  // 13: librarian.sephirah.v1.GetBatchFeedItemsResponse
	(*FeedConfig)(nil),                                 // 14: librarian.sephirah.v1.FeedConfig
	(*ListFeedsResponse_FeedWithConfig)(nil),           // 15: librarian.sephirah.v1.ListFeedsResponse.FeedWithConfig
	(*ListFeedItemsResponse_FeedItemIDWithFeedID)(nil), // 16: librarian.sephirah.v1.ListFeedItemsResponse.FeedItemIDWithFeedID
	(*v1.InternalID)(nil),                              // 17: librarian.v1.InternalID
	(*v1.PagingRequest)(nil),                           // 18: librarian.v1.PagingRequest
	(*v1.PagingResponse)(nil),                          // 19: librarian.v1.PagingResponse
	(*v1.FeedItem)(nil),                                // 20: librarian.v1.FeedItem
	(*durationpb.Duration)(nil),                        // 21: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),                      // 22: google.protobuf.Timestamp
	(*v1.Feed)(nil),                                    // 23: librarian.v1.Feed
}
var file_librarian_sephirah_v1_yesod_proto_depIdxs = []int32{
	14, // 0: librarian.sephirah.v1.CreateFeedConfigRequest.config:type_name -> librarian.sephirah.v1.FeedConfig
	17, // 1: librarian.sephirah.v1.CreateFeedConfigResponse.id:type_name -> librarian.v1.InternalID
	14, // 2: librarian.sephirah.v1.UpdateFeedConfigRequest.config:type_name -> librarian.sephirah.v1.FeedConfig
	18, // 3: librarian.sephirah.v1.ListFeedsRequest.paging:type_name -> librarian.v1.PagingRequest
	17, // 4: librarian.sephirah.v1.ListFeedsRequest.id_filter:type_name -> librarian.v1.InternalID
	17, // 5: librarian.sephirah.v1.ListFeedsRequest.author_id_filter:type_name -> librarian.v1.InternalID
	1,  // 6: librarian.sephirah.v1.ListFeedsRequest.source_filter:type_name -> librarian.sephirah.v1.FeedConfigSource
	0,  // 7: librarian.sephirah.v1.ListFeedsRequest.status_filter:type_name -> librarian.sephirah.v1.FeedConfigStatus
	19, // 8: librarian.sephirah.v1.ListFeedsResponse.paging:type_name -> librarian.v1.PagingResponse
	15, // 9: librarian.sephirah.v1.ListFeedsResponse.feeds_with_config:type_name -> librarian.sephirah.v1.ListFeedsResponse.FeedWithConfig
	18, // 10: librarian.sephirah.v1.ListFeedItemsRequest.paging:type_name -> librarian.v1.PagingRequest
	17, // 11: librarian.sephirah.v1.ListFeedItemsRequest.feed_id_filter:type_name -> librarian.v1.InternalID
	17, // 12: librarian.sephirah.v1.ListFeedItemsRequest.author_id_filter:type_name -> librarian.v1.InternalID
	19, // 13: librarian.sephirah.v1.ListFeedItemsResponse.paging:type_name -> librarian.v1.PagingResponse
	16, // 14: librarian.sephirah.v1.ListFeedItemsResponse.items:type_name -> librarian.sephirah.v1.ListFeedItemsResponse.FeedItemIDWithFeedID
	17, // 15: librarian.sephirah.v1.GetFeedItemRequest.id:type_name -> librarian.v1.InternalID
	20, // 16: librarian.sephirah.v1.GetFeedItemResponse.item:type_name -> librarian.v1.FeedItem
	17, // 17: librarian.sephirah.v1.GetBatchFeedItemsRequest.ids:type_name -> librarian.v1.InternalID
	20, // 18: librarian.sephirah.v1.GetBatchFeedItemsResponse.items:type_name -> librarian.v1.FeedItem
	17, // 19: librarian.sephirah.v1.FeedConfig.id:type_name -> librarian.v1.InternalID
	17, // 20: librarian.sephirah.v1.FeedConfig.author_account:type_name -> librarian.v1.InternalID
	1,  // 21: librarian.sephirah.v1.FeedConfig.source:type_name -> librarian.sephirah.v1.FeedConfigSource
	0,  // 22: librarian.sephirah.v1.FeedConfig.status:type_name -> librarian.sephirah.v1.FeedConfigStatus
	21, // 23: librarian.sephirah.v1.FeedConfig.pull_interval:type_name -> google.protobuf.Duration
	22, // 24: librarian.sephirah.v1.FeedConfig.latest_pull_time:type_name -> google.protobuf.Timestamp
	23, // 25: librarian.sephirah.v1.ListFeedsResponse.FeedWithConfig.feed:type_name -> librarian.v1.Feed
	14, // 26: librarian.sephirah.v1.ListFeedsResponse.FeedWithConfig.config:type_name -> librarian.sephirah.v1.FeedConfig
	17, // 27: librarian.sephirah.v1.ListFeedItemsResponse.FeedItemIDWithFeedID.feed_id:type_name -> librarian.v1.InternalID
	17, // 28: librarian.sephirah.v1.ListFeedItemsResponse.FeedItemIDWithFeedID.item_id:type_name -> librarian.v1.InternalID
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_librarian_sephirah_v1_yesod_proto_init() }
func file_librarian_sephirah_v1_yesod_proto_init() {
	if File_librarian_sephirah_v1_yesod_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_librarian_sephirah_v1_yesod_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFeedConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFeedConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFeedConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFeedConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFeedsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFeedsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFeedItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFeedItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFeedItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFeedItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBatchFeedItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBatchFeedItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFeedsResponse_FeedWithConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_librarian_sephirah_v1_yesod_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFeedItemsResponse_FeedItemIDWithFeedID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_librarian_sephirah_v1_yesod_proto_msgTypes[12].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_librarian_sephirah_v1_yesod_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_librarian_sephirah_v1_yesod_proto_goTypes,
		DependencyIndexes: file_librarian_sephirah_v1_yesod_proto_depIdxs,
		EnumInfos:         file_librarian_sephirah_v1_yesod_proto_enumTypes,
		MessageInfos:      file_librarian_sephirah_v1_yesod_proto_msgTypes,
	}.Build()
	File_librarian_sephirah_v1_yesod_proto = out.File
	file_librarian_sephirah_v1_yesod_proto_rawDesc = nil
	file_librarian_sephirah_v1_yesod_proto_goTypes = nil
	file_librarian_sephirah_v1_yesod_proto_depIdxs = nil
}
