// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: librarian/v0/librarian.proto

package librarian

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cd59e1fa82a7926, []int{0}
}
func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(m, src)
}
func (m *PingReq) XXX_Size() int {
	return m.Size()
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

type PingResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResp) Reset()         { *m = PingResp{} }
func (m *PingResp) String() string { return proto.CompactTextString(m) }
func (*PingResp) ProtoMessage()    {}
func (*PingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cd59e1fa82a7926, []int{1}
}
func (m *PingResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PingResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResp.Merge(m, src)
}
func (m *PingResp) XXX_Size() int {
	return m.Size()
}
func (m *PingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResp.DiscardUnknown(m)
}

var xxx_messageInfo_PingResp proto.InternalMessageInfo

type GetTokenReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Base                 *BaseReq `protobuf:"bytes,2047,opt,name=Base,proto3" json:"Base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenReq) Reset()         { *m = GetTokenReq{} }
func (m *GetTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetTokenReq) ProtoMessage()    {}
func (*GetTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cd59e1fa82a7926, []int{2}
}
func (m *GetTokenReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetTokenReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenReq.Merge(m, src)
}
func (m *GetTokenReq) XXX_Size() int {
	return m.Size()
}
func (m *GetTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenReq proto.InternalMessageInfo

func (m *GetTokenReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetTokenReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GetTokenReq) GetBase() *BaseReq {
	if m != nil {
		return m.Base
	}
	return nil
}

type GetTokenResp struct {
	Token                string    `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Base                 *BaseResp `protobuf:"bytes,2047,opt,name=Base,proto3" json:"Base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetTokenResp) Reset()         { *m = GetTokenResp{} }
func (m *GetTokenResp) String() string { return proto.CompactTextString(m) }
func (*GetTokenResp) ProtoMessage()    {}
func (*GetTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cd59e1fa82a7926, []int{3}
}
func (m *GetTokenResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetTokenResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResp.Merge(m, src)
}
func (m *GetTokenResp) XXX_Size() int {
	return m.Size()
}
func (m *GetTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResp proto.InternalMessageInfo

func (m *GetTokenResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetTokenResp) GetBase() *BaseResp {
	if m != nil {
		return m.Base
	}
	return nil
}

func init() {
	proto.RegisterType((*PingReq)(nil), "librarian.PingReq")
	proto.RegisterType((*PingResp)(nil), "librarian.PingResp")
	proto.RegisterType((*GetTokenReq)(nil), "librarian.GetTokenReq")
	proto.RegisterType((*GetTokenResp)(nil), "librarian.GetTokenResp")
}

func init() { proto.RegisterFile("librarian/v0/librarian.proto", fileDescriptor_5cd59e1fa82a7926) }

var fileDescriptor_5cd59e1fa82a7926 = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x95, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0xc6, 0xdd, 0x58, 0x6d, 0x77, 0xfa, 0x47, 0x79, 0x6b, 0x93, 0x74, 0x13, 0x43, 0xcc, 0xc5,
	0x9c, 0x12, 0xa9, 0x17, 0x41, 0x10, 0x12, 0x0b, 0x01, 0x49, 0x25, 0x6c, 0x2d, 0x54, 0x11, 0x64,
	0x36, 0x3b, 0xb4, 0x8b, 0xc9, 0xee, 0x9b, 0x9d, 0x4d, 0xfc, 0x1a, 0x1e, 0x3d, 0x7b, 0xf4, 0x93,
	0x88, 0x27, 0x3f, 0x82, 0x44, 0xf0, 0xe0, 0x97, 0x50, 0x26, 0xb3, 0x7f, 0x66, 0x27, 0x1b, 0xbd,
	0xcd, 0x3c, 0xbf, 0xf7, 0x7d, 0xde, 0x79, 0x86, 0x49, 0x96, 0xd4, 0x27, 0x9e, 0x13, 0xd2, 0xd0,
	0xa3, 0x7e, 0x77, 0xf1, 0xa8, 0x9b, 0x6e, 0x3a, 0x18, 0x06, 0x51, 0x00, 0x66, 0x2a, 0x58, 0x95,
	0x5c, 0xe1, 0x9c, 0xb3, 0x50, 0xd6, 0x58, 0xe5, 0x1c, 0xa0, 0x88, 0xb1, 0x5e, 0xcb, 0xe9, 0x9c,
	0xf9, 0x91, 0xe7, 0xb3, 0x49, 0x0c, 0xf3, 0x6e, 0x0e, 0xe5, 0xac, 0xb0, 0x8b, 0x22, 0xbe, 0x73,
	0x3c, 0xdf, 0x95, 0xb0, 0x65, 0x92, 0xed, 0x91, 0xe7, 0x5f, 0xd9, 0x6c, 0xd6, 0x22, 0x64, 0x47,
	0x2e, 0x39, 0xb6, 0x7c, 0xb2, 0x3b, 0x60, 0xd1, 0xab, 0xe0, 0x3d, 0xf3, 0x6d, 0x36, 0x03, 0x8b,
	0xec, 0x5c, 0x70, 0x16, 0xfa, 0x74, 0xca, 0xaa, 0x46, 0xd3, 0x68, 0x9b, 0x76, 0xba, 0x17, 0x6c,
	0x44, 0x39, 0xff, 0x10, 0x84, 0x6e, 0xb5, 0x24, 0x59, 0xb2, 0x87, 0x87, 0x64, 0xab, 0x4f, 0x39,
	0xab, 0xfe, 0xb9, 0xd3, 0x34, 0xda, 0xbb, 0x27, 0xd0, 0xc9, 0x6e, 0x43, 0xe8, 0x36, 0x9b, 0xd9,
	0xab, 0x82, 0xd6, 0x4b, 0xb2, 0x97, 0xcd, 0xe3, 0x08, 0xf7, 0xc8, 0xad, 0xd5, 0x26, 0x9e, 0x26,
	0x37, 0xd0, 0xce, 0xdb, 0x1d, 0xae, 0xd9, 0x71, 0x94, 0x7e, 0x27, 0xbf, 0x4c, 0x72, 0x77, 0x98,
	0xc0, 0x73, 0x16, 0x2e, 0xbc, 0x31, 0x83, 0x2e, 0xd9, 0x12, 0x01, 0x41, 0x3d, 0x46, 0x1c, 0xde,
	0x3a, 0x5c, 0xd3, 0x38, 0xc2, 0x53, 0xb2, 0x93, 0x9c, 0x0a, 0xca, 0x4a, 0x81, 0x72, 0x35, 0x56,
	0xa5, 0x50, 0xe7, 0x08, 0x3d, 0x42, 0x9e, 0x87, 0x8c, 0x46, 0x4c, 0xdc, 0x14, 0x54, 0x95, 0xb2,
	0x4c, 0x16, 0x06, 0xc7, 0x1b, 0x88, 0xb4, 0xb8, 0x40, 0xb7, 0xc8, 0x22, 0x93, 0x75, 0x0b, 0x95,
	0xc8, 0x08, 0x43, 0x8f, 0x47, 0x2b, 0x03, 0x35, 0x42, 0x22, 0xea, 0x11, 0x32, 0x5d, 0xce, 0x3f,
	0x65, 0x13, 0x56, 0x30, 0x3f, 0x93, 0xf5, 0xf9, 0x2a, 0xe1, 0x08, 0xcf, 0x88, 0x29, 0x43, 0xf5,
	0x10, 0xa1, 0xb2, 0x16, 0xb5, 0x87, 0x28, 0x0c, 0xaa, 0xc5, 0x40, 0xf6, 0xcb, 0x44, 0x7a, 0x7f,
	0xaa, 0xea, 0xfd, 0x0a, 0xe0, 0x08, 0x4f, 0xc8, 0xb6, 0x88, 0x24, 0xba, 0x8f, 0xb4, 0x98, 0x71,
	0x6f, 0xb9, 0x48, 0x96, 0x93, 0x65, 0x16, 0x7d, 0x72, 0xaa, 0xea, 0x93, 0x15, 0xc0, 0x11, 0xce,
	0xc8, 0x81, 0x8c, 0x72, 0x1e, 0xff, 0x4e, 0xa1, 0xbe, 0x96, 0x32, 0x41, 0xc2, 0xe9, 0xfe, 0x3f,
	0xa8, 0xb4, 0x93, 0xc9, 0x0a, 0xed, 0xf2, 0x48, 0xb7, 0xd3, 0x29, 0x47, 0x18, 0x90, 0x3d, 0x11,
	0x36, 0x35, 0xb3, 0xb4, 0x5b, 0x50, 0xad, 0x6a, 0x1b, 0x99, 0x3c, 0x97, 0xcc, 0x5d, 0x78, 0xae,
	0x3c, 0xd2, 0xcf, 0xa5, 0x53, 0x8e, 0xf0, 0x9a, 0x40, 0x7e, 0x04, 0x06, 0x61, 0x04, 0xcd, 0x8d,
	0x27, 0x10, 0x58, 0xd8, 0x3e, 0xf8, 0x4f, 0x85, 0x7c, 0xcd, 0x3d, 0xd7, 0xed, 0x21, 0xf6, 0x3d,
	0xdf, 0xcd, 0xbd, 0xe6, 0x4c, 0xd6, 0x5f, 0xb3, 0x4a, 0x38, 0xc2, 0x0b, 0xb2, 0x6f, 0xb3, 0x69,
	0xb0, 0x60, 0x89, 0x8b, 0x7a, 0x35, 0x39, 0x22, 0x8c, 0xea, 0x9b, 0x21, 0x47, 0x38, 0x25, 0xbb,
	0xf1, 0x73, 0x5b, 0x39, 0x1d, 0xaf, 0x3f, 0xc3, 0xc4, 0xc7, 0xda, 0x84, 0x38, 0xf6, 0x3f, 0x1a,
	0x5f, 0x97, 0x0d, 0xe3, 0xfb, 0xb2, 0x61, 0xfc, 0x58, 0x36, 0x8c, 0x4f, 0x3f, 0x1b, 0x37, 0xc8,
	0xfe, 0x38, 0x98, 0x66, 0x1d, 0xfd, 0x83, 0xf4, 0x7f, 0x70, 0x24, 0xfe, 0xf1, 0x47, 0xc6, 0x9b,
	0xda, 0x95, 0x17, 0x5d, 0xcf, 0x9d, 0xce, 0x38, 0x98, 0x76, 0xa3, 0xb9, 0x77, 0x3d, 0x77, 0xb2,
	0xaf, 0xd4, 0xe7, 0xd2, 0xcd, 0xe1, 0xe5, 0xe5, 0x97, 0x92, 0x99, 0x76, 0x7d, 0x53, 0xd6, 0xcb,
	0xd2, 0x51, 0xba, 0x7e, 0x3b, 0x18, 0xf5, 0xcf, 0x58, 0x44, 0x5d, 0x1a, 0xd1, 0xdf, 0x4a, 0x8d,
	0x73, 0x7b, 0xf5, 0x65, 0x79, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x32, 0xd6, 0x87, 0x08,
	0x07, 0x00, 0x00,
}

func (m *PingReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PingReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *PingResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PingResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *GetTokenReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTokenReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetTokenReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Base != nil {
		{
			size, err := m.Base.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLibrarian(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x7f
		i--
		dAtA[i] = 0xfa
	}
	if len(m.Password) > 0 {
		i -= len(m.Password)
		copy(dAtA[i:], m.Password)
		i = encodeVarintLibrarian(dAtA, i, uint64(len(m.Password)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintLibrarian(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetTokenResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTokenResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetTokenResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Base != nil {
		{
			size, err := m.Base.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLibrarian(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x7f
		i--
		dAtA[i] = 0xfa
	}
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintLibrarian(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLibrarian(dAtA []byte, offset int, v uint64) int {
	offset -= sovLibrarian(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PingReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PingResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetTokenReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovLibrarian(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovLibrarian(uint64(l))
	}
	if m.Base != nil {
		l = m.Base.Size()
		n += 2 + l + sovLibrarian(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *GetTokenResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovLibrarian(uint64(l))
	}
	if m.Base != nil {
		l = m.Base.Size()
		n += 2 + l + sovLibrarian(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovLibrarian(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLibrarian(x uint64) (n int) {
	return sovLibrarian(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PingReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLibrarian
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipLibrarian(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLibrarian
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PingResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLibrarian
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipLibrarian(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLibrarian
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTokenReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLibrarian
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTokenReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTokenReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLibrarian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLibrarian
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLibrarian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLibrarian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLibrarian
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLibrarian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2047:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Base", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLibrarian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLibrarian
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLibrarian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Base == nil {
				m.Base = &BaseReq{}
			}
			if err := m.Base.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLibrarian(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLibrarian
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTokenResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLibrarian
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTokenResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTokenResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLibrarian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLibrarian
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLibrarian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2047:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Base", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLibrarian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLibrarian
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLibrarian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Base == nil {
				m.Base = &BaseResp{}
			}
			if err := m.Base.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLibrarian(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLibrarian
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLibrarian(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLibrarian
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLibrarian
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLibrarian
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLibrarian
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLibrarian
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLibrarian
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLibrarian        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLibrarian          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLibrarian = fmt.Errorf("proto: unexpected end of group")
)
