// source: librarian/sephirah/v1/angela/angela_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var librarian_sephirah_v1_angela_binah_pb = require('../../../../librarian/sephirah/v1/angela/binah_pb.js');
goog.object.extend(proto, librarian_sephirah_v1_angela_binah_pb);
var librarian_sephirah_v1_angela_gebura_pb = require('../../../../librarian/sephirah/v1/angela/gebura_pb.js');
goog.object.extend(proto, librarian_sephirah_v1_angela_gebura_pb);
var librarian_sephirah_v1_angela_tiphereth_pb = require('../../../../librarian/sephirah/v1/angela/tiphereth_pb.js');
goog.object.extend(proto, librarian_sephirah_v1_angela_tiphereth_pb);
var librarian_sephirah_v1_sephirah_base_pb = require('../../../../librarian/sephirah/v1/sephirah/base_pb.js');
goog.object.extend(proto, librarian_sephirah_v1_sephirah_base_pb);
var librarian_v1_wellknown_pb = require('../../../../librarian/v1/wellknown_pb.js');
goog.object.extend(proto, librarian_v1_wellknown_pb);
goog.exportSymbol('proto.librarian.sephirah.v1.angela.GetServerConfigRequest', null, global);
goog.exportSymbol('proto.librarian.sephirah.v1.angela.GetServerConfigResponse', null, global);
goog.exportSymbol('proto.librarian.sephirah.v1.angela.GetServerInformationRequest', null, global);
goog.exportSymbol('proto.librarian.sephirah.v1.angela.GetServerInformationResponse', null, global);
goog.exportSymbol('proto.librarian.sephirah.v1.angela.ServerConfigItem', null, global);
goog.exportSymbol('proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate', null, global);
goog.exportSymbol('proto.librarian.sephirah.v1.angela.ServerConfigSection', null, global);
goog.exportSymbol('proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest', null, global);
goog.exportSymbol('proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.sephirah.v1.angela.GetServerInformationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.librarian.sephirah.v1.angela.GetServerInformationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.sephirah.v1.angela.GetServerInformationRequest.displayName = 'proto.librarian.sephirah.v1.angela.GetServerInformationRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.sephirah.v1.angela.GetServerInformationResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.librarian.sephirah.v1.angela.GetServerInformationResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.sephirah.v1.angela.GetServerInformationResponse.displayName = 'proto.librarian.sephirah.v1.angela.GetServerInformationResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.sephirah.v1.angela.GetServerConfigRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.librarian.sephirah.v1.angela.GetServerConfigRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.sephirah.v1.angela.GetServerConfigRequest.displayName = 'proto.librarian.sephirah.v1.angela.GetServerConfigRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.sephirah.v1.angela.GetServerConfigResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.librarian.sephirah.v1.angela.GetServerConfigResponse.repeatedFields_, null);
};
goog.inherits(proto.librarian.sephirah.v1.angela.GetServerConfigResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.sephirah.v1.angela.GetServerConfigResponse.displayName = 'proto.librarian.sephirah.v1.angela.GetServerConfigResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.repeatedFields_, null);
};
goog.inherits(proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.displayName = 'proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse.displayName = 'proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.librarian.sephirah.v1.angela.ServerConfigSection.repeatedFields_, null);
};
goog.inherits(proto.librarian.sephirah.v1.angela.ServerConfigSection, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.sephirah.v1.angela.ServerConfigSection.displayName = 'proto.librarian.sephirah.v1.angela.ServerConfigSection';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.librarian.sephirah.v1.angela.ServerConfigItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.sephirah.v1.angela.ServerConfigItem.displayName = 'proto.librarian.sephirah.v1.angela.ServerConfigItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.displayName = 'proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.sephirah.v1.angela.GetServerInformationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.sephirah.v1.angela.GetServerInformationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.sephirah.v1.angela.GetServerInformationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.GetServerInformationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
withStatusReport: (f = jspb.Message.getBooleanField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.sephirah.v1.angela.GetServerInformationRequest}
 */
proto.librarian.sephirah.v1.angela.GetServerInformationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.sephirah.v1.angela.GetServerInformationRequest;
  return proto.librarian.sephirah.v1.angela.GetServerInformationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.sephirah.v1.angela.GetServerInformationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.sephirah.v1.angela.GetServerInformationRequest}
 */
proto.librarian.sephirah.v1.angela.GetServerInformationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setWithStatusReport(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.sephirah.v1.angela.GetServerInformationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.sephirah.v1.angela.GetServerInformationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.sephirah.v1.angela.GetServerInformationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.GetServerInformationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {boolean} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool with_status_report = 1;
 * @return {boolean}
 */
proto.librarian.sephirah.v1.angela.GetServerInformationRequest.prototype.getWithStatusReport = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.librarian.sephirah.v1.angela.GetServerInformationRequest} returns this
 */
proto.librarian.sephirah.v1.angela.GetServerInformationRequest.prototype.setWithStatusReport = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.librarian.sephirah.v1.angela.GetServerInformationRequest} returns this
 */
proto.librarian.sephirah.v1.angela.GetServerInformationRequest.prototype.clearWithStatusReport = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.librarian.sephirah.v1.angela.GetServerInformationRequest.prototype.hasWithStatusReport = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.sephirah.v1.angela.GetServerInformationResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.sephirah.v1.angela.GetServerInformationResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.sephirah.v1.angela.GetServerInformationResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.GetServerInformationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
serverInformation: (f = msg.getServerInformation()) && librarian_sephirah_v1_sephirah_base_pb.ServerInformation.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.sephirah.v1.angela.GetServerInformationResponse}
 */
proto.librarian.sephirah.v1.angela.GetServerInformationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.sephirah.v1.angela.GetServerInformationResponse;
  return proto.librarian.sephirah.v1.angela.GetServerInformationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.sephirah.v1.angela.GetServerInformationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.sephirah.v1.angela.GetServerInformationResponse}
 */
proto.librarian.sephirah.v1.angela.GetServerInformationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new librarian_sephirah_v1_sephirah_base_pb.ServerInformation;
      reader.readMessage(value,librarian_sephirah_v1_sephirah_base_pb.ServerInformation.deserializeBinaryFromReader);
      msg.setServerInformation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.sephirah.v1.angela.GetServerInformationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.sephirah.v1.angela.GetServerInformationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.sephirah.v1.angela.GetServerInformationResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.GetServerInformationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerInformation();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      librarian_sephirah_v1_sephirah_base_pb.ServerInformation.serializeBinaryToWriter
    );
  }
};


/**
 * optional librarian.sephirah.v1.sephirah.ServerInformation server_information = 1;
 * @return {?proto.librarian.sephirah.v1.sephirah.ServerInformation}
 */
proto.librarian.sephirah.v1.angela.GetServerInformationResponse.prototype.getServerInformation = function() {
  return /** @type{?proto.librarian.sephirah.v1.sephirah.ServerInformation} */ (
    jspb.Message.getWrapperField(this, librarian_sephirah_v1_sephirah_base_pb.ServerInformation, 1));
};


/**
 * @param {?proto.librarian.sephirah.v1.sephirah.ServerInformation|undefined} value
 * @return {!proto.librarian.sephirah.v1.angela.GetServerInformationResponse} returns this
*/
proto.librarian.sephirah.v1.angela.GetServerInformationResponse.prototype.setServerInformation = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.librarian.sephirah.v1.angela.GetServerInformationResponse} returns this
 */
proto.librarian.sephirah.v1.angela.GetServerInformationResponse.prototype.clearServerInformation = function() {
  return this.setServerInformation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.librarian.sephirah.v1.angela.GetServerInformationResponse.prototype.hasServerInformation = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.sephirah.v1.angela.GetServerConfigRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.sephirah.v1.angela.GetServerConfigRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.sephirah.v1.angela.GetServerConfigRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.GetServerConfigRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.sephirah.v1.angela.GetServerConfigRequest}
 */
proto.librarian.sephirah.v1.angela.GetServerConfigRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.sephirah.v1.angela.GetServerConfigRequest;
  return proto.librarian.sephirah.v1.angela.GetServerConfigRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.sephirah.v1.angela.GetServerConfigRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.sephirah.v1.angela.GetServerConfigRequest}
 */
proto.librarian.sephirah.v1.angela.GetServerConfigRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.sephirah.v1.angela.GetServerConfigRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.sephirah.v1.angela.GetServerConfigRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.sephirah.v1.angela.GetServerConfigRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.GetServerConfigRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.librarian.sephirah.v1.angela.GetServerConfigResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.sephirah.v1.angela.GetServerConfigResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.sephirah.v1.angela.GetServerConfigResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.sephirah.v1.angela.GetServerConfigResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.GetServerConfigResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
sectionsList: jspb.Message.toObjectList(msg.getSectionsList(),
    proto.librarian.sephirah.v1.angela.ServerConfigSection.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.sephirah.v1.angela.GetServerConfigResponse}
 */
proto.librarian.sephirah.v1.angela.GetServerConfigResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.sephirah.v1.angela.GetServerConfigResponse;
  return proto.librarian.sephirah.v1.angela.GetServerConfigResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.sephirah.v1.angela.GetServerConfigResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.sephirah.v1.angela.GetServerConfigResponse}
 */
proto.librarian.sephirah.v1.angela.GetServerConfigResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.librarian.sephirah.v1.angela.ServerConfigSection;
      reader.readMessage(value,proto.librarian.sephirah.v1.angela.ServerConfigSection.deserializeBinaryFromReader);
      msg.addSections(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.sephirah.v1.angela.GetServerConfigResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.sephirah.v1.angela.GetServerConfigResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.sephirah.v1.angela.GetServerConfigResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.GetServerConfigResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSectionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.librarian.sephirah.v1.angela.ServerConfigSection.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ServerConfigSection sections = 1;
 * @return {!Array<!proto.librarian.sephirah.v1.angela.ServerConfigSection>}
 */
proto.librarian.sephirah.v1.angela.GetServerConfigResponse.prototype.getSectionsList = function() {
  return /** @type{!Array<!proto.librarian.sephirah.v1.angela.ServerConfigSection>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.librarian.sephirah.v1.angela.ServerConfigSection, 1));
};


/**
 * @param {!Array<!proto.librarian.sephirah.v1.angela.ServerConfigSection>} value
 * @return {!proto.librarian.sephirah.v1.angela.GetServerConfigResponse} returns this
*/
proto.librarian.sephirah.v1.angela.GetServerConfigResponse.prototype.setSectionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.librarian.sephirah.v1.angela.ServerConfigSection=} opt_value
 * @param {number=} opt_index
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigSection}
 */
proto.librarian.sephirah.v1.angela.GetServerConfigResponse.prototype.addSections = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.librarian.sephirah.v1.angela.ServerConfigSection, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.librarian.sephirah.v1.angela.GetServerConfigResponse} returns this
 */
proto.librarian.sephirah.v1.angela.GetServerConfigResponse.prototype.clearSectionsList = function() {
  return this.setSectionsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.librarian.sephirah.v1.angela.ServerConfigItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest}
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest;
  return proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest}
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.librarian.sephirah.v1.angela.ServerConfigItem;
      reader.readMessage(value,proto.librarian.sephirah.v1.angela.ServerConfigItem.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.librarian.sephirah.v1.angela.ServerConfigItem.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ServerConfigItem items = 1;
 * @return {!Array<!proto.librarian.sephirah.v1.angela.ServerConfigItem>}
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.librarian.sephirah.v1.angela.ServerConfigItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.librarian.sephirah.v1.angela.ServerConfigItem, 1));
};


/**
 * @param {!Array<!proto.librarian.sephirah.v1.angela.ServerConfigItem>} value
 * @return {!proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest} returns this
*/
proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.librarian.sephirah.v1.angela.ServerConfigItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItem}
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.librarian.sephirah.v1.angela.ServerConfigItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest} returns this
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigRequest.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse}
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse;
  return proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse}
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.UpdateServerConfigResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.sephirah.v1.angela.ServerConfigSection.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.sephirah.v1.angela.ServerConfigSection} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
name: (f = msg.getName()) && librarian_v1_wellknown_pb.I18NString.toObject(includeInstance, f),
description: (f = msg.getDescription()) && librarian_v1_wellknown_pb.I18NString.toObject(includeInstance, f),
itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.librarian.sephirah.v1.angela.ServerConfigItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigSection}
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.sephirah.v1.angela.ServerConfigSection;
  return proto.librarian.sephirah.v1.angela.ServerConfigSection.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.sephirah.v1.angela.ServerConfigSection} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigSection}
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new librarian_v1_wellknown_pb.I18NString;
      reader.readMessage(value,librarian_v1_wellknown_pb.I18NString.deserializeBinaryFromReader);
      msg.setName(value);
      break;
    case 3:
      var value = new librarian_v1_wellknown_pb.I18NString;
      reader.readMessage(value,librarian_v1_wellknown_pb.I18NString.deserializeBinaryFromReader);
      msg.setDescription(value);
      break;
    case 4:
      var value = new proto.librarian.sephirah.v1.angela.ServerConfigItem;
      reader.readMessage(value,proto.librarian.sephirah.v1.angela.ServerConfigItem.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.sephirah.v1.angela.ServerConfigSection.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.sephirah.v1.angela.ServerConfigSection} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      librarian_v1_wellknown_pb.I18NString.serializeBinaryToWriter
    );
  }
  f = message.getDescription();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      librarian_v1_wellknown_pb.I18NString.serializeBinaryToWriter
    );
  }
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.librarian.sephirah.v1.angela.ServerConfigItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigSection} returns this
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional librarian.v1.I18NString name = 2;
 * @return {?proto.librarian.v1.I18NString}
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.getName = function() {
  return /** @type{?proto.librarian.v1.I18NString} */ (
    jspb.Message.getWrapperField(this, librarian_v1_wellknown_pb.I18NString, 2));
};


/**
 * @param {?proto.librarian.v1.I18NString|undefined} value
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigSection} returns this
*/
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.setName = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigSection} returns this
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.clearName = function() {
  return this.setName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.hasName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional librarian.v1.I18NString description = 3;
 * @return {?proto.librarian.v1.I18NString}
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.getDescription = function() {
  return /** @type{?proto.librarian.v1.I18NString} */ (
    jspb.Message.getWrapperField(this, librarian_v1_wellknown_pb.I18NString, 3));
};


/**
 * @param {?proto.librarian.v1.I18NString|undefined} value
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigSection} returns this
*/
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.setDescription = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigSection} returns this
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.clearDescription = function() {
  return this.setDescription(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.hasDescription = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated ServerConfigItem items = 4;
 * @return {!Array<!proto.librarian.sephirah.v1.angela.ServerConfigItem>}
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.librarian.sephirah.v1.angela.ServerConfigItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.librarian.sephirah.v1.angela.ServerConfigItem, 4));
};


/**
 * @param {!Array<!proto.librarian.sephirah.v1.angela.ServerConfigItem>} value
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigSection} returns this
*/
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.librarian.sephirah.v1.angela.ServerConfigItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItem}
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.librarian.sephirah.v1.angela.ServerConfigItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigSection} returns this
 */
proto.librarian.sephirah.v1.angela.ServerConfigSection.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.sephirah.v1.angela.ServerConfigItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.sephirah.v1.angela.ServerConfigItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
name: (f = msg.getName()) && librarian_v1_wellknown_pb.I18NString.toObject(includeInstance, f),
description: (f = msg.getDescription()) && librarian_v1_wellknown_pb.I18NString.toObject(includeInstance, f),
defaultValue: jspb.Message.getFieldWithDefault(msg, 4, ""),
currentValue: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItem}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.sephirah.v1.angela.ServerConfigItem;
  return proto.librarian.sephirah.v1.angela.ServerConfigItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.sephirah.v1.angela.ServerConfigItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItem}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new librarian_v1_wellknown_pb.I18NString;
      reader.readMessage(value,librarian_v1_wellknown_pb.I18NString.deserializeBinaryFromReader);
      msg.setName(value);
      break;
    case 3:
      var value = new librarian_v1_wellknown_pb.I18NString;
      reader.readMessage(value,librarian_v1_wellknown_pb.I18NString.deserializeBinaryFromReader);
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDefaultValue(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrentValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.sephirah.v1.angela.ServerConfigItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.sephirah.v1.angela.ServerConfigItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      librarian_v1_wellknown_pb.I18NString.serializeBinaryToWriter
    );
  }
  f = message.getDescription();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      librarian_v1_wellknown_pb.I18NString.serializeBinaryToWriter
    );
  }
  f = message.getDefaultValue();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCurrentValue();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItem} returns this
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional librarian.v1.I18NString name = 2;
 * @return {?proto.librarian.v1.I18NString}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.getName = function() {
  return /** @type{?proto.librarian.v1.I18NString} */ (
    jspb.Message.getWrapperField(this, librarian_v1_wellknown_pb.I18NString, 2));
};


/**
 * @param {?proto.librarian.v1.I18NString|undefined} value
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItem} returns this
*/
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.setName = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItem} returns this
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.clearName = function() {
  return this.setName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.hasName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional librarian.v1.I18NString description = 3;
 * @return {?proto.librarian.v1.I18NString}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.getDescription = function() {
  return /** @type{?proto.librarian.v1.I18NString} */ (
    jspb.Message.getWrapperField(this, librarian_v1_wellknown_pb.I18NString, 3));
};


/**
 * @param {?proto.librarian.v1.I18NString|undefined} value
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItem} returns this
*/
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.setDescription = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItem} returns this
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.clearDescription = function() {
  return this.setDescription(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.hasDescription = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string default_value = 4;
 * @return {string}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.getDefaultValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItem} returns this
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.setDefaultValue = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string current_value = 5;
 * @return {string}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.getCurrentValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItem} returns this
 */
proto.librarian.sephirah.v1.angela.ServerConfigItem.prototype.setCurrentValue = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
value: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate;
  return proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate} returns this
 */
proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate} returns this
 */
proto.librarian.sephirah.v1.angela.ServerConfigItemUpdate.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.librarian.sephirah.v1.angela);
