// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: librarian/sephirah/v1/sephirah/yesod.proto

package v1

import (
	v1 "github.com/tuihub/protos/pkg/librarian/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedConfigStatus int32

const (
	FeedConfigStatus_FEED_CONFIG_STATUS_UNSPECIFIED FeedConfigStatus = 0
	FeedConfigStatus_FEED_CONFIG_STATUS_ACTIVE      FeedConfigStatus = 1
	FeedConfigStatus_FEED_CONFIG_STATUS_SUSPEND     FeedConfigStatus = 2
)

// Enum value maps for FeedConfigStatus.
var (
	FeedConfigStatus_name = map[int32]string{
		0: "FEED_CONFIG_STATUS_UNSPECIFIED",
		1: "FEED_CONFIG_STATUS_ACTIVE",
		2: "FEED_CONFIG_STATUS_SUSPEND",
	}
	FeedConfigStatus_value = map[string]int32{
		"FEED_CONFIG_STATUS_UNSPECIFIED": 0,
		"FEED_CONFIG_STATUS_ACTIVE":      1,
		"FEED_CONFIG_STATUS_SUSPEND":     2,
	}
)

func (x FeedConfigStatus) Enum() *FeedConfigStatus {
	p := new(FeedConfigStatus)
	*p = x
	return p
}

func (x FeedConfigStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedConfigStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_enumTypes[0].Descriptor()
}

func (FeedConfigStatus) Type() protoreflect.EnumType {
	return &file_librarian_sephirah_v1_sephirah_yesod_proto_enumTypes[0]
}

func (x FeedConfigStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedConfigStatus.Descriptor instead.
func (FeedConfigStatus) EnumDescriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{0}
}

type FeedConfigPullStatus int32

const (
	FeedConfigPullStatus_FEED_CONFIG_PULL_STATUS_UNSPECIFIED FeedConfigPullStatus = 0
	FeedConfigPullStatus_FEED_CONFIG_PULL_STATUS_PROCESSING  FeedConfigPullStatus = 1
	FeedConfigPullStatus_FEED_CONFIG_PULL_STATUS_SUCCESS     FeedConfigPullStatus = 2
	FeedConfigPullStatus_FEED_CONFIG_PULL_STATUS_FAILED      FeedConfigPullStatus = 3
)

// Enum value maps for FeedConfigPullStatus.
var (
	FeedConfigPullStatus_name = map[int32]string{
		0: "FEED_CONFIG_PULL_STATUS_UNSPECIFIED",
		1: "FEED_CONFIG_PULL_STATUS_PROCESSING",
		2: "FEED_CONFIG_PULL_STATUS_SUCCESS",
		3: "FEED_CONFIG_PULL_STATUS_FAILED",
	}
	FeedConfigPullStatus_value = map[string]int32{
		"FEED_CONFIG_PULL_STATUS_UNSPECIFIED": 0,
		"FEED_CONFIG_PULL_STATUS_PROCESSING":  1,
		"FEED_CONFIG_PULL_STATUS_SUCCESS":     2,
		"FEED_CONFIG_PULL_STATUS_FAILED":      3,
	}
)

func (x FeedConfigPullStatus) Enum() *FeedConfigPullStatus {
	p := new(FeedConfigPullStatus)
	*p = x
	return p
}

func (x FeedConfigPullStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedConfigPullStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_enumTypes[1].Descriptor()
}

func (FeedConfigPullStatus) Type() protoreflect.EnumType {
	return &file_librarian_sephirah_v1_sephirah_yesod_proto_enumTypes[1]
}

func (x FeedConfigPullStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedConfigPullStatus.Descriptor instead.
func (FeedConfigPullStatus) EnumDescriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{1}
}

type CreateFeedConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *FeedConfig            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedConfigRequest) Reset() {
	*x = CreateFeedConfigRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedConfigRequest) ProtoMessage() {}

func (x *CreateFeedConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateFeedConfigRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFeedConfigRequest) GetConfig() *FeedConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateFeedConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.InternalID         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedConfigResponse) Reset() {
	*x = CreateFeedConfigResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedConfigResponse) ProtoMessage() {}

func (x *CreateFeedConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateFeedConfigResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFeedConfigResponse) GetId() *v1.InternalID {
	if x != nil {
		return x.Id
	}
	return nil
}

type UpdateFeedConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *FeedConfig            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFeedConfigRequest) Reset() {
	*x = UpdateFeedConfigRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeedConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedConfigRequest) ProtoMessage() {}

func (x *UpdateFeedConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateFeedConfigRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateFeedConfigRequest) GetConfig() *FeedConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateFeedConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFeedConfigResponse) Reset() {
	*x = UpdateFeedConfigResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeedConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedConfigResponse) ProtoMessage() {}

func (x *UpdateFeedConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateFeedConfigResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{3}
}

type ListFeedConfigsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Paging         *v1.PagingRequest      `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	IdFilter       []*v1.InternalID       `protobuf:"bytes,2,rep,name=id_filter,json=idFilter,proto3" json:"id_filter,omitempty"`
	StatusFilter   []FeedConfigStatus     `protobuf:"varint,5,rep,packed,name=status_filter,json=statusFilter,proto3,enum=librarian.sephirah.v1.sephirah.FeedConfigStatus" json:"status_filter,omitempty"`
	CategoryFilter []string               `protobuf:"bytes,6,rep,name=category_filter,json=categoryFilter,proto3" json:"category_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListFeedConfigsRequest) Reset() {
	*x = ListFeedConfigsRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedConfigsRequest) ProtoMessage() {}

func (x *ListFeedConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedConfigsRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{4}
}

func (x *ListFeedConfigsRequest) GetPaging() *v1.PagingRequest {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListFeedConfigsRequest) GetIdFilter() []*v1.InternalID {
	if x != nil {
		return x.IdFilter
	}
	return nil
}

func (x *ListFeedConfigsRequest) GetStatusFilter() []FeedConfigStatus {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

func (x *ListFeedConfigsRequest) GetCategoryFilter() []string {
	if x != nil {
		return x.CategoryFilter
	}
	return nil
}

type ListFeedConfigsResponse struct {
	state           protoimpl.MessageState                    `protogen:"open.v1"`
	Paging          *v1.PagingResponse                        `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	FeedsWithConfig []*ListFeedConfigsResponse_FeedWithConfig `protobuf:"bytes,2,rep,name=feeds_with_config,json=feedsWithConfig,proto3" json:"feeds_with_config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListFeedConfigsResponse) Reset() {
	*x = ListFeedConfigsResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedConfigsResponse) ProtoMessage() {}

func (x *ListFeedConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedConfigsResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{5}
}

func (x *ListFeedConfigsResponse) GetPaging() *v1.PagingResponse {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListFeedConfigsResponse) GetFeedsWithConfig() []*ListFeedConfigsResponse_FeedWithConfig {
	if x != nil {
		return x.FeedsWithConfig
	}
	return nil
}

type CreateFeedActionSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionSet     *FeedActionSet         `protobuf:"bytes,1,opt,name=action_set,json=actionSet,proto3" json:"action_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedActionSetRequest) Reset() {
	*x = CreateFeedActionSetRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedActionSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedActionSetRequest) ProtoMessage() {}

func (x *CreateFeedActionSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedActionSetRequest.ProtoReflect.Descriptor instead.
func (*CreateFeedActionSetRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{6}
}

func (x *CreateFeedActionSetRequest) GetActionSet() *FeedActionSet {
	if x != nil {
		return x.ActionSet
	}
	return nil
}

type CreateFeedActionSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.InternalID         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedActionSetResponse) Reset() {
	*x = CreateFeedActionSetResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedActionSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedActionSetResponse) ProtoMessage() {}

func (x *CreateFeedActionSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedActionSetResponse.ProtoReflect.Descriptor instead.
func (*CreateFeedActionSetResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{7}
}

func (x *CreateFeedActionSetResponse) GetId() *v1.InternalID {
	if x != nil {
		return x.Id
	}
	return nil
}

type UpdateFeedActionSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionSet     *FeedActionSet         `protobuf:"bytes,1,opt,name=action_set,json=actionSet,proto3" json:"action_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFeedActionSetRequest) Reset() {
	*x = UpdateFeedActionSetRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeedActionSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedActionSetRequest) ProtoMessage() {}

func (x *UpdateFeedActionSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedActionSetRequest.ProtoReflect.Descriptor instead.
func (*UpdateFeedActionSetRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFeedActionSetRequest) GetActionSet() *FeedActionSet {
	if x != nil {
		return x.ActionSet
	}
	return nil
}

type UpdateFeedActionSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFeedActionSetResponse) Reset() {
	*x = UpdateFeedActionSetResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeedActionSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedActionSetResponse) ProtoMessage() {}

func (x *UpdateFeedActionSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedActionSetResponse.ProtoReflect.Descriptor instead.
func (*UpdateFeedActionSetResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{9}
}

type ListFeedActionSetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *v1.PagingRequest      `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedActionSetsRequest) Reset() {
	*x = ListFeedActionSetsRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedActionSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedActionSetsRequest) ProtoMessage() {}

func (x *ListFeedActionSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedActionSetsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedActionSetsRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{10}
}

func (x *ListFeedActionSetsRequest) GetPaging() *v1.PagingRequest {
	if x != nil {
		return x.Paging
	}
	return nil
}

type ListFeedActionSetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *v1.PagingResponse     `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	ActionSets    []*FeedActionSet       `protobuf:"bytes,2,rep,name=action_sets,json=actionSets,proto3" json:"action_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedActionSetsResponse) Reset() {
	*x = ListFeedActionSetsResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedActionSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedActionSetsResponse) ProtoMessage() {}

func (x *ListFeedActionSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedActionSetsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedActionSetsResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{11}
}

func (x *ListFeedActionSetsResponse) GetPaging() *v1.PagingResponse {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListFeedActionSetsResponse) GetActionSets() []*FeedActionSet {
	if x != nil {
		return x.ActionSets
	}
	return nil
}

type ListFeedCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedCategoriesRequest) Reset() {
	*x = ListFeedCategoriesRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedCategoriesRequest) ProtoMessage() {}

func (x *ListFeedCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListFeedCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{12}
}

type ListFeedCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedCategoriesResponse) Reset() {
	*x = ListFeedCategoriesResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedCategoriesResponse) ProtoMessage() {}

func (x *ListFeedCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListFeedCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{13}
}

func (x *ListFeedCategoriesResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListFeedPlatformsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedPlatformsRequest) Reset() {
	*x = ListFeedPlatformsRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedPlatformsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedPlatformsRequest) ProtoMessage() {}

func (x *ListFeedPlatformsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedPlatformsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedPlatformsRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{14}
}

type ListFeedPlatformsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platforms     []string               `protobuf:"bytes,1,rep,name=platforms,proto3" json:"platforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedPlatformsResponse) Reset() {
	*x = ListFeedPlatformsResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedPlatformsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedPlatformsResponse) ProtoMessage() {}

func (x *ListFeedPlatformsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedPlatformsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedPlatformsResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{15}
}

func (x *ListFeedPlatformsResponse) GetPlatforms() []string {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type ListFeedItemsRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Paging                *v1.PagingRequest      `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	FeedIdFilter          []*v1.InternalID       `protobuf:"bytes,2,rep,name=feed_id_filter,json=feedIdFilter,proto3" json:"feed_id_filter,omitempty"`
	AuthorFilter          []string               `protobuf:"bytes,3,rep,name=author_filter,json=authorFilter,proto3" json:"author_filter,omitempty"`
	PublishPlatformFilter []string               `protobuf:"bytes,4,rep,name=publish_platform_filter,json=publishPlatformFilter,proto3" json:"publish_platform_filter,omitempty"`
	CategoryFilter        []string               `protobuf:"bytes,5,rep,name=category_filter,json=categoryFilter,proto3" json:"category_filter,omitempty"`
	PublishTimeRange      *v1.TimeRange          `protobuf:"bytes,6,opt,name=publish_time_range,json=publishTimeRange,proto3" json:"publish_time_range,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListFeedItemsRequest) Reset() {
	*x = ListFeedItemsRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemsRequest) ProtoMessage() {}

func (x *ListFeedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedItemsRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{16}
}

func (x *ListFeedItemsRequest) GetPaging() *v1.PagingRequest {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListFeedItemsRequest) GetFeedIdFilter() []*v1.InternalID {
	if x != nil {
		return x.FeedIdFilter
	}
	return nil
}

func (x *ListFeedItemsRequest) GetAuthorFilter() []string {
	if x != nil {
		return x.AuthorFilter
	}
	return nil
}

func (x *ListFeedItemsRequest) GetPublishPlatformFilter() []string {
	if x != nil {
		return x.PublishPlatformFilter
	}
	return nil
}

func (x *ListFeedItemsRequest) GetCategoryFilter() []string {
	if x != nil {
		return x.CategoryFilter
	}
	return nil
}

func (x *ListFeedItemsRequest) GetPublishTimeRange() *v1.TimeRange {
	if x != nil {
		return x.PublishTimeRange
	}
	return nil
}

type ListFeedItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *v1.PagingResponse     `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	Items         []*FeedItemDigest      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedItemsResponse) Reset() {
	*x = ListFeedItemsResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemsResponse) ProtoMessage() {}

func (x *ListFeedItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedItemsResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{17}
}

func (x *ListFeedItemsResponse) GetPaging() *v1.PagingResponse {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListFeedItemsResponse) GetItems() []*FeedItemDigest {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetFeedItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.InternalID         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedItemRequest) Reset() {
	*x = GetFeedItemRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedItemRequest) ProtoMessage() {}

func (x *GetFeedItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedItemRequest.ProtoReflect.Descriptor instead.
func (*GetFeedItemRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{18}
}

func (x *GetFeedItemRequest) GetId() *v1.InternalID {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetFeedItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *v1.FeedItem           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedItemResponse) Reset() {
	*x = GetFeedItemResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedItemResponse) ProtoMessage() {}

func (x *GetFeedItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedItemResponse.ProtoReflect.Descriptor instead.
func (*GetFeedItemResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{19}
}

func (x *GetFeedItemResponse) GetItem() *v1.FeedItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetBatchFeedItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*v1.InternalID       `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchFeedItemsRequest) Reset() {
	*x = GetBatchFeedItemsRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchFeedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchFeedItemsRequest) ProtoMessage() {}

func (x *GetBatchFeedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchFeedItemsRequest.ProtoReflect.Descriptor instead.
func (*GetBatchFeedItemsRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{20}
}

func (x *GetBatchFeedItemsRequest) GetIds() []*v1.InternalID {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetBatchFeedItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*v1.FeedItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchFeedItemsResponse) Reset() {
	*x = GetBatchFeedItemsResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchFeedItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchFeedItemsResponse) ProtoMessage() {}

func (x *GetBatchFeedItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchFeedItemsResponse.ProtoReflect.Descriptor instead.
func (*GetBatchFeedItemsResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{21}
}

func (x *GetBatchFeedItemsResponse) GetItems() []*v1.FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReadFeedItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.InternalID         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFeedItemRequest) Reset() {
	*x = ReadFeedItemRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFeedItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFeedItemRequest) ProtoMessage() {}

func (x *ReadFeedItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFeedItemRequest.ProtoReflect.Descriptor instead.
func (*ReadFeedItemRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{22}
}

func (x *ReadFeedItemRequest) GetId() *v1.InternalID {
	if x != nil {
		return x.Id
	}
	return nil
}

type ReadFeedItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFeedItemResponse) Reset() {
	*x = ReadFeedItemResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFeedItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFeedItemResponse) ProtoMessage() {}

func (x *ReadFeedItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFeedItemResponse.ProtoReflect.Descriptor instead.
func (*ReadFeedItemResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{23}
}

type CreateFeedItemCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *FeedItemCollection    `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedItemCollectionRequest) Reset() {
	*x = CreateFeedItemCollectionRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedItemCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedItemCollectionRequest) ProtoMessage() {}

func (x *CreateFeedItemCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedItemCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateFeedItemCollectionRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{24}
}

func (x *CreateFeedItemCollectionRequest) GetCollection() *FeedItemCollection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type CreateFeedItemCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedItemCollectionResponse) Reset() {
	*x = CreateFeedItemCollectionResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedItemCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedItemCollectionResponse) ProtoMessage() {}

func (x *CreateFeedItemCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedItemCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateFeedItemCollectionResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{25}
}

type UpdateFeedItemCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *FeedItemCollection    `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFeedItemCollectionRequest) Reset() {
	*x = UpdateFeedItemCollectionRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeedItemCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedItemCollectionRequest) ProtoMessage() {}

func (x *UpdateFeedItemCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedItemCollectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateFeedItemCollectionRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateFeedItemCollectionRequest) GetCollection() *FeedItemCollection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type UpdateFeedItemCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFeedItemCollectionResponse) Reset() {
	*x = UpdateFeedItemCollectionResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeedItemCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeedItemCollectionResponse) ProtoMessage() {}

func (x *UpdateFeedItemCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeedItemCollectionResponse.ProtoReflect.Descriptor instead.
func (*UpdateFeedItemCollectionResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{27}
}

type ListFeedItemCollectionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Paging         *v1.PagingRequest      `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	IdFilter       []*v1.InternalID       `protobuf:"bytes,2,rep,name=id_filter,json=idFilter,proto3" json:"id_filter,omitempty"`
	CategoryFilter []string               `protobuf:"bytes,3,rep,name=category_filter,json=categoryFilter,proto3" json:"category_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListFeedItemCollectionsRequest) Reset() {
	*x = ListFeedItemCollectionsRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedItemCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemCollectionsRequest) ProtoMessage() {}

func (x *ListFeedItemCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedItemCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{28}
}

func (x *ListFeedItemCollectionsRequest) GetPaging() *v1.PagingRequest {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListFeedItemCollectionsRequest) GetIdFilter() []*v1.InternalID {
	if x != nil {
		return x.IdFilter
	}
	return nil
}

func (x *ListFeedItemCollectionsRequest) GetCategoryFilter() []string {
	if x != nil {
		return x.CategoryFilter
	}
	return nil
}

type ListFeedItemCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *v1.PagingResponse     `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	Collections   []*FeedItemCollection  `protobuf:"bytes,2,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedItemCollectionsResponse) Reset() {
	*x = ListFeedItemCollectionsResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedItemCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemCollectionsResponse) ProtoMessage() {}

func (x *ListFeedItemCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedItemCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{29}
}

func (x *ListFeedItemCollectionsResponse) GetPaging() *v1.PagingResponse {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListFeedItemCollectionsResponse) GetCollections() []*FeedItemCollection {
	if x != nil {
		return x.Collections
	}
	return nil
}

type AddFeedItemToCollectionRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	FeedItemId *v1.InternalID         `protobuf:"bytes,1,opt,name=feed_item_id,json=feedItemId,proto3" json:"feed_item_id,omitempty"`
	// id 0 is regarded as the default collection id
	CollectionId  *v1.InternalID `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFeedItemToCollectionRequest) Reset() {
	*x = AddFeedItemToCollectionRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFeedItemToCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeedItemToCollectionRequest) ProtoMessage() {}

func (x *AddFeedItemToCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeedItemToCollectionRequest.ProtoReflect.Descriptor instead.
func (*AddFeedItemToCollectionRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{30}
}

func (x *AddFeedItemToCollectionRequest) GetFeedItemId() *v1.InternalID {
	if x != nil {
		return x.FeedItemId
	}
	return nil
}

func (x *AddFeedItemToCollectionRequest) GetCollectionId() *v1.InternalID {
	if x != nil {
		return x.CollectionId
	}
	return nil
}

type AddFeedItemToCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFeedItemToCollectionResponse) Reset() {
	*x = AddFeedItemToCollectionResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFeedItemToCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeedItemToCollectionResponse) ProtoMessage() {}

func (x *AddFeedItemToCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeedItemToCollectionResponse.ProtoReflect.Descriptor instead.
func (*AddFeedItemToCollectionResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{31}
}

type RemoveFeedItemFromCollectionRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	FeedItemId *v1.InternalID         `protobuf:"bytes,1,opt,name=feed_item_id,json=feedItemId,proto3" json:"feed_item_id,omitempty"`
	// id 0 is regarded as the default collection id
	CollectionId  *v1.InternalID `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFeedItemFromCollectionRequest) Reset() {
	*x = RemoveFeedItemFromCollectionRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFeedItemFromCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFeedItemFromCollectionRequest) ProtoMessage() {}

func (x *RemoveFeedItemFromCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFeedItemFromCollectionRequest.ProtoReflect.Descriptor instead.
func (*RemoveFeedItemFromCollectionRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{32}
}

func (x *RemoveFeedItemFromCollectionRequest) GetFeedItemId() *v1.InternalID {
	if x != nil {
		return x.FeedItemId
	}
	return nil
}

func (x *RemoveFeedItemFromCollectionRequest) GetCollectionId() *v1.InternalID {
	if x != nil {
		return x.CollectionId
	}
	return nil
}

type RemoveFeedItemFromCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFeedItemFromCollectionResponse) Reset() {
	*x = RemoveFeedItemFromCollectionResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFeedItemFromCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFeedItemFromCollectionResponse) ProtoMessage() {}

func (x *RemoveFeedItemFromCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFeedItemFromCollectionResponse.ProtoReflect.Descriptor instead.
func (*RemoveFeedItemFromCollectionResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{33}
}

type ListFeedItemsInCollectionRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Paging *v1.PagingRequest      `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	// id 0 is regarded as the default collection id
	CollectionIdFilter    []*v1.InternalID `protobuf:"bytes,2,rep,name=collection_id_filter,json=collectionIdFilter,proto3" json:"collection_id_filter,omitempty"`
	AuthorFilter          []string         `protobuf:"bytes,3,rep,name=author_filter,json=authorFilter,proto3" json:"author_filter,omitempty"`
	PublishPlatformFilter []string         `protobuf:"bytes,4,rep,name=publish_platform_filter,json=publishPlatformFilter,proto3" json:"publish_platform_filter,omitempty"`
	CategoryFilter        []string         `protobuf:"bytes,5,rep,name=category_filter,json=categoryFilter,proto3" json:"category_filter,omitempty"`
	PublishTimeRange      *v1.TimeRange    `protobuf:"bytes,6,opt,name=publish_time_range,json=publishTimeRange,proto3" json:"publish_time_range,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListFeedItemsInCollectionRequest) Reset() {
	*x = ListFeedItemsInCollectionRequest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedItemsInCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemsInCollectionRequest) ProtoMessage() {}

func (x *ListFeedItemsInCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemsInCollectionRequest.ProtoReflect.Descriptor instead.
func (*ListFeedItemsInCollectionRequest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{34}
}

func (x *ListFeedItemsInCollectionRequest) GetPaging() *v1.PagingRequest {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListFeedItemsInCollectionRequest) GetCollectionIdFilter() []*v1.InternalID {
	if x != nil {
		return x.CollectionIdFilter
	}
	return nil
}

func (x *ListFeedItemsInCollectionRequest) GetAuthorFilter() []string {
	if x != nil {
		return x.AuthorFilter
	}
	return nil
}

func (x *ListFeedItemsInCollectionRequest) GetPublishPlatformFilter() []string {
	if x != nil {
		return x.PublishPlatformFilter
	}
	return nil
}

func (x *ListFeedItemsInCollectionRequest) GetCategoryFilter() []string {
	if x != nil {
		return x.CategoryFilter
	}
	return nil
}

func (x *ListFeedItemsInCollectionRequest) GetPublishTimeRange() *v1.TimeRange {
	if x != nil {
		return x.PublishTimeRange
	}
	return nil
}

type ListFeedItemsInCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *v1.PagingResponse     `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	Items         []*FeedItemDigest      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedItemsInCollectionResponse) Reset() {
	*x = ListFeedItemsInCollectionResponse{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedItemsInCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemsInCollectionResponse) ProtoMessage() {}

func (x *ListFeedItemsInCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemsInCollectionResponse.ProtoReflect.Descriptor instead.
func (*ListFeedItemsInCollectionResponse) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{35}
}

func (x *ListFeedItemsInCollectionResponse) GetPaging() *v1.PagingResponse {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListFeedItemsInCollectionResponse) GetItems() []*FeedItemDigest {
	if x != nil {
		return x.Items
	}
	return nil
}

type FeedConfig struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          *v1.InternalID         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// WellKnownFeedSource
	Source *v1.FeatureRequest `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// `FeedActionSet.id`
	ActionSets   []*v1.InternalID     `protobuf:"bytes,5,rep,name=action_sets,json=actionSets,proto3" json:"action_sets,omitempty"`
	Status       FeedConfigStatus     `protobuf:"varint,6,opt,name=status,proto3,enum=librarian.sephirah.v1.sephirah.FeedConfigStatus" json:"status,omitempty"`
	PullInterval *durationpb.Duration `protobuf:"bytes,7,opt,name=pull_interval,json=pullInterval,proto3" json:"pull_interval,omitempty"`
	Category     string               `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	// If ture, exclude items from ListFeedItemsResponse
	HideItems bool `protobuf:"varint,9,opt,name=hide_items,json=hideItems,proto3" json:"hide_items,omitempty"`
	// response only
	LatestPullTime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=latest_pull_time,json=latestPullTime,proto3,oneof" json:"latest_pull_time,omitempty"`
	// response only
	LatestPullStatus *FeedConfigPullStatus `protobuf:"varint,11,opt,name=latest_pull_status,json=latestPullStatus,proto3,enum=librarian.sephirah.v1.sephirah.FeedConfigPullStatus,oneof" json:"latest_pull_status,omitempty"`
	// response only
	LatestPullMessage *string `protobuf:"bytes,12,opt,name=latest_pull_message,json=latestPullMessage,proto3,oneof" json:"latest_pull_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FeedConfig) Reset() {
	*x = FeedConfig{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedConfig) ProtoMessage() {}

func (x *FeedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedConfig.ProtoReflect.Descriptor instead.
func (*FeedConfig) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{36}
}

func (x *FeedConfig) GetId() *v1.InternalID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FeedConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeedConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FeedConfig) GetSource() *v1.FeatureRequest {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *FeedConfig) GetActionSets() []*v1.InternalID {
	if x != nil {
		return x.ActionSets
	}
	return nil
}

func (x *FeedConfig) GetStatus() FeedConfigStatus {
	if x != nil {
		return x.Status
	}
	return FeedConfigStatus_FEED_CONFIG_STATUS_UNSPECIFIED
}

func (x *FeedConfig) GetPullInterval() *durationpb.Duration {
	if x != nil {
		return x.PullInterval
	}
	return nil
}

func (x *FeedConfig) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FeedConfig) GetHideItems() bool {
	if x != nil {
		return x.HideItems
	}
	return false
}

func (x *FeedConfig) GetLatestPullTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LatestPullTime
	}
	return nil
}

func (x *FeedConfig) GetLatestPullStatus() FeedConfigPullStatus {
	if x != nil && x.LatestPullStatus != nil {
		return *x.LatestPullStatus
	}
	return FeedConfigPullStatus_FEED_CONFIG_PULL_STATUS_UNSPECIFIED
}

func (x *FeedConfig) GetLatestPullMessage() string {
	if x != nil && x.LatestPullMessage != nil {
		return *x.LatestPullMessage
	}
	return ""
}

type FeedActionSet struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          *v1.InternalID         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// WellKnownFeedItemAction
	Actions       []*v1.FeatureRequest `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedActionSet) Reset() {
	*x = FeedActionSet{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedActionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedActionSet) ProtoMessage() {}

func (x *FeedActionSet) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedActionSet.ProtoReflect.Descriptor instead.
func (*FeedActionSet) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{37}
}

func (x *FeedActionSet) GetId() *v1.InternalID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FeedActionSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeedActionSet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FeedActionSet) GetActions() []*v1.FeatureRequest {
	if x != nil {
		return x.Actions
	}
	return nil
}

// Digest information generated from origin item data
type FeedItemDigest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	FeedId *v1.InternalID         `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	ItemId *v1.InternalID         `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	// `FeedItem.image.url`
	AvatarUrl string `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	// `FeedItem.authors.name`, seperated by `, `
	Authors string `protobuf:"bytes,4,opt,name=authors,proto3" json:"authors,omitempty"`
	// `FeedItem.published_parsed`
	PublishedParsedTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=published_parsed_time,json=publishedParsedTime,proto3" json:"published_parsed_time,omitempty"`
	// `FeedItem.title`
	Title string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	// text generated from `FeedItem.content` or `FeedItem.description`
	ShortDescription string `protobuf:"bytes,7,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	// images generated from `FeedItem.content` or `FeedItem.description`
	// maximum 9
	ImageUrls []string `protobuf:"bytes,8,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	// hostname of `FeedItem.link`, e.g. github.com
	PublishPlatform string `protobuf:"bytes,9,opt,name=publish_platform,json=publishPlatform,proto3" json:"publish_platform,omitempty"`
	// `FeedConfig.name`
	FeedConfigName string `protobuf:"bytes,10,opt,name=feed_config_name,json=feedConfigName,proto3" json:"feed_config_name,omitempty"`
	// `Feed.image.url`
	FeedAvatarUrl string `protobuf:"bytes,11,opt,name=feed_avatar_url,json=feedAvatarUrl,proto3" json:"feed_avatar_url,omitempty"`
	// `FeedItem.read_count`
	ReadCount     int64 `protobuf:"varint,12,opt,name=read_count,json=readCount,proto3" json:"read_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItemDigest) Reset() {
	*x = FeedItemDigest{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItemDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItemDigest) ProtoMessage() {}

func (x *FeedItemDigest) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItemDigest.ProtoReflect.Descriptor instead.
func (*FeedItemDigest) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{38}
}

func (x *FeedItemDigest) GetFeedId() *v1.InternalID {
	if x != nil {
		return x.FeedId
	}
	return nil
}

func (x *FeedItemDigest) GetItemId() *v1.InternalID {
	if x != nil {
		return x.ItemId
	}
	return nil
}

func (x *FeedItemDigest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *FeedItemDigest) GetAuthors() string {
	if x != nil {
		return x.Authors
	}
	return ""
}

func (x *FeedItemDigest) GetPublishedParsedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedParsedTime
	}
	return nil
}

func (x *FeedItemDigest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedItemDigest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *FeedItemDigest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *FeedItemDigest) GetPublishPlatform() string {
	if x != nil {
		return x.PublishPlatform
	}
	return ""
}

func (x *FeedItemDigest) GetFeedConfigName() string {
	if x != nil {
		return x.FeedConfigName
	}
	return ""
}

func (x *FeedItemDigest) GetFeedAvatarUrl() string {
	if x != nil {
		return x.FeedAvatarUrl
	}
	return ""
}

func (x *FeedItemDigest) GetReadCount() int64 {
	if x != nil {
		return x.ReadCount
	}
	return 0
}

// Server must maintain a default collection, without requirement of create
// the default collection can have its id, but client can use id 0 to specify the default collection.
// check ListCollectionItems api for the use case.
type FeedItemCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.InternalID         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItemCollection) Reset() {
	*x = FeedItemCollection{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItemCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItemCollection) ProtoMessage() {}

func (x *FeedItemCollection) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItemCollection.ProtoReflect.Descriptor instead.
func (*FeedItemCollection) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{39}
}

func (x *FeedItemCollection) GetId() *v1.InternalID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FeedItemCollection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeedItemCollection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FeedItemCollection) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListFeedConfigsResponse_FeedWithConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feed          *v1.Feed               `protobuf:"bytes,1,opt,name=feed,proto3" json:"feed,omitempty"`
	Config        *FeedConfig            `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedConfigsResponse_FeedWithConfig) Reset() {
	*x = ListFeedConfigsResponse_FeedWithConfig{}
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedConfigsResponse_FeedWithConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedConfigsResponse_FeedWithConfig) ProtoMessage() {}

func (x *ListFeedConfigsResponse_FeedWithConfig) ProtoReflect() protoreflect.Message {
	mi := &file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedConfigsResponse_FeedWithConfig.ProtoReflect.Descriptor instead.
func (*ListFeedConfigsResponse_FeedWithConfig) Descriptor() ([]byte, []int) {
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListFeedConfigsResponse_FeedWithConfig) GetFeed() *v1.Feed {
	if x != nil {
		return x.Feed
	}
	return nil
}

func (x *ListFeedConfigsResponse_FeedWithConfig) GetConfig() *FeedConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_librarian_sephirah_v1_sephirah_yesod_proto protoreflect.FileDescriptor

const file_librarian_sephirah_v1_sephirah_yesod_proto_rawDesc = "" +
	"\n" +
	"*librarian/sephirah/v1/sephirah/yesod.proto\x12\x1elibrarian.sephirah.v1.sephirah\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19librarian/v1/common.proto\x1a\x1clibrarian/v1/wellknown.proto\"]\n" +
	"\x17CreateFeedConfigRequest\x12B\n" +
	"\x06config\x18\x01 \x01(\v2*.librarian.sephirah.v1.sephirah.FeedConfigR\x06config\"D\n" +
	"\x18CreateFeedConfigResponse\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.librarian.v1.InternalIDR\x02id\"]\n" +
	"\x17UpdateFeedConfigRequest\x12B\n" +
	"\x06config\x18\x01 \x01(\v2*.librarian.sephirah.v1.sephirah.FeedConfigR\x06config\"\x1a\n" +
	"\x18UpdateFeedConfigResponse\"\x84\x02\n" +
	"\x16ListFeedConfigsRequest\x123\n" +
	"\x06paging\x18\x01 \x01(\v2\x1b.librarian.v1.PagingRequestR\x06paging\x125\n" +
	"\tid_filter\x18\x02 \x03(\v2\x18.librarian.v1.InternalIDR\bidFilter\x12U\n" +
	"\rstatus_filter\x18\x05 \x03(\x0e20.librarian.sephirah.v1.sephirah.FeedConfigStatusR\fstatusFilter\x12'\n" +
	"\x0fcategory_filter\x18\x06 \x03(\tR\x0ecategoryFilter\"\xc1\x02\n" +
	"\x17ListFeedConfigsResponse\x124\n" +
	"\x06paging\x18\x01 \x01(\v2\x1c.librarian.v1.PagingResponseR\x06paging\x12r\n" +
	"\x11feeds_with_config\x18\x02 \x03(\v2F.librarian.sephirah.v1.sephirah.ListFeedConfigsResponse.FeedWithConfigR\x0ffeedsWithConfig\x1a|\n" +
	"\x0eFeedWithConfig\x12&\n" +
	"\x04feed\x18\x01 \x01(\v2\x12.librarian.v1.FeedR\x04feed\x12B\n" +
	"\x06config\x18\x02 \x01(\v2*.librarian.sephirah.v1.sephirah.FeedConfigR\x06config\"j\n" +
	"\x1aCreateFeedActionSetRequest\x12L\n" +
	"\n" +
	"action_set\x18\x01 \x01(\v2-.librarian.sephirah.v1.sephirah.FeedActionSetR\tactionSet\"G\n" +
	"\x1bCreateFeedActionSetResponse\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.librarian.v1.InternalIDR\x02id\"j\n" +
	"\x1aUpdateFeedActionSetRequest\x12L\n" +
	"\n" +
	"action_set\x18\x01 \x01(\v2-.librarian.sephirah.v1.sephirah.FeedActionSetR\tactionSet\"\x1d\n" +
	"\x1bUpdateFeedActionSetResponse\"P\n" +
	"\x19ListFeedActionSetsRequest\x123\n" +
	"\x06paging\x18\x01 \x01(\v2\x1b.librarian.v1.PagingRequestR\x06paging\"\xa2\x01\n" +
	"\x1aListFeedActionSetsResponse\x124\n" +
	"\x06paging\x18\x01 \x01(\v2\x1c.librarian.v1.PagingResponseR\x06paging\x12N\n" +
	"\vaction_sets\x18\x02 \x03(\v2-.librarian.sephirah.v1.sephirah.FeedActionSetR\n" +
	"actionSets\"\x1b\n" +
	"\x19ListFeedCategoriesRequest\"<\n" +
	"\x1aListFeedCategoriesResponse\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\"\x1a\n" +
	"\x18ListFeedPlatformsRequest\"9\n" +
	"\x19ListFeedPlatformsResponse\x12\x1c\n" +
	"\tplatforms\x18\x01 \x03(\tR\tplatforms\"\xd8\x02\n" +
	"\x14ListFeedItemsRequest\x123\n" +
	"\x06paging\x18\x01 \x01(\v2\x1b.librarian.v1.PagingRequestR\x06paging\x12>\n" +
	"\x0efeed_id_filter\x18\x02 \x03(\v2\x18.librarian.v1.InternalIDR\ffeedIdFilter\x12#\n" +
	"\rauthor_filter\x18\x03 \x03(\tR\fauthorFilter\x126\n" +
	"\x17publish_platform_filter\x18\x04 \x03(\tR\x15publishPlatformFilter\x12'\n" +
	"\x0fcategory_filter\x18\x05 \x03(\tR\x0ecategoryFilter\x12E\n" +
	"\x12publish_time_range\x18\x06 \x01(\v2\x17.librarian.v1.TimeRangeR\x10publishTimeRange\"\x93\x01\n" +
	"\x15ListFeedItemsResponse\x124\n" +
	"\x06paging\x18\x01 \x01(\v2\x1c.librarian.v1.PagingResponseR\x06paging\x12D\n" +
	"\x05items\x18\x02 \x03(\v2..librarian.sephirah.v1.sephirah.FeedItemDigestR\x05items\">\n" +
	"\x12GetFeedItemRequest\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.librarian.v1.InternalIDR\x02id\"A\n" +
	"\x13GetFeedItemResponse\x12*\n" +
	"\x04item\x18\x01 \x01(\v2\x16.librarian.v1.FeedItemR\x04item\"F\n" +
	"\x18GetBatchFeedItemsRequest\x12*\n" +
	"\x03ids\x18\x01 \x03(\v2\x18.librarian.v1.InternalIDR\x03ids\"I\n" +
	"\x19GetBatchFeedItemsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.librarian.v1.FeedItemR\x05items\"?\n" +
	"\x13ReadFeedItemRequest\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.librarian.v1.InternalIDR\x02id\"\x16\n" +
	"\x14ReadFeedItemResponse\"u\n" +
	"\x1fCreateFeedItemCollectionRequest\x12R\n" +
	"\n" +
	"collection\x18\x01 \x01(\v22.librarian.sephirah.v1.sephirah.FeedItemCollectionR\n" +
	"collection\"\"\n" +
	" CreateFeedItemCollectionResponse\"u\n" +
	"\x1fUpdateFeedItemCollectionRequest\x12R\n" +
	"\n" +
	"collection\x18\x01 \x01(\v22.librarian.sephirah.v1.sephirah.FeedItemCollectionR\n" +
	"collection\"\"\n" +
	" UpdateFeedItemCollectionResponse\"\xb5\x01\n" +
	"\x1eListFeedItemCollectionsRequest\x123\n" +
	"\x06paging\x18\x01 \x01(\v2\x1b.librarian.v1.PagingRequestR\x06paging\x125\n" +
	"\tid_filter\x18\x02 \x03(\v2\x18.librarian.v1.InternalIDR\bidFilter\x12'\n" +
	"\x0fcategory_filter\x18\x03 \x03(\tR\x0ecategoryFilter\"\xad\x01\n" +
	"\x1fListFeedItemCollectionsResponse\x124\n" +
	"\x06paging\x18\x01 \x01(\v2\x1c.librarian.v1.PagingResponseR\x06paging\x12T\n" +
	"\vcollections\x18\x02 \x03(\v22.librarian.sephirah.v1.sephirah.FeedItemCollectionR\vcollections\"\x9b\x01\n" +
	"\x1eAddFeedItemToCollectionRequest\x12:\n" +
	"\ffeed_item_id\x18\x01 \x01(\v2\x18.librarian.v1.InternalIDR\n" +
	"feedItemId\x12=\n" +
	"\rcollection_id\x18\x02 \x01(\v2\x18.librarian.v1.InternalIDR\fcollectionId\"!\n" +
	"\x1fAddFeedItemToCollectionResponse\"\xa0\x01\n" +
	"#RemoveFeedItemFromCollectionRequest\x12:\n" +
	"\ffeed_item_id\x18\x01 \x01(\v2\x18.librarian.v1.InternalIDR\n" +
	"feedItemId\x12=\n" +
	"\rcollection_id\x18\x02 \x01(\v2\x18.librarian.v1.InternalIDR\fcollectionId\"&\n" +
	"$RemoveFeedItemFromCollectionResponse\"\xf0\x02\n" +
	" ListFeedItemsInCollectionRequest\x123\n" +
	"\x06paging\x18\x01 \x01(\v2\x1b.librarian.v1.PagingRequestR\x06paging\x12J\n" +
	"\x14collection_id_filter\x18\x02 \x03(\v2\x18.librarian.v1.InternalIDR\x12collectionIdFilter\x12#\n" +
	"\rauthor_filter\x18\x03 \x03(\tR\fauthorFilter\x126\n" +
	"\x17publish_platform_filter\x18\x04 \x03(\tR\x15publishPlatformFilter\x12'\n" +
	"\x0fcategory_filter\x18\x05 \x03(\tR\x0ecategoryFilter\x12E\n" +
	"\x12publish_time_range\x18\x06 \x01(\v2\x17.librarian.v1.TimeRangeR\x10publishTimeRange\"\x9f\x01\n" +
	"!ListFeedItemsInCollectionResponse\x124\n" +
	"\x06paging\x18\x01 \x01(\v2\x1c.librarian.v1.PagingResponseR\x06paging\x12D\n" +
	"\x05items\x18\x02 \x03(\v2..librarian.sephirah.v1.sephirah.FeedItemDigestR\x05items\"\xcf\x05\n" +
	"\n" +
	"FeedConfig\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.librarian.v1.InternalIDR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x124\n" +
	"\x06source\x18\x04 \x01(\v2\x1c.librarian.v1.FeatureRequestR\x06source\x129\n" +
	"\vaction_sets\x18\x05 \x03(\v2\x18.librarian.v1.InternalIDR\n" +
	"actionSets\x12H\n" +
	"\x06status\x18\x06 \x01(\x0e20.librarian.sephirah.v1.sephirah.FeedConfigStatusR\x06status\x12>\n" +
	"\rpull_interval\x18\a \x01(\v2\x19.google.protobuf.DurationR\fpullInterval\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"hide_items\x18\t \x01(\bR\thideItems\x12I\n" +
	"\x10latest_pull_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0elatestPullTime\x88\x01\x01\x12g\n" +
	"\x12latest_pull_status\x18\v \x01(\x0e24.librarian.sephirah.v1.sephirah.FeedConfigPullStatusH\x01R\x10latestPullStatus\x88\x01\x01\x123\n" +
	"\x13latest_pull_message\x18\f \x01(\tH\x02R\x11latestPullMessage\x88\x01\x01B\x13\n" +
	"\x11_latest_pull_timeB\x15\n" +
	"\x13_latest_pull_statusB\x16\n" +
	"\x14_latest_pull_message\"\xa7\x01\n" +
	"\rFeedActionSet\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.librarian.v1.InternalIDR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x126\n" +
	"\aactions\x18\x04 \x03(\v2\x1c.librarian.v1.FeatureRequestR\aactions\"\xfd\x03\n" +
	"\x0eFeedItemDigest\x121\n" +
	"\afeed_id\x18\x01 \x01(\v2\x18.librarian.v1.InternalIDR\x06feedId\x121\n" +
	"\aitem_id\x18\x02 \x01(\v2\x18.librarian.v1.InternalIDR\x06itemId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x18\n" +
	"\aauthors\x18\x04 \x01(\tR\aauthors\x12N\n" +
	"\x15published_parsed_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x13publishedParsedTime\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12+\n" +
	"\x11short_description\x18\a \x01(\tR\x10shortDescription\x12\x1d\n" +
	"\n" +
	"image_urls\x18\b \x03(\tR\timageUrls\x12)\n" +
	"\x10publish_platform\x18\t \x01(\tR\x0fpublishPlatform\x12(\n" +
	"\x10feed_config_name\x18\n" +
	" \x01(\tR\x0efeedConfigName\x12&\n" +
	"\x0ffeed_avatar_url\x18\v \x01(\tR\rfeedAvatarUrl\x12\x1d\n" +
	"\n" +
	"read_count\x18\f \x01(\x03R\treadCount\"\x90\x01\n" +
	"\x12FeedItemCollection\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.librarian.v1.InternalIDR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory*u\n" +
	"\x10FeedConfigStatus\x12\"\n" +
	"\x1eFEED_CONFIG_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19FEED_CONFIG_STATUS_ACTIVE\x10\x01\x12\x1e\n" +
	"\x1aFEED_CONFIG_STATUS_SUSPEND\x10\x02*\xb0\x01\n" +
	"\x14FeedConfigPullStatus\x12'\n" +
	"#FEED_CONFIG_PULL_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"FEED_CONFIG_PULL_STATUS_PROCESSING\x10\x01\x12#\n" +
	"\x1fFEED_CONFIG_PULL_STATUS_SUCCESS\x10\x02\x12\"\n" +
	"\x1eFEED_CONFIG_PULL_STATUS_FAILED\x10\x03BfZ5github.com/tuihub/protos/pkg/librarian/sephirah/v1;v1\xaa\x02,TuiHub.Protos.Librarian.Sephirah.V1.Sephirahb\x06proto3"

var (
	file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescOnce sync.Once
	file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescData []byte
)

func file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescGZIP() []byte {
	file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescOnce.Do(func() {
		file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_librarian_sephirah_v1_sephirah_yesod_proto_rawDesc), len(file_librarian_sephirah_v1_sephirah_yesod_proto_rawDesc)))
	})
	return file_librarian_sephirah_v1_sephirah_yesod_proto_rawDescData
}

var file_librarian_sephirah_v1_sephirah_yesod_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_librarian_sephirah_v1_sephirah_yesod_proto_goTypes = []any{
	(FeedConfigStatus)(0),                          // 0: librarian.sephirah.v1.sephirah.FeedConfigStatus
	(FeedConfigPullStatus)(0),                      // 1: librarian.sephirah.v1.sephirah.FeedConfigPullStatus
	(*CreateFeedConfigRequest)(nil),                // 2: librarian.sephirah.v1.sephirah.CreateFeedConfigRequest
	(*CreateFeedConfigResponse)(nil),               // 3: librarian.sephirah.v1.sephirah.CreateFeedConfigResponse
	(*UpdateFeedConfigRequest)(nil),                // 4: librarian.sephirah.v1.sephirah.UpdateFeedConfigRequest
	(*UpdateFeedConfigResponse)(nil),               // 5: librarian.sephirah.v1.sephirah.UpdateFeedConfigResponse
	(*ListFeedConfigsRequest)(nil),                 // 6: librarian.sephirah.v1.sephirah.ListFeedConfigsRequest
	(*ListFeedConfigsResponse)(nil),                // 7: librarian.sephirah.v1.sephirah.ListFeedConfigsResponse
	(*CreateFeedActionSetRequest)(nil),             // 8: librarian.sephirah.v1.sephirah.CreateFeedActionSetRequest
	(*CreateFeedActionSetResponse)(nil),            // 9: librarian.sephirah.v1.sephirah.CreateFeedActionSetResponse
	(*UpdateFeedActionSetRequest)(nil),             // 10: librarian.sephirah.v1.sephirah.UpdateFeedActionSetRequest
	(*UpdateFeedActionSetResponse)(nil),            // 11: librarian.sephirah.v1.sephirah.UpdateFeedActionSetResponse
	(*ListFeedActionSetsRequest)(nil),              // 12: librarian.sephirah.v1.sephirah.ListFeedActionSetsRequest
	(*ListFeedActionSetsResponse)(nil),             // 13: librarian.sephirah.v1.sephirah.ListFeedActionSetsResponse
	(*ListFeedCategoriesRequest)(nil),              // 14: librarian.sephirah.v1.sephirah.ListFeedCategoriesRequest
	(*ListFeedCategoriesResponse)(nil),             // 15: librarian.sephirah.v1.sephirah.ListFeedCategoriesResponse
	(*ListFeedPlatformsRequest)(nil),               // 16: librarian.sephirah.v1.sephirah.ListFeedPlatformsRequest
	(*ListFeedPlatformsResponse)(nil),              // 17: librarian.sephirah.v1.sephirah.ListFeedPlatformsResponse
	(*ListFeedItemsRequest)(nil),                   // 18: librarian.sephirah.v1.sephirah.ListFeedItemsRequest
	(*ListFeedItemsResponse)(nil),                  // 19: librarian.sephirah.v1.sephirah.ListFeedItemsResponse
	(*GetFeedItemRequest)(nil),                     // 20: librarian.sephirah.v1.sephirah.GetFeedItemRequest
	(*GetFeedItemResponse)(nil),                    // 21: librarian.sephirah.v1.sephirah.GetFeedItemResponse
	(*GetBatchFeedItemsRequest)(nil),               // 22: librarian.sephirah.v1.sephirah.GetBatchFeedItemsRequest
	(*GetBatchFeedItemsResponse)(nil),              // 23: librarian.sephirah.v1.sephirah.GetBatchFeedItemsResponse
	(*ReadFeedItemRequest)(nil),                    // 24: librarian.sephirah.v1.sephirah.ReadFeedItemRequest
	(*ReadFeedItemResponse)(nil),                   // 25: librarian.sephirah.v1.sephirah.ReadFeedItemResponse
	(*CreateFeedItemCollectionRequest)(nil),        // 26: librarian.sephirah.v1.sephirah.CreateFeedItemCollectionRequest
	(*CreateFeedItemCollectionResponse)(nil),       // 27: librarian.sephirah.v1.sephirah.CreateFeedItemCollectionResponse
	(*UpdateFeedItemCollectionRequest)(nil),        // 28: librarian.sephirah.v1.sephirah.UpdateFeedItemCollectionRequest
	(*UpdateFeedItemCollectionResponse)(nil),       // 29: librarian.sephirah.v1.sephirah.UpdateFeedItemCollectionResponse
	(*ListFeedItemCollectionsRequest)(nil),         // 30: librarian.sephirah.v1.sephirah.ListFeedItemCollectionsRequest
	(*ListFeedItemCollectionsResponse)(nil),        // 31: librarian.sephirah.v1.sephirah.ListFeedItemCollectionsResponse
	(*AddFeedItemToCollectionRequest)(nil),         // 32: librarian.sephirah.v1.sephirah.AddFeedItemToCollectionRequest
	(*AddFeedItemToCollectionResponse)(nil),        // 33: librarian.sephirah.v1.sephirah.AddFeedItemToCollectionResponse
	(*RemoveFeedItemFromCollectionRequest)(nil),    // 34: librarian.sephirah.v1.sephirah.RemoveFeedItemFromCollectionRequest
	(*RemoveFeedItemFromCollectionResponse)(nil),   // 35: librarian.sephirah.v1.sephirah.RemoveFeedItemFromCollectionResponse
	(*ListFeedItemsInCollectionRequest)(nil),       // 36: librarian.sephirah.v1.sephirah.ListFeedItemsInCollectionRequest
	(*ListFeedItemsInCollectionResponse)(nil),      // 37: librarian.sephirah.v1.sephirah.ListFeedItemsInCollectionResponse
	(*FeedConfig)(nil),                             // 38: librarian.sephirah.v1.sephirah.FeedConfig
	(*FeedActionSet)(nil),                          // 39: librarian.sephirah.v1.sephirah.FeedActionSet
	(*FeedItemDigest)(nil),                         // 40: librarian.sephirah.v1.sephirah.FeedItemDigest
	(*FeedItemCollection)(nil),                     // 41: librarian.sephirah.v1.sephirah.FeedItemCollection
	(*ListFeedConfigsResponse_FeedWithConfig)(nil), // 42: librarian.sephirah.v1.sephirah.ListFeedConfigsResponse.FeedWithConfig
	(*v1.InternalID)(nil),                          // 43: librarian.v1.InternalID
	(*v1.PagingRequest)(nil),                       // 44: librarian.v1.PagingRequest
	(*v1.PagingResponse)(nil),                      // 45: librarian.v1.PagingResponse
	(*v1.TimeRange)(nil),                           // 46: librarian.v1.TimeRange
	(*v1.FeedItem)(nil),                            // 47: librarian.v1.FeedItem
	(*v1.FeatureRequest)(nil),                      // 48: librarian.v1.FeatureRequest
	(*durationpb.Duration)(nil),                    // 49: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),                  // 50: google.protobuf.Timestamp
	(*v1.Feed)(nil),                                // 51: librarian.v1.Feed
}
var file_librarian_sephirah_v1_sephirah_yesod_proto_depIdxs = []int32{
	38, // 0: librarian.sephirah.v1.sephirah.CreateFeedConfigRequest.config:type_name -> librarian.sephirah.v1.sephirah.FeedConfig
	43, // 1: librarian.sephirah.v1.sephirah.CreateFeedConfigResponse.id:type_name -> librarian.v1.InternalID
	38, // 2: librarian.sephirah.v1.sephirah.UpdateFeedConfigRequest.config:type_name -> librarian.sephirah.v1.sephirah.FeedConfig
	44, // 3: librarian.sephirah.v1.sephirah.ListFeedConfigsRequest.paging:type_name -> librarian.v1.PagingRequest
	43, // 4: librarian.sephirah.v1.sephirah.ListFeedConfigsRequest.id_filter:type_name -> librarian.v1.InternalID
	0,  // 5: librarian.sephirah.v1.sephirah.ListFeedConfigsRequest.status_filter:type_name -> librarian.sephirah.v1.sephirah.FeedConfigStatus
	45, // 6: librarian.sephirah.v1.sephirah.ListFeedConfigsResponse.paging:type_name -> librarian.v1.PagingResponse
	42, // 7: librarian.sephirah.v1.sephirah.ListFeedConfigsResponse.feeds_with_config:type_name -> librarian.sephirah.v1.sephirah.ListFeedConfigsResponse.FeedWithConfig
	39, // 8: librarian.sephirah.v1.sephirah.CreateFeedActionSetRequest.action_set:type_name -> librarian.sephirah.v1.sephirah.FeedActionSet
	43, // 9: librarian.sephirah.v1.sephirah.CreateFeedActionSetResponse.id:type_name -> librarian.v1.InternalID
	39, // 10: librarian.sephirah.v1.sephirah.UpdateFeedActionSetRequest.action_set:type_name -> librarian.sephirah.v1.sephirah.FeedActionSet
	44, // 11: librarian.sephirah.v1.sephirah.ListFeedActionSetsRequest.paging:type_name -> librarian.v1.PagingRequest
	45, // 12: librarian.sephirah.v1.sephirah.ListFeedActionSetsResponse.paging:type_name -> librarian.v1.PagingResponse
	39, // 13: librarian.sephirah.v1.sephirah.ListFeedActionSetsResponse.action_sets:type_name -> librarian.sephirah.v1.sephirah.FeedActionSet
	44, // 14: librarian.sephirah.v1.sephirah.ListFeedItemsRequest.paging:type_name -> librarian.v1.PagingRequest
	43, // 15: librarian.sephirah.v1.sephirah.ListFeedItemsRequest.feed_id_filter:type_name -> librarian.v1.InternalID
	46, // 16: librarian.sephirah.v1.sephirah.ListFeedItemsRequest.publish_time_range:type_name -> librarian.v1.TimeRange
	45, // 17: librarian.sephirah.v1.sephirah.ListFeedItemsResponse.paging:type_name -> librarian.v1.PagingResponse
	40, // 18: librarian.sephirah.v1.sephirah.ListFeedItemsResponse.items:type_name -> librarian.sephirah.v1.sephirah.FeedItemDigest
	43, // 19: librarian.sephirah.v1.sephirah.GetFeedItemRequest.id:type_name -> librarian.v1.InternalID
	47, // 20: librarian.sephirah.v1.sephirah.GetFeedItemResponse.item:type_name -> librarian.v1.FeedItem
	43, // 21: librarian.sephirah.v1.sephirah.GetBatchFeedItemsRequest.ids:type_name -> librarian.v1.InternalID
	47, // 22: librarian.sephirah.v1.sephirah.GetBatchFeedItemsResponse.items:type_name -> librarian.v1.FeedItem
	43, // 23: librarian.sephirah.v1.sephirah.ReadFeedItemRequest.id:type_name -> librarian.v1.InternalID
	41, // 24: librarian.sephirah.v1.sephirah.CreateFeedItemCollectionRequest.collection:type_name -> librarian.sephirah.v1.sephirah.FeedItemCollection
	41, // 25: librarian.sephirah.v1.sephirah.UpdateFeedItemCollectionRequest.collection:type_name -> librarian.sephirah.v1.sephirah.FeedItemCollection
	44, // 26: librarian.sephirah.v1.sephirah.ListFeedItemCollectionsRequest.paging:type_name -> librarian.v1.PagingRequest
	43, // 27: librarian.sephirah.v1.sephirah.ListFeedItemCollectionsRequest.id_filter:type_name -> librarian.v1.InternalID
	45, // 28: librarian.sephirah.v1.sephirah.ListFeedItemCollectionsResponse.paging:type_name -> librarian.v1.PagingResponse
	41, // 29: librarian.sephirah.v1.sephirah.ListFeedItemCollectionsResponse.collections:type_name -> librarian.sephirah.v1.sephirah.FeedItemCollection
	43, // 30: librarian.sephirah.v1.sephirah.AddFeedItemToCollectionRequest.feed_item_id:type_name -> librarian.v1.InternalID
	43, // 31: librarian.sephirah.v1.sephirah.AddFeedItemToCollectionRequest.collection_id:type_name -> librarian.v1.InternalID
	43, // 32: librarian.sephirah.v1.sephirah.RemoveFeedItemFromCollectionRequest.feed_item_id:type_name -> librarian.v1.InternalID
	43, // 33: librarian.sephirah.v1.sephirah.RemoveFeedItemFromCollectionRequest.collection_id:type_name -> librarian.v1.InternalID
	44, // 34: librarian.sephirah.v1.sephirah.ListFeedItemsInCollectionRequest.paging:type_name -> librarian.v1.PagingRequest
	43, // 35: librarian.sephirah.v1.sephirah.ListFeedItemsInCollectionRequest.collection_id_filter:type_name -> librarian.v1.InternalID
	46, // 36: librarian.sephirah.v1.sephirah.ListFeedItemsInCollectionRequest.publish_time_range:type_name -> librarian.v1.TimeRange
	45, // 37: librarian.sephirah.v1.sephirah.ListFeedItemsInCollectionResponse.paging:type_name -> librarian.v1.PagingResponse
	40, // 38: librarian.sephirah.v1.sephirah.ListFeedItemsInCollectionResponse.items:type_name -> librarian.sephirah.v1.sephirah.FeedItemDigest
	43, // 39: librarian.sephirah.v1.sephirah.FeedConfig.id:type_name -> librarian.v1.InternalID
	48, // 40: librarian.sephirah.v1.sephirah.FeedConfig.source:type_name -> librarian.v1.FeatureRequest
	43, // 41: librarian.sephirah.v1.sephirah.FeedConfig.action_sets:type_name -> librarian.v1.InternalID
	0,  // 42: librarian.sephirah.v1.sephirah.FeedConfig.status:type_name -> librarian.sephirah.v1.sephirah.FeedConfigStatus
	49, // 43: librarian.sephirah.v1.sephirah.FeedConfig.pull_interval:type_name -> google.protobuf.Duration
	50, // 44: librarian.sephirah.v1.sephirah.FeedConfig.latest_pull_time:type_name -> google.protobuf.Timestamp
	1,  // 45: librarian.sephirah.v1.sephirah.FeedConfig.latest_pull_status:type_name -> librarian.sephirah.v1.sephirah.FeedConfigPullStatus
	43, // 46: librarian.sephirah.v1.sephirah.FeedActionSet.id:type_name -> librarian.v1.InternalID
	48, // 47: librarian.sephirah.v1.sephirah.FeedActionSet.actions:type_name -> librarian.v1.FeatureRequest
	43, // 48: librarian.sephirah.v1.sephirah.FeedItemDigest.feed_id:type_name -> librarian.v1.InternalID
	43, // 49: librarian.sephirah.v1.sephirah.FeedItemDigest.item_id:type_name -> librarian.v1.InternalID
	50, // 50: librarian.sephirah.v1.sephirah.FeedItemDigest.published_parsed_time:type_name -> google.protobuf.Timestamp
	43, // 51: librarian.sephirah.v1.sephirah.FeedItemCollection.id:type_name -> librarian.v1.InternalID
	51, // 52: librarian.sephirah.v1.sephirah.ListFeedConfigsResponse.FeedWithConfig.feed:type_name -> librarian.v1.Feed
	38, // 53: librarian.sephirah.v1.sephirah.ListFeedConfigsResponse.FeedWithConfig.config:type_name -> librarian.sephirah.v1.sephirah.FeedConfig
	54, // [54:54] is the sub-list for method output_type
	54, // [54:54] is the sub-list for method input_type
	54, // [54:54] is the sub-list for extension type_name
	54, // [54:54] is the sub-list for extension extendee
	0,  // [0:54] is the sub-list for field type_name
}

func init() { file_librarian_sephirah_v1_sephirah_yesod_proto_init() }
func file_librarian_sephirah_v1_sephirah_yesod_proto_init() {
	if File_librarian_sephirah_v1_sephirah_yesod_proto != nil {
		return
	}
	file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes[36].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_librarian_sephirah_v1_sephirah_yesod_proto_rawDesc), len(file_librarian_sephirah_v1_sephirah_yesod_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_librarian_sephirah_v1_sephirah_yesod_proto_goTypes,
		DependencyIndexes: file_librarian_sephirah_v1_sephirah_yesod_proto_depIdxs,
		EnumInfos:         file_librarian_sephirah_v1_sephirah_yesod_proto_enumTypes,
		MessageInfos:      file_librarian_sephirah_v1_sephirah_yesod_proto_msgTypes,
	}.Build()
	File_librarian_sephirah_v1_sephirah_yesod_proto = out.File
	file_librarian_sephirah_v1_sephirah_yesod_proto_goTypes = nil
	file_librarian_sephirah_v1_sephirah_yesod_proto_depIdxs = nil
}
