// GENERATED CODE -- DO NOT EDIT!

// package: librarian.sephirah.v1
// file: librarian/sephirah/v1/sephirah.proto

import * as librarian_sephirah_v1_sephirah_pb from "../../../librarian/sephirah/v1/sephirah_pb";
import * as librarian_sephirah_v1_binah_pb from "../../../librarian/sephirah/v1/binah_pb";
import * as librarian_sephirah_v1_chesed_pb from "../../../librarian/sephirah/v1/chesed_pb";
import * as librarian_sephirah_v1_gebura_pb from "../../../librarian/sephirah/v1/gebura_pb";
import * as librarian_sephirah_v1_netzach_pb from "../../../librarian/sephirah/v1/netzach_pb";
import * as librarian_sephirah_v1_tiphereth_pb from "../../../librarian/sephirah/v1/tiphereth_pb";
import * as librarian_sephirah_v1_yesod_pb from "../../../librarian/sephirah/v1/yesod_pb";
import * as grpc from "@grpc/grpc-js";

interface ILibrarianSephirahServiceService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  getServerInformation: grpc.MethodDefinition<librarian_sephirah_v1_sephirah_pb.GetServerInformationRequest, librarian_sephirah_v1_sephirah_pb.GetServerInformationResponse>;
  getToken: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.GetTokenRequest, librarian_sephirah_v1_tiphereth_pb.GetTokenResponse>;
  refreshToken: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.RefreshTokenRequest, librarian_sephirah_v1_tiphereth_pb.RefreshTokenResponse>;
  generateToken: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.GenerateTokenRequest, librarian_sephirah_v1_tiphereth_pb.GenerateTokenResponse>;
  createUser: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.CreateUserRequest, librarian_sephirah_v1_tiphereth_pb.CreateUserResponse>;
  updateUser: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.UpdateUserRequest, librarian_sephirah_v1_tiphereth_pb.UpdateUserResponse>;
  getUser: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.GetUserRequest, librarian_sephirah_v1_tiphereth_pb.GetUserResponse>;
  listUsers: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.ListUsersRequest, librarian_sephirah_v1_tiphereth_pb.ListUsersResponse>;
  linkAccount: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.LinkAccountRequest, librarian_sephirah_v1_tiphereth_pb.LinkAccountResponse>;
  unLinkAccount: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.UnLinkAccountRequest, librarian_sephirah_v1_tiphereth_pb.UnLinkAccountResponse>;
  listLinkAccounts: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsRequest, librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsResponse>;
  uploadFile: grpc.MethodDefinition<librarian_sephirah_v1_binah_pb.UploadFileRequest, librarian_sephirah_v1_binah_pb.UploadFileResponse>;
  downloadFile: grpc.MethodDefinition<librarian_sephirah_v1_binah_pb.DownloadFileRequest, librarian_sephirah_v1_binah_pb.DownloadFileResponse>;
  simpleUploadFile: grpc.MethodDefinition<librarian_sephirah_v1_binah_pb.SimpleUploadFileRequest, librarian_sephirah_v1_binah_pb.SimpleUploadFileResponse>;
  simpleDownloadFile: grpc.MethodDefinition<librarian_sephirah_v1_binah_pb.SimpleDownloadFileRequest, librarian_sephirah_v1_binah_pb.SimpleDownloadFileResponse>;
  presignedDownloadFile: grpc.MethodDefinition<librarian_sephirah_v1_binah_pb.PresignedDownloadFileRequest, librarian_sephirah_v1_binah_pb.PresignedDownloadFileResponse>;
  uploadImage: grpc.MethodDefinition<librarian_sephirah_v1_chesed_pb.UploadImageRequest, librarian_sephirah_v1_chesed_pb.UploadImageResponse>;
  updateImage: grpc.MethodDefinition<librarian_sephirah_v1_chesed_pb.UpdateImageRequest, librarian_sephirah_v1_chesed_pb.UpdateImageResponse>;
  listImages: grpc.MethodDefinition<librarian_sephirah_v1_chesed_pb.ListImagesRequest, librarian_sephirah_v1_chesed_pb.ListImagesResponse>;
  searchImages: grpc.MethodDefinition<librarian_sephirah_v1_chesed_pb.SearchImagesRequest, librarian_sephirah_v1_chesed_pb.SearchImagesResponse>;
  getImage: grpc.MethodDefinition<librarian_sephirah_v1_chesed_pb.GetImageRequest, librarian_sephirah_v1_chesed_pb.GetImageResponse>;
  downloadImage: grpc.MethodDefinition<librarian_sephirah_v1_chesed_pb.DownloadImageRequest, librarian_sephirah_v1_chesed_pb.DownloadImageResponse>;
  createApp: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.CreateAppRequest, librarian_sephirah_v1_gebura_pb.CreateAppResponse>;
  updateApp: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.UpdateAppRequest, librarian_sephirah_v1_gebura_pb.UpdateAppResponse>;
  listApps: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.ListAppsRequest, librarian_sephirah_v1_gebura_pb.ListAppsResponse>;
  refreshApp: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.RefreshAppRequest, librarian_sephirah_v1_gebura_pb.RefreshAppResponse>;
  mergeApps: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.MergeAppsRequest, librarian_sephirah_v1_gebura_pb.MergeAppsResponse>;
  pickApp: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.PickAppRequest, librarian_sephirah_v1_gebura_pb.PickAppResponse>;
  searchApps: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.SearchAppsRequest, librarian_sephirah_v1_gebura_pb.SearchAppsResponse>;
  getBindApps: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.GetBindAppsRequest, librarian_sephirah_v1_gebura_pb.GetBindAppsResponse>;
  purchaseApp: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.PurchaseAppRequest, librarian_sephirah_v1_gebura_pb.PurchaseAppResponse>;
  getPurchasedApps: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.GetPurchasedAppsRequest, librarian_sephirah_v1_gebura_pb.GetPurchasedAppsResponse>;
  createAppPackage: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.CreateAppPackageRequest, librarian_sephirah_v1_gebura_pb.CreateAppPackageResponse>;
  updateAppPackage: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.UpdateAppPackageRequest, librarian_sephirah_v1_gebura_pb.UpdateAppPackageResponse>;
  listAppPackages: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.ListAppPackagesRequest, librarian_sephirah_v1_gebura_pb.ListAppPackagesResponse>;
  assignAppPackage: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.AssignAppPackageRequest, librarian_sephirah_v1_gebura_pb.AssignAppPackageResponse>;
  unAssignAppPackage: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.UnAssignAppPackageRequest, librarian_sephirah_v1_gebura_pb.UnAssignAppPackageResponse>;
  reportAppPackages: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.ReportAppPackagesRequest, librarian_sephirah_v1_gebura_pb.ReportAppPackagesResponse>;
  uploadGameSaveFile: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.UploadGameSaveFileRequest, librarian_sephirah_v1_gebura_pb.UploadGameSaveFileResponse>;
  downloadGameSaveFile: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileRequest, librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileResponse>;
  listGameSaveFile: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.ListGameSaveFileRequest, librarian_sephirah_v1_gebura_pb.ListGameSaveFileResponse>;
  createNotifyTarget: grpc.MethodDefinition<librarian_sephirah_v1_netzach_pb.CreateNotifyTargetRequest, librarian_sephirah_v1_netzach_pb.CreateNotifyTargetResponse>;
  updateNotifyTarget: grpc.MethodDefinition<librarian_sephirah_v1_netzach_pb.UpdateNotifyTargetRequest, librarian_sephirah_v1_netzach_pb.UpdateNotifyTargetResponse>;
  listNotifyTargets: grpc.MethodDefinition<librarian_sephirah_v1_netzach_pb.ListNotifyTargetsRequest, librarian_sephirah_v1_netzach_pb.ListNotifyTargetsResponse>;
  createNotifyFlow: grpc.MethodDefinition<librarian_sephirah_v1_netzach_pb.CreateNotifyFlowRequest, librarian_sephirah_v1_netzach_pb.CreateNotifyFlowResponse>;
  updateNotifyFlow: grpc.MethodDefinition<librarian_sephirah_v1_netzach_pb.UpdateNotifyFlowRequest, librarian_sephirah_v1_netzach_pb.UpdateNotifyFlowResponse>;
  listNotifyFlows: grpc.MethodDefinition<librarian_sephirah_v1_netzach_pb.ListNotifyFlowsRequest, librarian_sephirah_v1_netzach_pb.ListNotifyFlowsResponse>;
  createFeedConfig: grpc.MethodDefinition<librarian_sephirah_v1_yesod_pb.CreateFeedConfigRequest, librarian_sephirah_v1_yesod_pb.CreateFeedConfigResponse>;
  updateFeedConfig: grpc.MethodDefinition<librarian_sephirah_v1_yesod_pb.UpdateFeedConfigRequest, librarian_sephirah_v1_yesod_pb.UpdateFeedConfigResponse>;
  listFeedConfigs: grpc.MethodDefinition<librarian_sephirah_v1_yesod_pb.ListFeedConfigsRequest, librarian_sephirah_v1_yesod_pb.ListFeedConfigsResponse>;
  listFeedItems: grpc.MethodDefinition<librarian_sephirah_v1_yesod_pb.ListFeedItemsRequest, librarian_sephirah_v1_yesod_pb.ListFeedItemsResponse>;
  groupFeedItems: grpc.MethodDefinition<librarian_sephirah_v1_yesod_pb.GroupFeedItemsRequest, librarian_sephirah_v1_yesod_pb.GroupFeedItemsResponse>;
  getFeedItem: grpc.MethodDefinition<librarian_sephirah_v1_yesod_pb.GetFeedItemRequest, librarian_sephirah_v1_yesod_pb.GetFeedItemResponse>;
  getBatchFeedItems: grpc.MethodDefinition<librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsRequest, librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsResponse>;
}

export const LibrarianSephirahServiceService: ILibrarianSephirahServiceService;

export interface ILibrarianSephirahServiceServer extends grpc.UntypedServiceImplementation {
  getServerInformation: grpc.handleUnaryCall<librarian_sephirah_v1_sephirah_pb.GetServerInformationRequest, librarian_sephirah_v1_sephirah_pb.GetServerInformationResponse>;
  getToken: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.GetTokenRequest, librarian_sephirah_v1_tiphereth_pb.GetTokenResponse>;
  refreshToken: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.RefreshTokenRequest, librarian_sephirah_v1_tiphereth_pb.RefreshTokenResponse>;
  generateToken: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.GenerateTokenRequest, librarian_sephirah_v1_tiphereth_pb.GenerateTokenResponse>;
  createUser: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.CreateUserRequest, librarian_sephirah_v1_tiphereth_pb.CreateUserResponse>;
  updateUser: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.UpdateUserRequest, librarian_sephirah_v1_tiphereth_pb.UpdateUserResponse>;
  getUser: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.GetUserRequest, librarian_sephirah_v1_tiphereth_pb.GetUserResponse>;
  listUsers: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.ListUsersRequest, librarian_sephirah_v1_tiphereth_pb.ListUsersResponse>;
  linkAccount: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.LinkAccountRequest, librarian_sephirah_v1_tiphereth_pb.LinkAccountResponse>;
  unLinkAccount: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.UnLinkAccountRequest, librarian_sephirah_v1_tiphereth_pb.UnLinkAccountResponse>;
  listLinkAccounts: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsRequest, librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsResponse>;
  uploadFile: grpc.handleBidiStreamingCall<librarian_sephirah_v1_binah_pb.UploadFileRequest, librarian_sephirah_v1_binah_pb.UploadFileResponse>;
  downloadFile: grpc.handleBidiStreamingCall<librarian_sephirah_v1_binah_pb.DownloadFileRequest, librarian_sephirah_v1_binah_pb.DownloadFileResponse>;
  simpleUploadFile: grpc.handleBidiStreamingCall<librarian_sephirah_v1_binah_pb.SimpleUploadFileRequest, librarian_sephirah_v1_binah_pb.SimpleUploadFileResponse>;
  simpleDownloadFile: grpc.handleServerStreamingCall<librarian_sephirah_v1_binah_pb.SimpleDownloadFileRequest, librarian_sephirah_v1_binah_pb.SimpleDownloadFileResponse>;
  presignedDownloadFile: grpc.handleUnaryCall<librarian_sephirah_v1_binah_pb.PresignedDownloadFileRequest, librarian_sephirah_v1_binah_pb.PresignedDownloadFileResponse>;
  uploadImage: grpc.handleUnaryCall<librarian_sephirah_v1_chesed_pb.UploadImageRequest, librarian_sephirah_v1_chesed_pb.UploadImageResponse>;
  updateImage: grpc.handleUnaryCall<librarian_sephirah_v1_chesed_pb.UpdateImageRequest, librarian_sephirah_v1_chesed_pb.UpdateImageResponse>;
  listImages: grpc.handleUnaryCall<librarian_sephirah_v1_chesed_pb.ListImagesRequest, librarian_sephirah_v1_chesed_pb.ListImagesResponse>;
  searchImages: grpc.handleUnaryCall<librarian_sephirah_v1_chesed_pb.SearchImagesRequest, librarian_sephirah_v1_chesed_pb.SearchImagesResponse>;
  getImage: grpc.handleUnaryCall<librarian_sephirah_v1_chesed_pb.GetImageRequest, librarian_sephirah_v1_chesed_pb.GetImageResponse>;
  downloadImage: grpc.handleUnaryCall<librarian_sephirah_v1_chesed_pb.DownloadImageRequest, librarian_sephirah_v1_chesed_pb.DownloadImageResponse>;
  createApp: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.CreateAppRequest, librarian_sephirah_v1_gebura_pb.CreateAppResponse>;
  updateApp: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.UpdateAppRequest, librarian_sephirah_v1_gebura_pb.UpdateAppResponse>;
  listApps: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.ListAppsRequest, librarian_sephirah_v1_gebura_pb.ListAppsResponse>;
  refreshApp: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.RefreshAppRequest, librarian_sephirah_v1_gebura_pb.RefreshAppResponse>;
  mergeApps: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.MergeAppsRequest, librarian_sephirah_v1_gebura_pb.MergeAppsResponse>;
  pickApp: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.PickAppRequest, librarian_sephirah_v1_gebura_pb.PickAppResponse>;
  searchApps: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.SearchAppsRequest, librarian_sephirah_v1_gebura_pb.SearchAppsResponse>;
  getBindApps: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.GetBindAppsRequest, librarian_sephirah_v1_gebura_pb.GetBindAppsResponse>;
  purchaseApp: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.PurchaseAppRequest, librarian_sephirah_v1_gebura_pb.PurchaseAppResponse>;
  getPurchasedApps: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.GetPurchasedAppsRequest, librarian_sephirah_v1_gebura_pb.GetPurchasedAppsResponse>;
  createAppPackage: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.CreateAppPackageRequest, librarian_sephirah_v1_gebura_pb.CreateAppPackageResponse>;
  updateAppPackage: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.UpdateAppPackageRequest, librarian_sephirah_v1_gebura_pb.UpdateAppPackageResponse>;
  listAppPackages: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.ListAppPackagesRequest, librarian_sephirah_v1_gebura_pb.ListAppPackagesResponse>;
  assignAppPackage: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.AssignAppPackageRequest, librarian_sephirah_v1_gebura_pb.AssignAppPackageResponse>;
  unAssignAppPackage: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.UnAssignAppPackageRequest, librarian_sephirah_v1_gebura_pb.UnAssignAppPackageResponse>;
  reportAppPackages: grpc.handleBidiStreamingCall<librarian_sephirah_v1_gebura_pb.ReportAppPackagesRequest, librarian_sephirah_v1_gebura_pb.ReportAppPackagesResponse>;
  uploadGameSaveFile: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.UploadGameSaveFileRequest, librarian_sephirah_v1_gebura_pb.UploadGameSaveFileResponse>;
  downloadGameSaveFile: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileRequest, librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileResponse>;
  listGameSaveFile: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.ListGameSaveFileRequest, librarian_sephirah_v1_gebura_pb.ListGameSaveFileResponse>;
  createNotifyTarget: grpc.handleUnaryCall<librarian_sephirah_v1_netzach_pb.CreateNotifyTargetRequest, librarian_sephirah_v1_netzach_pb.CreateNotifyTargetResponse>;
  updateNotifyTarget: grpc.handleUnaryCall<librarian_sephirah_v1_netzach_pb.UpdateNotifyTargetRequest, librarian_sephirah_v1_netzach_pb.UpdateNotifyTargetResponse>;
  listNotifyTargets: grpc.handleUnaryCall<librarian_sephirah_v1_netzach_pb.ListNotifyTargetsRequest, librarian_sephirah_v1_netzach_pb.ListNotifyTargetsResponse>;
  createNotifyFlow: grpc.handleUnaryCall<librarian_sephirah_v1_netzach_pb.CreateNotifyFlowRequest, librarian_sephirah_v1_netzach_pb.CreateNotifyFlowResponse>;
  updateNotifyFlow: grpc.handleUnaryCall<librarian_sephirah_v1_netzach_pb.UpdateNotifyFlowRequest, librarian_sephirah_v1_netzach_pb.UpdateNotifyFlowResponse>;
  listNotifyFlows: grpc.handleUnaryCall<librarian_sephirah_v1_netzach_pb.ListNotifyFlowsRequest, librarian_sephirah_v1_netzach_pb.ListNotifyFlowsResponse>;
  createFeedConfig: grpc.handleUnaryCall<librarian_sephirah_v1_yesod_pb.CreateFeedConfigRequest, librarian_sephirah_v1_yesod_pb.CreateFeedConfigResponse>;
  updateFeedConfig: grpc.handleUnaryCall<librarian_sephirah_v1_yesod_pb.UpdateFeedConfigRequest, librarian_sephirah_v1_yesod_pb.UpdateFeedConfigResponse>;
  listFeedConfigs: grpc.handleUnaryCall<librarian_sephirah_v1_yesod_pb.ListFeedConfigsRequest, librarian_sephirah_v1_yesod_pb.ListFeedConfigsResponse>;
  listFeedItems: grpc.handleUnaryCall<librarian_sephirah_v1_yesod_pb.ListFeedItemsRequest, librarian_sephirah_v1_yesod_pb.ListFeedItemsResponse>;
  groupFeedItems: grpc.handleUnaryCall<librarian_sephirah_v1_yesod_pb.GroupFeedItemsRequest, librarian_sephirah_v1_yesod_pb.GroupFeedItemsResponse>;
  getFeedItem: grpc.handleUnaryCall<librarian_sephirah_v1_yesod_pb.GetFeedItemRequest, librarian_sephirah_v1_yesod_pb.GetFeedItemResponse>;
  getBatchFeedItems: grpc.handleUnaryCall<librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsRequest, librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsResponse>;
}

export class LibrarianSephirahServiceClient extends grpc.Client {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  getServerInformation(argument: librarian_sephirah_v1_sephirah_pb.GetServerInformationRequest, callback: grpc.requestCallback<librarian_sephirah_v1_sephirah_pb.GetServerInformationResponse>): grpc.ClientUnaryCall;
  getServerInformation(argument: librarian_sephirah_v1_sephirah_pb.GetServerInformationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_sephirah_pb.GetServerInformationResponse>): grpc.ClientUnaryCall;
  getServerInformation(argument: librarian_sephirah_v1_sephirah_pb.GetServerInformationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_sephirah_pb.GetServerInformationResponse>): grpc.ClientUnaryCall;
  getToken(argument: librarian_sephirah_v1_tiphereth_pb.GetTokenRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GetTokenResponse>): grpc.ClientUnaryCall;
  getToken(argument: librarian_sephirah_v1_tiphereth_pb.GetTokenRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GetTokenResponse>): grpc.ClientUnaryCall;
  getToken(argument: librarian_sephirah_v1_tiphereth_pb.GetTokenRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GetTokenResponse>): grpc.ClientUnaryCall;
  refreshToken(argument: librarian_sephirah_v1_tiphereth_pb.RefreshTokenRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.RefreshTokenResponse>): grpc.ClientUnaryCall;
  refreshToken(argument: librarian_sephirah_v1_tiphereth_pb.RefreshTokenRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.RefreshTokenResponse>): grpc.ClientUnaryCall;
  refreshToken(argument: librarian_sephirah_v1_tiphereth_pb.RefreshTokenRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.RefreshTokenResponse>): grpc.ClientUnaryCall;
  generateToken(argument: librarian_sephirah_v1_tiphereth_pb.GenerateTokenRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GenerateTokenResponse>): grpc.ClientUnaryCall;
  generateToken(argument: librarian_sephirah_v1_tiphereth_pb.GenerateTokenRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GenerateTokenResponse>): grpc.ClientUnaryCall;
  generateToken(argument: librarian_sephirah_v1_tiphereth_pb.GenerateTokenRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GenerateTokenResponse>): grpc.ClientUnaryCall;
  createUser(argument: librarian_sephirah_v1_tiphereth_pb.CreateUserRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.CreateUserResponse>): grpc.ClientUnaryCall;
  createUser(argument: librarian_sephirah_v1_tiphereth_pb.CreateUserRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.CreateUserResponse>): grpc.ClientUnaryCall;
  createUser(argument: librarian_sephirah_v1_tiphereth_pb.CreateUserRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.CreateUserResponse>): grpc.ClientUnaryCall;
  updateUser(argument: librarian_sephirah_v1_tiphereth_pb.UpdateUserRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.UpdateUserResponse>): grpc.ClientUnaryCall;
  updateUser(argument: librarian_sephirah_v1_tiphereth_pb.UpdateUserRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.UpdateUserResponse>): grpc.ClientUnaryCall;
  updateUser(argument: librarian_sephirah_v1_tiphereth_pb.UpdateUserRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.UpdateUserResponse>): grpc.ClientUnaryCall;
  getUser(argument: librarian_sephirah_v1_tiphereth_pb.GetUserRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GetUserResponse>): grpc.ClientUnaryCall;
  getUser(argument: librarian_sephirah_v1_tiphereth_pb.GetUserRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GetUserResponse>): grpc.ClientUnaryCall;
  getUser(argument: librarian_sephirah_v1_tiphereth_pb.GetUserRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GetUserResponse>): grpc.ClientUnaryCall;
  listUsers(argument: librarian_sephirah_v1_tiphereth_pb.ListUsersRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.ListUsersResponse>): grpc.ClientUnaryCall;
  listUsers(argument: librarian_sephirah_v1_tiphereth_pb.ListUsersRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.ListUsersResponse>): grpc.ClientUnaryCall;
  listUsers(argument: librarian_sephirah_v1_tiphereth_pb.ListUsersRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.ListUsersResponse>): grpc.ClientUnaryCall;
  linkAccount(argument: librarian_sephirah_v1_tiphereth_pb.LinkAccountRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.LinkAccountResponse>): grpc.ClientUnaryCall;
  linkAccount(argument: librarian_sephirah_v1_tiphereth_pb.LinkAccountRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.LinkAccountResponse>): grpc.ClientUnaryCall;
  linkAccount(argument: librarian_sephirah_v1_tiphereth_pb.LinkAccountRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.LinkAccountResponse>): grpc.ClientUnaryCall;
  unLinkAccount(argument: librarian_sephirah_v1_tiphereth_pb.UnLinkAccountRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.UnLinkAccountResponse>): grpc.ClientUnaryCall;
  unLinkAccount(argument: librarian_sephirah_v1_tiphereth_pb.UnLinkAccountRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.UnLinkAccountResponse>): grpc.ClientUnaryCall;
  unLinkAccount(argument: librarian_sephirah_v1_tiphereth_pb.UnLinkAccountRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.UnLinkAccountResponse>): grpc.ClientUnaryCall;
  listLinkAccounts(argument: librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsResponse>): grpc.ClientUnaryCall;
  listLinkAccounts(argument: librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsResponse>): grpc.ClientUnaryCall;
  listLinkAccounts(argument: librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsResponse>): grpc.ClientUnaryCall;
  uploadFile(metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.UploadFileRequest, librarian_sephirah_v1_binah_pb.UploadFileResponse>;
  uploadFile(metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.UploadFileRequest, librarian_sephirah_v1_binah_pb.UploadFileResponse>;
  downloadFile(metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.DownloadFileRequest, librarian_sephirah_v1_binah_pb.DownloadFileResponse>;
  downloadFile(metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.DownloadFileRequest, librarian_sephirah_v1_binah_pb.DownloadFileResponse>;
  simpleUploadFile(metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.SimpleUploadFileRequest, librarian_sephirah_v1_binah_pb.SimpleUploadFileResponse>;
  simpleUploadFile(metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.SimpleUploadFileRequest, librarian_sephirah_v1_binah_pb.SimpleUploadFileResponse>;
  simpleDownloadFile(argument: librarian_sephirah_v1_binah_pb.SimpleDownloadFileRequest, metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientReadableStream<librarian_sephirah_v1_binah_pb.SimpleDownloadFileResponse>;
  simpleDownloadFile(argument: librarian_sephirah_v1_binah_pb.SimpleDownloadFileRequest, metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientReadableStream<librarian_sephirah_v1_binah_pb.SimpleDownloadFileResponse>;
  presignedDownloadFile(argument: librarian_sephirah_v1_binah_pb.PresignedDownloadFileRequest, callback: grpc.requestCallback<librarian_sephirah_v1_binah_pb.PresignedDownloadFileResponse>): grpc.ClientUnaryCall;
  presignedDownloadFile(argument: librarian_sephirah_v1_binah_pb.PresignedDownloadFileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_binah_pb.PresignedDownloadFileResponse>): grpc.ClientUnaryCall;
  presignedDownloadFile(argument: librarian_sephirah_v1_binah_pb.PresignedDownloadFileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_binah_pb.PresignedDownloadFileResponse>): grpc.ClientUnaryCall;
  uploadImage(argument: librarian_sephirah_v1_chesed_pb.UploadImageRequest, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.UploadImageResponse>): grpc.ClientUnaryCall;
  uploadImage(argument: librarian_sephirah_v1_chesed_pb.UploadImageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.UploadImageResponse>): grpc.ClientUnaryCall;
  uploadImage(argument: librarian_sephirah_v1_chesed_pb.UploadImageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.UploadImageResponse>): grpc.ClientUnaryCall;
  updateImage(argument: librarian_sephirah_v1_chesed_pb.UpdateImageRequest, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.UpdateImageResponse>): grpc.ClientUnaryCall;
  updateImage(argument: librarian_sephirah_v1_chesed_pb.UpdateImageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.UpdateImageResponse>): grpc.ClientUnaryCall;
  updateImage(argument: librarian_sephirah_v1_chesed_pb.UpdateImageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.UpdateImageResponse>): grpc.ClientUnaryCall;
  listImages(argument: librarian_sephirah_v1_chesed_pb.ListImagesRequest, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.ListImagesResponse>): grpc.ClientUnaryCall;
  listImages(argument: librarian_sephirah_v1_chesed_pb.ListImagesRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.ListImagesResponse>): grpc.ClientUnaryCall;
  listImages(argument: librarian_sephirah_v1_chesed_pb.ListImagesRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.ListImagesResponse>): grpc.ClientUnaryCall;
  searchImages(argument: librarian_sephirah_v1_chesed_pb.SearchImagesRequest, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.SearchImagesResponse>): grpc.ClientUnaryCall;
  searchImages(argument: librarian_sephirah_v1_chesed_pb.SearchImagesRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.SearchImagesResponse>): grpc.ClientUnaryCall;
  searchImages(argument: librarian_sephirah_v1_chesed_pb.SearchImagesRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.SearchImagesResponse>): grpc.ClientUnaryCall;
  getImage(argument: librarian_sephirah_v1_chesed_pb.GetImageRequest, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.GetImageResponse>): grpc.ClientUnaryCall;
  getImage(argument: librarian_sephirah_v1_chesed_pb.GetImageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.GetImageResponse>): grpc.ClientUnaryCall;
  getImage(argument: librarian_sephirah_v1_chesed_pb.GetImageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.GetImageResponse>): grpc.ClientUnaryCall;
  downloadImage(argument: librarian_sephirah_v1_chesed_pb.DownloadImageRequest, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.DownloadImageResponse>): grpc.ClientUnaryCall;
  downloadImage(argument: librarian_sephirah_v1_chesed_pb.DownloadImageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.DownloadImageResponse>): grpc.ClientUnaryCall;
  downloadImage(argument: librarian_sephirah_v1_chesed_pb.DownloadImageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_chesed_pb.DownloadImageResponse>): grpc.ClientUnaryCall;
  createApp(argument: librarian_sephirah_v1_gebura_pb.CreateAppRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.CreateAppResponse>): grpc.ClientUnaryCall;
  createApp(argument: librarian_sephirah_v1_gebura_pb.CreateAppRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.CreateAppResponse>): grpc.ClientUnaryCall;
  createApp(argument: librarian_sephirah_v1_gebura_pb.CreateAppRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.CreateAppResponse>): grpc.ClientUnaryCall;
  updateApp(argument: librarian_sephirah_v1_gebura_pb.UpdateAppRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UpdateAppResponse>): grpc.ClientUnaryCall;
  updateApp(argument: librarian_sephirah_v1_gebura_pb.UpdateAppRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UpdateAppResponse>): grpc.ClientUnaryCall;
  updateApp(argument: librarian_sephirah_v1_gebura_pb.UpdateAppRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UpdateAppResponse>): grpc.ClientUnaryCall;
  listApps(argument: librarian_sephirah_v1_gebura_pb.ListAppsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListAppsResponse>): grpc.ClientUnaryCall;
  listApps(argument: librarian_sephirah_v1_gebura_pb.ListAppsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListAppsResponse>): grpc.ClientUnaryCall;
  listApps(argument: librarian_sephirah_v1_gebura_pb.ListAppsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListAppsResponse>): grpc.ClientUnaryCall;
  refreshApp(argument: librarian_sephirah_v1_gebura_pb.RefreshAppRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.RefreshAppResponse>): grpc.ClientUnaryCall;
  refreshApp(argument: librarian_sephirah_v1_gebura_pb.RefreshAppRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.RefreshAppResponse>): grpc.ClientUnaryCall;
  refreshApp(argument: librarian_sephirah_v1_gebura_pb.RefreshAppRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.RefreshAppResponse>): grpc.ClientUnaryCall;
  mergeApps(argument: librarian_sephirah_v1_gebura_pb.MergeAppsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.MergeAppsResponse>): grpc.ClientUnaryCall;
  mergeApps(argument: librarian_sephirah_v1_gebura_pb.MergeAppsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.MergeAppsResponse>): grpc.ClientUnaryCall;
  mergeApps(argument: librarian_sephirah_v1_gebura_pb.MergeAppsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.MergeAppsResponse>): grpc.ClientUnaryCall;
  pickApp(argument: librarian_sephirah_v1_gebura_pb.PickAppRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.PickAppResponse>): grpc.ClientUnaryCall;
  pickApp(argument: librarian_sephirah_v1_gebura_pb.PickAppRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.PickAppResponse>): grpc.ClientUnaryCall;
  pickApp(argument: librarian_sephirah_v1_gebura_pb.PickAppRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.PickAppResponse>): grpc.ClientUnaryCall;
  searchApps(argument: librarian_sephirah_v1_gebura_pb.SearchAppsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.SearchAppsResponse>): grpc.ClientUnaryCall;
  searchApps(argument: librarian_sephirah_v1_gebura_pb.SearchAppsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.SearchAppsResponse>): grpc.ClientUnaryCall;
  searchApps(argument: librarian_sephirah_v1_gebura_pb.SearchAppsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.SearchAppsResponse>): grpc.ClientUnaryCall;
  getBindApps(argument: librarian_sephirah_v1_gebura_pb.GetBindAppsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.GetBindAppsResponse>): grpc.ClientUnaryCall;
  getBindApps(argument: librarian_sephirah_v1_gebura_pb.GetBindAppsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.GetBindAppsResponse>): grpc.ClientUnaryCall;
  getBindApps(argument: librarian_sephirah_v1_gebura_pb.GetBindAppsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.GetBindAppsResponse>): grpc.ClientUnaryCall;
  purchaseApp(argument: librarian_sephirah_v1_gebura_pb.PurchaseAppRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.PurchaseAppResponse>): grpc.ClientUnaryCall;
  purchaseApp(argument: librarian_sephirah_v1_gebura_pb.PurchaseAppRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.PurchaseAppResponse>): grpc.ClientUnaryCall;
  purchaseApp(argument: librarian_sephirah_v1_gebura_pb.PurchaseAppRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.PurchaseAppResponse>): grpc.ClientUnaryCall;
  getPurchasedApps(argument: librarian_sephirah_v1_gebura_pb.GetPurchasedAppsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.GetPurchasedAppsResponse>): grpc.ClientUnaryCall;
  getPurchasedApps(argument: librarian_sephirah_v1_gebura_pb.GetPurchasedAppsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.GetPurchasedAppsResponse>): grpc.ClientUnaryCall;
  getPurchasedApps(argument: librarian_sephirah_v1_gebura_pb.GetPurchasedAppsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.GetPurchasedAppsResponse>): grpc.ClientUnaryCall;
  createAppPackage(argument: librarian_sephirah_v1_gebura_pb.CreateAppPackageRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.CreateAppPackageResponse>): grpc.ClientUnaryCall;
  createAppPackage(argument: librarian_sephirah_v1_gebura_pb.CreateAppPackageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.CreateAppPackageResponse>): grpc.ClientUnaryCall;
  createAppPackage(argument: librarian_sephirah_v1_gebura_pb.CreateAppPackageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.CreateAppPackageResponse>): grpc.ClientUnaryCall;
  updateAppPackage(argument: librarian_sephirah_v1_gebura_pb.UpdateAppPackageRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UpdateAppPackageResponse>): grpc.ClientUnaryCall;
  updateAppPackage(argument: librarian_sephirah_v1_gebura_pb.UpdateAppPackageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UpdateAppPackageResponse>): grpc.ClientUnaryCall;
  updateAppPackage(argument: librarian_sephirah_v1_gebura_pb.UpdateAppPackageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UpdateAppPackageResponse>): grpc.ClientUnaryCall;
  listAppPackages(argument: librarian_sephirah_v1_gebura_pb.ListAppPackagesRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListAppPackagesResponse>): grpc.ClientUnaryCall;
  listAppPackages(argument: librarian_sephirah_v1_gebura_pb.ListAppPackagesRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListAppPackagesResponse>): grpc.ClientUnaryCall;
  listAppPackages(argument: librarian_sephirah_v1_gebura_pb.ListAppPackagesRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListAppPackagesResponse>): grpc.ClientUnaryCall;
  assignAppPackage(argument: librarian_sephirah_v1_gebura_pb.AssignAppPackageRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.AssignAppPackageResponse>): grpc.ClientUnaryCall;
  assignAppPackage(argument: librarian_sephirah_v1_gebura_pb.AssignAppPackageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.AssignAppPackageResponse>): grpc.ClientUnaryCall;
  assignAppPackage(argument: librarian_sephirah_v1_gebura_pb.AssignAppPackageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.AssignAppPackageResponse>): grpc.ClientUnaryCall;
  unAssignAppPackage(argument: librarian_sephirah_v1_gebura_pb.UnAssignAppPackageRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UnAssignAppPackageResponse>): grpc.ClientUnaryCall;
  unAssignAppPackage(argument: librarian_sephirah_v1_gebura_pb.UnAssignAppPackageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UnAssignAppPackageResponse>): grpc.ClientUnaryCall;
  unAssignAppPackage(argument: librarian_sephirah_v1_gebura_pb.UnAssignAppPackageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UnAssignAppPackageResponse>): grpc.ClientUnaryCall;
  reportAppPackages(metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_gebura_pb.ReportAppPackagesRequest, librarian_sephirah_v1_gebura_pb.ReportAppPackagesResponse>;
  reportAppPackages(metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_gebura_pb.ReportAppPackagesRequest, librarian_sephirah_v1_gebura_pb.ReportAppPackagesResponse>;
  uploadGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.UploadGameSaveFileRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UploadGameSaveFileResponse>): grpc.ClientUnaryCall;
  uploadGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.UploadGameSaveFileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UploadGameSaveFileResponse>): grpc.ClientUnaryCall;
  uploadGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.UploadGameSaveFileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UploadGameSaveFileResponse>): grpc.ClientUnaryCall;
  downloadGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileResponse>): grpc.ClientUnaryCall;
  downloadGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileResponse>): grpc.ClientUnaryCall;
  downloadGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileResponse>): grpc.ClientUnaryCall;
  listGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.ListGameSaveFileRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListGameSaveFileResponse>): grpc.ClientUnaryCall;
  listGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.ListGameSaveFileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListGameSaveFileResponse>): grpc.ClientUnaryCall;
  listGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.ListGameSaveFileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListGameSaveFileResponse>): grpc.ClientUnaryCall;
  createNotifyTarget(argument: librarian_sephirah_v1_netzach_pb.CreateNotifyTargetRequest, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.CreateNotifyTargetResponse>): grpc.ClientUnaryCall;
  createNotifyTarget(argument: librarian_sephirah_v1_netzach_pb.CreateNotifyTargetRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.CreateNotifyTargetResponse>): grpc.ClientUnaryCall;
  createNotifyTarget(argument: librarian_sephirah_v1_netzach_pb.CreateNotifyTargetRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.CreateNotifyTargetResponse>): grpc.ClientUnaryCall;
  updateNotifyTarget(argument: librarian_sephirah_v1_netzach_pb.UpdateNotifyTargetRequest, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.UpdateNotifyTargetResponse>): grpc.ClientUnaryCall;
  updateNotifyTarget(argument: librarian_sephirah_v1_netzach_pb.UpdateNotifyTargetRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.UpdateNotifyTargetResponse>): grpc.ClientUnaryCall;
  updateNotifyTarget(argument: librarian_sephirah_v1_netzach_pb.UpdateNotifyTargetRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.UpdateNotifyTargetResponse>): grpc.ClientUnaryCall;
  listNotifyTargets(argument: librarian_sephirah_v1_netzach_pb.ListNotifyTargetsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.ListNotifyTargetsResponse>): grpc.ClientUnaryCall;
  listNotifyTargets(argument: librarian_sephirah_v1_netzach_pb.ListNotifyTargetsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.ListNotifyTargetsResponse>): grpc.ClientUnaryCall;
  listNotifyTargets(argument: librarian_sephirah_v1_netzach_pb.ListNotifyTargetsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.ListNotifyTargetsResponse>): grpc.ClientUnaryCall;
  createNotifyFlow(argument: librarian_sephirah_v1_netzach_pb.CreateNotifyFlowRequest, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.CreateNotifyFlowResponse>): grpc.ClientUnaryCall;
  createNotifyFlow(argument: librarian_sephirah_v1_netzach_pb.CreateNotifyFlowRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.CreateNotifyFlowResponse>): grpc.ClientUnaryCall;
  createNotifyFlow(argument: librarian_sephirah_v1_netzach_pb.CreateNotifyFlowRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.CreateNotifyFlowResponse>): grpc.ClientUnaryCall;
  updateNotifyFlow(argument: librarian_sephirah_v1_netzach_pb.UpdateNotifyFlowRequest, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.UpdateNotifyFlowResponse>): grpc.ClientUnaryCall;
  updateNotifyFlow(argument: librarian_sephirah_v1_netzach_pb.UpdateNotifyFlowRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.UpdateNotifyFlowResponse>): grpc.ClientUnaryCall;
  updateNotifyFlow(argument: librarian_sephirah_v1_netzach_pb.UpdateNotifyFlowRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.UpdateNotifyFlowResponse>): grpc.ClientUnaryCall;
  listNotifyFlows(argument: librarian_sephirah_v1_netzach_pb.ListNotifyFlowsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.ListNotifyFlowsResponse>): grpc.ClientUnaryCall;
  listNotifyFlows(argument: librarian_sephirah_v1_netzach_pb.ListNotifyFlowsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.ListNotifyFlowsResponse>): grpc.ClientUnaryCall;
  listNotifyFlows(argument: librarian_sephirah_v1_netzach_pb.ListNotifyFlowsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_netzach_pb.ListNotifyFlowsResponse>): grpc.ClientUnaryCall;
  createFeedConfig(argument: librarian_sephirah_v1_yesod_pb.CreateFeedConfigRequest, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.CreateFeedConfigResponse>): grpc.ClientUnaryCall;
  createFeedConfig(argument: librarian_sephirah_v1_yesod_pb.CreateFeedConfigRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.CreateFeedConfigResponse>): grpc.ClientUnaryCall;
  createFeedConfig(argument: librarian_sephirah_v1_yesod_pb.CreateFeedConfigRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.CreateFeedConfigResponse>): grpc.ClientUnaryCall;
  updateFeedConfig(argument: librarian_sephirah_v1_yesod_pb.UpdateFeedConfigRequest, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.UpdateFeedConfigResponse>): grpc.ClientUnaryCall;
  updateFeedConfig(argument: librarian_sephirah_v1_yesod_pb.UpdateFeedConfigRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.UpdateFeedConfigResponse>): grpc.ClientUnaryCall;
  updateFeedConfig(argument: librarian_sephirah_v1_yesod_pb.UpdateFeedConfigRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.UpdateFeedConfigResponse>): grpc.ClientUnaryCall;
  listFeedConfigs(argument: librarian_sephirah_v1_yesod_pb.ListFeedConfigsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.ListFeedConfigsResponse>): grpc.ClientUnaryCall;
  listFeedConfigs(argument: librarian_sephirah_v1_yesod_pb.ListFeedConfigsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.ListFeedConfigsResponse>): grpc.ClientUnaryCall;
  listFeedConfigs(argument: librarian_sephirah_v1_yesod_pb.ListFeedConfigsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.ListFeedConfigsResponse>): grpc.ClientUnaryCall;
  listFeedItems(argument: librarian_sephirah_v1_yesod_pb.ListFeedItemsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.ListFeedItemsResponse>): grpc.ClientUnaryCall;
  listFeedItems(argument: librarian_sephirah_v1_yesod_pb.ListFeedItemsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.ListFeedItemsResponse>): grpc.ClientUnaryCall;
  listFeedItems(argument: librarian_sephirah_v1_yesod_pb.ListFeedItemsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.ListFeedItemsResponse>): grpc.ClientUnaryCall;
  groupFeedItems(argument: librarian_sephirah_v1_yesod_pb.GroupFeedItemsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GroupFeedItemsResponse>): grpc.ClientUnaryCall;
  groupFeedItems(argument: librarian_sephirah_v1_yesod_pb.GroupFeedItemsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GroupFeedItemsResponse>): grpc.ClientUnaryCall;
  groupFeedItems(argument: librarian_sephirah_v1_yesod_pb.GroupFeedItemsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GroupFeedItemsResponse>): grpc.ClientUnaryCall;
  getFeedItem(argument: librarian_sephirah_v1_yesod_pb.GetFeedItemRequest, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GetFeedItemResponse>): grpc.ClientUnaryCall;
  getFeedItem(argument: librarian_sephirah_v1_yesod_pb.GetFeedItemRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GetFeedItemResponse>): grpc.ClientUnaryCall;
  getFeedItem(argument: librarian_sephirah_v1_yesod_pb.GetFeedItemRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GetFeedItemResponse>): grpc.ClientUnaryCall;
  getBatchFeedItems(argument: librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsResponse>): grpc.ClientUnaryCall;
  getBatchFeedItems(argument: librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsResponse>): grpc.ClientUnaryCall;
  getBatchFeedItems(argument: librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsResponse>): grpc.ClientUnaryCall;
}
