// GENERATED CODE -- DO NOT EDIT!

// package: librarian.sephirah.v1
// file: librarian/sephirah/v1/sephirah.proto

import * as librarian_sephirah_v1_sephirah_pb from "../../../librarian/sephirah/v1/sephirah_pb";
import * as librarian_sephirah_v1_binah_pb from "../../../librarian/sephirah/v1/binah_pb";
import * as librarian_sephirah_v1_gebura_pb from "../../../librarian/sephirah/v1/gebura_pb";
import * as librarian_sephirah_v1_tiphereth_pb from "../../../librarian/sephirah/v1/tiphereth_pb";
import * as librarian_sephirah_v1_yesod_pb from "../../../librarian/sephirah/v1/yesod_pb";
import * as grpc from "@grpc/grpc-js";

interface ILibrarianSephirahServiceService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  getToken: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.GetTokenRequest, librarian_sephirah_v1_tiphereth_pb.GetTokenResponse>;
  refreshToken: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.RefreshTokenRequest, librarian_sephirah_v1_tiphereth_pb.RefreshTokenResponse>;
  generateToken: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.GenerateTokenRequest, librarian_sephirah_v1_tiphereth_pb.GenerateTokenResponse>;
  createUser: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.CreateUserRequest, librarian_sephirah_v1_tiphereth_pb.CreateUserResponse>;
  updateUser: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.UpdateUserRequest, librarian_sephirah_v1_tiphereth_pb.UpdateUserResponse>;
  getUser: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.GetUserRequest, librarian_sephirah_v1_tiphereth_pb.GetUserResponse>;
  listUsers: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.ListUsersRequest, librarian_sephirah_v1_tiphereth_pb.ListUsersResponse>;
  linkAccount: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.LinkAccountRequest, librarian_sephirah_v1_tiphereth_pb.LinkAccountResponse>;
  unLinkAccount: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.UnLinkAccountRequest, librarian_sephirah_v1_tiphereth_pb.UnLinkAccountResponse>;
  listLinkAccounts: grpc.MethodDefinition<librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsRequest, librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsResponse>;
  uploadFile: grpc.MethodDefinition<librarian_sephirah_v1_binah_pb.UploadFileRequest, librarian_sephirah_v1_binah_pb.UploadFileResponse>;
  downloadFile: grpc.MethodDefinition<librarian_sephirah_v1_binah_pb.DownloadFileRequest, librarian_sephirah_v1_binah_pb.DownloadFileResponse>;
  simpleUploadFile: grpc.MethodDefinition<librarian_sephirah_v1_binah_pb.SimpleUploadFileRequest, librarian_sephirah_v1_binah_pb.SimpleUploadFileResponse>;
  simpleDownloadFile: grpc.MethodDefinition<librarian_sephirah_v1_binah_pb.SimpleDownloadFileRequest, librarian_sephirah_v1_binah_pb.SimpleDownloadFileResponse>;
  createApp: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.CreateAppRequest, librarian_sephirah_v1_gebura_pb.CreateAppResponse>;
  updateApp: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.UpdateAppRequest, librarian_sephirah_v1_gebura_pb.UpdateAppResponse>;
  listApp: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.ListAppRequest, librarian_sephirah_v1_gebura_pb.ListAppResponse>;
  bindApp: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.BindAppRequest, librarian_sephirah_v1_gebura_pb.BindAppResponse>;
  unBindApp: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.UnBindAppRequest, librarian_sephirah_v1_gebura_pb.UnBindAppResponse>;
  refreshApp: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.RefreshAppRequest, librarian_sephirah_v1_gebura_pb.RefreshAppResponse>;
  listBindApp: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.ListBindAppRequest, librarian_sephirah_v1_gebura_pb.ListBindAppResponse>;
  createAppPackage: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.CreateAppPackageRequest, librarian_sephirah_v1_gebura_pb.CreateAppPackageResponse>;
  updateAppPackage: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.UpdateAppPackageRequest, librarian_sephirah_v1_gebura_pb.UpdateAppPackageResponse>;
  listAppPackage: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.ListAppPackageRequest, librarian_sephirah_v1_gebura_pb.ListAppPackageResponse>;
  assignAppPackage: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.AssignAppPackageRequest, librarian_sephirah_v1_gebura_pb.AssignAppPackageResponse>;
  unAssignAppPackage: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.UnAssignAppPackageRequest, librarian_sephirah_v1_gebura_pb.UnAssignAppPackageResponse>;
  reportAppPackage: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.ReportAppPackageRequest, librarian_sephirah_v1_gebura_pb.ReportAppPackageResponse>;
  uploadGameSaveFile: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.UploadGameSaveFileRequest, librarian_sephirah_v1_gebura_pb.UploadGameSaveFileResponse>;
  downloadGameSaveFile: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileRequest, librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileResponse>;
  listGameSaveFile: grpc.MethodDefinition<librarian_sephirah_v1_gebura_pb.ListGameSaveFileRequest, librarian_sephirah_v1_gebura_pb.ListGameSaveFileResponse>;
  createFeedConfig: grpc.MethodDefinition<librarian_sephirah_v1_yesod_pb.CreateFeedConfigRequest, librarian_sephirah_v1_yesod_pb.CreateFeedConfigResponse>;
  updateFeedConfig: grpc.MethodDefinition<librarian_sephirah_v1_yesod_pb.UpdateFeedConfigRequest, librarian_sephirah_v1_yesod_pb.UpdateFeedConfigResponse>;
  listFeeds: grpc.MethodDefinition<librarian_sephirah_v1_yesod_pb.ListFeedsRequest, librarian_sephirah_v1_yesod_pb.ListFeedsResponse>;
  listFeedItems: grpc.MethodDefinition<librarian_sephirah_v1_yesod_pb.ListFeedItemsRequest, librarian_sephirah_v1_yesod_pb.ListFeedItemsResponse>;
  getFeedItem: grpc.MethodDefinition<librarian_sephirah_v1_yesod_pb.GetFeedItemRequest, librarian_sephirah_v1_yesod_pb.GetFeedItemResponse>;
  getBatchFeedItems: grpc.MethodDefinition<librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsRequest, librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsResponse>;
}

export const LibrarianSephirahServiceService: ILibrarianSephirahServiceService;

export interface ILibrarianSephirahServiceServer extends grpc.UntypedServiceImplementation {
  getToken: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.GetTokenRequest, librarian_sephirah_v1_tiphereth_pb.GetTokenResponse>;
  refreshToken: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.RefreshTokenRequest, librarian_sephirah_v1_tiphereth_pb.RefreshTokenResponse>;
  generateToken: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.GenerateTokenRequest, librarian_sephirah_v1_tiphereth_pb.GenerateTokenResponse>;
  createUser: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.CreateUserRequest, librarian_sephirah_v1_tiphereth_pb.CreateUserResponse>;
  updateUser: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.UpdateUserRequest, librarian_sephirah_v1_tiphereth_pb.UpdateUserResponse>;
  getUser: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.GetUserRequest, librarian_sephirah_v1_tiphereth_pb.GetUserResponse>;
  listUsers: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.ListUsersRequest, librarian_sephirah_v1_tiphereth_pb.ListUsersResponse>;
  linkAccount: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.LinkAccountRequest, librarian_sephirah_v1_tiphereth_pb.LinkAccountResponse>;
  unLinkAccount: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.UnLinkAccountRequest, librarian_sephirah_v1_tiphereth_pb.UnLinkAccountResponse>;
  listLinkAccounts: grpc.handleUnaryCall<librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsRequest, librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsResponse>;
  uploadFile: grpc.handleBidiStreamingCall<librarian_sephirah_v1_binah_pb.UploadFileRequest, librarian_sephirah_v1_binah_pb.UploadFileResponse>;
  downloadFile: grpc.handleBidiStreamingCall<librarian_sephirah_v1_binah_pb.DownloadFileRequest, librarian_sephirah_v1_binah_pb.DownloadFileResponse>;
  simpleUploadFile: grpc.handleBidiStreamingCall<librarian_sephirah_v1_binah_pb.SimpleUploadFileRequest, librarian_sephirah_v1_binah_pb.SimpleUploadFileResponse>;
  simpleDownloadFile: grpc.handleBidiStreamingCall<librarian_sephirah_v1_binah_pb.SimpleDownloadFileRequest, librarian_sephirah_v1_binah_pb.SimpleDownloadFileResponse>;
  createApp: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.CreateAppRequest, librarian_sephirah_v1_gebura_pb.CreateAppResponse>;
  updateApp: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.UpdateAppRequest, librarian_sephirah_v1_gebura_pb.UpdateAppResponse>;
  listApp: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.ListAppRequest, librarian_sephirah_v1_gebura_pb.ListAppResponse>;
  bindApp: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.BindAppRequest, librarian_sephirah_v1_gebura_pb.BindAppResponse>;
  unBindApp: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.UnBindAppRequest, librarian_sephirah_v1_gebura_pb.UnBindAppResponse>;
  refreshApp: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.RefreshAppRequest, librarian_sephirah_v1_gebura_pb.RefreshAppResponse>;
  listBindApp: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.ListBindAppRequest, librarian_sephirah_v1_gebura_pb.ListBindAppResponse>;
  createAppPackage: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.CreateAppPackageRequest, librarian_sephirah_v1_gebura_pb.CreateAppPackageResponse>;
  updateAppPackage: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.UpdateAppPackageRequest, librarian_sephirah_v1_gebura_pb.UpdateAppPackageResponse>;
  listAppPackage: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.ListAppPackageRequest, librarian_sephirah_v1_gebura_pb.ListAppPackageResponse>;
  assignAppPackage: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.AssignAppPackageRequest, librarian_sephirah_v1_gebura_pb.AssignAppPackageResponse>;
  unAssignAppPackage: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.UnAssignAppPackageRequest, librarian_sephirah_v1_gebura_pb.UnAssignAppPackageResponse>;
  reportAppPackage: grpc.handleBidiStreamingCall<librarian_sephirah_v1_gebura_pb.ReportAppPackageRequest, librarian_sephirah_v1_gebura_pb.ReportAppPackageResponse>;
  uploadGameSaveFile: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.UploadGameSaveFileRequest, librarian_sephirah_v1_gebura_pb.UploadGameSaveFileResponse>;
  downloadGameSaveFile: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileRequest, librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileResponse>;
  listGameSaveFile: grpc.handleUnaryCall<librarian_sephirah_v1_gebura_pb.ListGameSaveFileRequest, librarian_sephirah_v1_gebura_pb.ListGameSaveFileResponse>;
  createFeedConfig: grpc.handleUnaryCall<librarian_sephirah_v1_yesod_pb.CreateFeedConfigRequest, librarian_sephirah_v1_yesod_pb.CreateFeedConfigResponse>;
  updateFeedConfig: grpc.handleUnaryCall<librarian_sephirah_v1_yesod_pb.UpdateFeedConfigRequest, librarian_sephirah_v1_yesod_pb.UpdateFeedConfigResponse>;
  listFeeds: grpc.handleUnaryCall<librarian_sephirah_v1_yesod_pb.ListFeedsRequest, librarian_sephirah_v1_yesod_pb.ListFeedsResponse>;
  listFeedItems: grpc.handleUnaryCall<librarian_sephirah_v1_yesod_pb.ListFeedItemsRequest, librarian_sephirah_v1_yesod_pb.ListFeedItemsResponse>;
  getFeedItem: grpc.handleUnaryCall<librarian_sephirah_v1_yesod_pb.GetFeedItemRequest, librarian_sephirah_v1_yesod_pb.GetFeedItemResponse>;
  getBatchFeedItems: grpc.handleUnaryCall<librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsRequest, librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsResponse>;
}

export class LibrarianSephirahServiceClient extends grpc.Client {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  getToken(argument: librarian_sephirah_v1_tiphereth_pb.GetTokenRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GetTokenResponse>): grpc.ClientUnaryCall;
  getToken(argument: librarian_sephirah_v1_tiphereth_pb.GetTokenRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GetTokenResponse>): grpc.ClientUnaryCall;
  getToken(argument: librarian_sephirah_v1_tiphereth_pb.GetTokenRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GetTokenResponse>): grpc.ClientUnaryCall;
  refreshToken(argument: librarian_sephirah_v1_tiphereth_pb.RefreshTokenRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.RefreshTokenResponse>): grpc.ClientUnaryCall;
  refreshToken(argument: librarian_sephirah_v1_tiphereth_pb.RefreshTokenRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.RefreshTokenResponse>): grpc.ClientUnaryCall;
  refreshToken(argument: librarian_sephirah_v1_tiphereth_pb.RefreshTokenRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.RefreshTokenResponse>): grpc.ClientUnaryCall;
  generateToken(argument: librarian_sephirah_v1_tiphereth_pb.GenerateTokenRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GenerateTokenResponse>): grpc.ClientUnaryCall;
  generateToken(argument: librarian_sephirah_v1_tiphereth_pb.GenerateTokenRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GenerateTokenResponse>): grpc.ClientUnaryCall;
  generateToken(argument: librarian_sephirah_v1_tiphereth_pb.GenerateTokenRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GenerateTokenResponse>): grpc.ClientUnaryCall;
  createUser(argument: librarian_sephirah_v1_tiphereth_pb.CreateUserRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.CreateUserResponse>): grpc.ClientUnaryCall;
  createUser(argument: librarian_sephirah_v1_tiphereth_pb.CreateUserRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.CreateUserResponse>): grpc.ClientUnaryCall;
  createUser(argument: librarian_sephirah_v1_tiphereth_pb.CreateUserRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.CreateUserResponse>): grpc.ClientUnaryCall;
  updateUser(argument: librarian_sephirah_v1_tiphereth_pb.UpdateUserRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.UpdateUserResponse>): grpc.ClientUnaryCall;
  updateUser(argument: librarian_sephirah_v1_tiphereth_pb.UpdateUserRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.UpdateUserResponse>): grpc.ClientUnaryCall;
  updateUser(argument: librarian_sephirah_v1_tiphereth_pb.UpdateUserRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.UpdateUserResponse>): grpc.ClientUnaryCall;
  getUser(argument: librarian_sephirah_v1_tiphereth_pb.GetUserRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GetUserResponse>): grpc.ClientUnaryCall;
  getUser(argument: librarian_sephirah_v1_tiphereth_pb.GetUserRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GetUserResponse>): grpc.ClientUnaryCall;
  getUser(argument: librarian_sephirah_v1_tiphereth_pb.GetUserRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.GetUserResponse>): grpc.ClientUnaryCall;
  listUsers(argument: librarian_sephirah_v1_tiphereth_pb.ListUsersRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.ListUsersResponse>): grpc.ClientUnaryCall;
  listUsers(argument: librarian_sephirah_v1_tiphereth_pb.ListUsersRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.ListUsersResponse>): grpc.ClientUnaryCall;
  listUsers(argument: librarian_sephirah_v1_tiphereth_pb.ListUsersRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.ListUsersResponse>): grpc.ClientUnaryCall;
  linkAccount(argument: librarian_sephirah_v1_tiphereth_pb.LinkAccountRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.LinkAccountResponse>): grpc.ClientUnaryCall;
  linkAccount(argument: librarian_sephirah_v1_tiphereth_pb.LinkAccountRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.LinkAccountResponse>): grpc.ClientUnaryCall;
  linkAccount(argument: librarian_sephirah_v1_tiphereth_pb.LinkAccountRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.LinkAccountResponse>): grpc.ClientUnaryCall;
  unLinkAccount(argument: librarian_sephirah_v1_tiphereth_pb.UnLinkAccountRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.UnLinkAccountResponse>): grpc.ClientUnaryCall;
  unLinkAccount(argument: librarian_sephirah_v1_tiphereth_pb.UnLinkAccountRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.UnLinkAccountResponse>): grpc.ClientUnaryCall;
  unLinkAccount(argument: librarian_sephirah_v1_tiphereth_pb.UnLinkAccountRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.UnLinkAccountResponse>): grpc.ClientUnaryCall;
  listLinkAccounts(argument: librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsResponse>): grpc.ClientUnaryCall;
  listLinkAccounts(argument: librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsResponse>): grpc.ClientUnaryCall;
  listLinkAccounts(argument: librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_tiphereth_pb.ListLinkAccountsResponse>): grpc.ClientUnaryCall;
  uploadFile(metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.UploadFileRequest, librarian_sephirah_v1_binah_pb.UploadFileResponse>;
  uploadFile(metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.UploadFileRequest, librarian_sephirah_v1_binah_pb.UploadFileResponse>;
  downloadFile(metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.DownloadFileRequest, librarian_sephirah_v1_binah_pb.DownloadFileResponse>;
  downloadFile(metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.DownloadFileRequest, librarian_sephirah_v1_binah_pb.DownloadFileResponse>;
  simpleUploadFile(metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.SimpleUploadFileRequest, librarian_sephirah_v1_binah_pb.SimpleUploadFileResponse>;
  simpleUploadFile(metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.SimpleUploadFileRequest, librarian_sephirah_v1_binah_pb.SimpleUploadFileResponse>;
  simpleDownloadFile(metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.SimpleDownloadFileRequest, librarian_sephirah_v1_binah_pb.SimpleDownloadFileResponse>;
  simpleDownloadFile(metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_binah_pb.SimpleDownloadFileRequest, librarian_sephirah_v1_binah_pb.SimpleDownloadFileResponse>;
  createApp(argument: librarian_sephirah_v1_gebura_pb.CreateAppRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.CreateAppResponse>): grpc.ClientUnaryCall;
  createApp(argument: librarian_sephirah_v1_gebura_pb.CreateAppRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.CreateAppResponse>): grpc.ClientUnaryCall;
  createApp(argument: librarian_sephirah_v1_gebura_pb.CreateAppRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.CreateAppResponse>): grpc.ClientUnaryCall;
  updateApp(argument: librarian_sephirah_v1_gebura_pb.UpdateAppRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UpdateAppResponse>): grpc.ClientUnaryCall;
  updateApp(argument: librarian_sephirah_v1_gebura_pb.UpdateAppRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UpdateAppResponse>): grpc.ClientUnaryCall;
  updateApp(argument: librarian_sephirah_v1_gebura_pb.UpdateAppRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UpdateAppResponse>): grpc.ClientUnaryCall;
  listApp(argument: librarian_sephirah_v1_gebura_pb.ListAppRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListAppResponse>): grpc.ClientUnaryCall;
  listApp(argument: librarian_sephirah_v1_gebura_pb.ListAppRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListAppResponse>): grpc.ClientUnaryCall;
  listApp(argument: librarian_sephirah_v1_gebura_pb.ListAppRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListAppResponse>): grpc.ClientUnaryCall;
  bindApp(argument: librarian_sephirah_v1_gebura_pb.BindAppRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.BindAppResponse>): grpc.ClientUnaryCall;
  bindApp(argument: librarian_sephirah_v1_gebura_pb.BindAppRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.BindAppResponse>): grpc.ClientUnaryCall;
  bindApp(argument: librarian_sephirah_v1_gebura_pb.BindAppRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.BindAppResponse>): grpc.ClientUnaryCall;
  unBindApp(argument: librarian_sephirah_v1_gebura_pb.UnBindAppRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UnBindAppResponse>): grpc.ClientUnaryCall;
  unBindApp(argument: librarian_sephirah_v1_gebura_pb.UnBindAppRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UnBindAppResponse>): grpc.ClientUnaryCall;
  unBindApp(argument: librarian_sephirah_v1_gebura_pb.UnBindAppRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UnBindAppResponse>): grpc.ClientUnaryCall;
  refreshApp(argument: librarian_sephirah_v1_gebura_pb.RefreshAppRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.RefreshAppResponse>): grpc.ClientUnaryCall;
  refreshApp(argument: librarian_sephirah_v1_gebura_pb.RefreshAppRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.RefreshAppResponse>): grpc.ClientUnaryCall;
  refreshApp(argument: librarian_sephirah_v1_gebura_pb.RefreshAppRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.RefreshAppResponse>): grpc.ClientUnaryCall;
  listBindApp(argument: librarian_sephirah_v1_gebura_pb.ListBindAppRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListBindAppResponse>): grpc.ClientUnaryCall;
  listBindApp(argument: librarian_sephirah_v1_gebura_pb.ListBindAppRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListBindAppResponse>): grpc.ClientUnaryCall;
  listBindApp(argument: librarian_sephirah_v1_gebura_pb.ListBindAppRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListBindAppResponse>): grpc.ClientUnaryCall;
  createAppPackage(argument: librarian_sephirah_v1_gebura_pb.CreateAppPackageRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.CreateAppPackageResponse>): grpc.ClientUnaryCall;
  createAppPackage(argument: librarian_sephirah_v1_gebura_pb.CreateAppPackageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.CreateAppPackageResponse>): grpc.ClientUnaryCall;
  createAppPackage(argument: librarian_sephirah_v1_gebura_pb.CreateAppPackageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.CreateAppPackageResponse>): grpc.ClientUnaryCall;
  updateAppPackage(argument: librarian_sephirah_v1_gebura_pb.UpdateAppPackageRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UpdateAppPackageResponse>): grpc.ClientUnaryCall;
  updateAppPackage(argument: librarian_sephirah_v1_gebura_pb.UpdateAppPackageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UpdateAppPackageResponse>): grpc.ClientUnaryCall;
  updateAppPackage(argument: librarian_sephirah_v1_gebura_pb.UpdateAppPackageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UpdateAppPackageResponse>): grpc.ClientUnaryCall;
  listAppPackage(argument: librarian_sephirah_v1_gebura_pb.ListAppPackageRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListAppPackageResponse>): grpc.ClientUnaryCall;
  listAppPackage(argument: librarian_sephirah_v1_gebura_pb.ListAppPackageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListAppPackageResponse>): grpc.ClientUnaryCall;
  listAppPackage(argument: librarian_sephirah_v1_gebura_pb.ListAppPackageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListAppPackageResponse>): grpc.ClientUnaryCall;
  assignAppPackage(argument: librarian_sephirah_v1_gebura_pb.AssignAppPackageRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.AssignAppPackageResponse>): grpc.ClientUnaryCall;
  assignAppPackage(argument: librarian_sephirah_v1_gebura_pb.AssignAppPackageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.AssignAppPackageResponse>): grpc.ClientUnaryCall;
  assignAppPackage(argument: librarian_sephirah_v1_gebura_pb.AssignAppPackageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.AssignAppPackageResponse>): grpc.ClientUnaryCall;
  unAssignAppPackage(argument: librarian_sephirah_v1_gebura_pb.UnAssignAppPackageRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UnAssignAppPackageResponse>): grpc.ClientUnaryCall;
  unAssignAppPackage(argument: librarian_sephirah_v1_gebura_pb.UnAssignAppPackageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UnAssignAppPackageResponse>): grpc.ClientUnaryCall;
  unAssignAppPackage(argument: librarian_sephirah_v1_gebura_pb.UnAssignAppPackageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UnAssignAppPackageResponse>): grpc.ClientUnaryCall;
  reportAppPackage(metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_gebura_pb.ReportAppPackageRequest, librarian_sephirah_v1_gebura_pb.ReportAppPackageResponse>;
  reportAppPackage(metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientDuplexStream<librarian_sephirah_v1_gebura_pb.ReportAppPackageRequest, librarian_sephirah_v1_gebura_pb.ReportAppPackageResponse>;
  uploadGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.UploadGameSaveFileRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UploadGameSaveFileResponse>): grpc.ClientUnaryCall;
  uploadGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.UploadGameSaveFileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UploadGameSaveFileResponse>): grpc.ClientUnaryCall;
  uploadGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.UploadGameSaveFileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.UploadGameSaveFileResponse>): grpc.ClientUnaryCall;
  downloadGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileResponse>): grpc.ClientUnaryCall;
  downloadGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileResponse>): grpc.ClientUnaryCall;
  downloadGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.DownloadGameSaveFileResponse>): grpc.ClientUnaryCall;
  listGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.ListGameSaveFileRequest, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListGameSaveFileResponse>): grpc.ClientUnaryCall;
  listGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.ListGameSaveFileRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListGameSaveFileResponse>): grpc.ClientUnaryCall;
  listGameSaveFile(argument: librarian_sephirah_v1_gebura_pb.ListGameSaveFileRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_gebura_pb.ListGameSaveFileResponse>): grpc.ClientUnaryCall;
  createFeedConfig(argument: librarian_sephirah_v1_yesod_pb.CreateFeedConfigRequest, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.CreateFeedConfigResponse>): grpc.ClientUnaryCall;
  createFeedConfig(argument: librarian_sephirah_v1_yesod_pb.CreateFeedConfigRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.CreateFeedConfigResponse>): grpc.ClientUnaryCall;
  createFeedConfig(argument: librarian_sephirah_v1_yesod_pb.CreateFeedConfigRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.CreateFeedConfigResponse>): grpc.ClientUnaryCall;
  updateFeedConfig(argument: librarian_sephirah_v1_yesod_pb.UpdateFeedConfigRequest, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.UpdateFeedConfigResponse>): grpc.ClientUnaryCall;
  updateFeedConfig(argument: librarian_sephirah_v1_yesod_pb.UpdateFeedConfigRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.UpdateFeedConfigResponse>): grpc.ClientUnaryCall;
  updateFeedConfig(argument: librarian_sephirah_v1_yesod_pb.UpdateFeedConfigRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.UpdateFeedConfigResponse>): grpc.ClientUnaryCall;
  listFeeds(argument: librarian_sephirah_v1_yesod_pb.ListFeedsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.ListFeedsResponse>): grpc.ClientUnaryCall;
  listFeeds(argument: librarian_sephirah_v1_yesod_pb.ListFeedsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.ListFeedsResponse>): grpc.ClientUnaryCall;
  listFeeds(argument: librarian_sephirah_v1_yesod_pb.ListFeedsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.ListFeedsResponse>): grpc.ClientUnaryCall;
  listFeedItems(argument: librarian_sephirah_v1_yesod_pb.ListFeedItemsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.ListFeedItemsResponse>): grpc.ClientUnaryCall;
  listFeedItems(argument: librarian_sephirah_v1_yesod_pb.ListFeedItemsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.ListFeedItemsResponse>): grpc.ClientUnaryCall;
  listFeedItems(argument: librarian_sephirah_v1_yesod_pb.ListFeedItemsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.ListFeedItemsResponse>): grpc.ClientUnaryCall;
  getFeedItem(argument: librarian_sephirah_v1_yesod_pb.GetFeedItemRequest, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GetFeedItemResponse>): grpc.ClientUnaryCall;
  getFeedItem(argument: librarian_sephirah_v1_yesod_pb.GetFeedItemRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GetFeedItemResponse>): grpc.ClientUnaryCall;
  getFeedItem(argument: librarian_sephirah_v1_yesod_pb.GetFeedItemRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GetFeedItemResponse>): grpc.ClientUnaryCall;
  getBatchFeedItems(argument: librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsRequest, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsResponse>): grpc.ClientUnaryCall;
  getBatchFeedItems(argument: librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsResponse>): grpc.ClientUnaryCall;
  getBatchFeedItems(argument: librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<librarian_sephirah_v1_yesod_pb.GetBatchFeedItemsResponse>): grpc.ClientUnaryCall;
}
