// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: librarian/sephirah/v1/porter/sephirah_porter_service.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	porter "github.com/tuihub/protos/pkg/librarian/sephirah/v1/porter"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LibrarianSephirahPorterServiceName is the fully-qualified name of the
	// LibrarianSephirahPorterService service.
	LibrarianSephirahPorterServiceName = "librarian.sephirah.v1.porter.LibrarianSephirahPorterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LibrarianSephirahPorterServiceRefreshTokenProcedure is the fully-qualified name of the
	// LibrarianSephirahPorterService's RefreshToken RPC.
	LibrarianSephirahPorterServiceRefreshTokenProcedure = "/librarian.sephirah.v1.porter.LibrarianSephirahPorterService/RefreshToken"
	// LibrarianSephirahPorterServiceAcquireUserTokenProcedure is the fully-qualified name of the
	// LibrarianSephirahPorterService's AcquireUserToken RPC.
	LibrarianSephirahPorterServiceAcquireUserTokenProcedure = "/librarian.sephirah.v1.porter.LibrarianSephirahPorterService/AcquireUserToken"
	// LibrarianSephirahPorterServiceGetNotifyTargetItemsProcedure is the fully-qualified name of the
	// LibrarianSephirahPorterService's GetNotifyTargetItems RPC.
	LibrarianSephirahPorterServiceGetNotifyTargetItemsProcedure = "/librarian.sephirah.v1.porter.LibrarianSephirahPorterService/GetNotifyTargetItems"
	// LibrarianSephirahPorterServiceUpsertFeedProcedure is the fully-qualified name of the
	// LibrarianSephirahPorterService's UpsertFeed RPC.
	LibrarianSephirahPorterServiceUpsertFeedProcedure = "/librarian.sephirah.v1.porter.LibrarianSephirahPorterService/UpsertFeed"
	// LibrarianSephirahPorterServiceGetFeedProcedure is the fully-qualified name of the
	// LibrarianSephirahPorterService's GetFeed RPC.
	LibrarianSephirahPorterServiceGetFeedProcedure = "/librarian.sephirah.v1.porter.LibrarianSephirahPorterService/GetFeed"
)

// LibrarianSephirahPorterServiceClient is a client for the
// librarian.sephirah.v1.porter.LibrarianSephirahPorterService service.
type LibrarianSephirahPorterServiceClient interface {
	// `Tiphereth` Use valid refresh_token and get two new token, a refresh_token can only be used once
	RefreshToken(context.Context, *connect.Request[porter.RefreshTokenRequest]) (*connect.Response[porter.RefreshTokenResponse], error)
	// `Tiphereth` `Porter` Obtain access_token of a specific user after user authorization.
	// This token can be used to perform actions on behalf of the user.
	AcquireUserToken(context.Context, *connect.Request[porter.AcquireUserTokenRequest]) (*connect.Response[porter.AcquireUserTokenResponse], error)
	// `Netzach` `Porter`
	GetNotifyTargetItems(context.Context, *connect.Request[porter.GetNotifyTargetItemsRequest]) (*connect.Response[porter.GetNotifyTargetItemsResponse], error)
	// `Yesod` `Porter`
	UpsertFeed(context.Context, *connect.Request[porter.UpsertFeedRequest]) (*connect.Response[porter.UpsertFeedResponse], error)
	// `Yesod` `Porter`
	GetFeed(context.Context, *connect.Request[porter.GetFeedRequest]) (*connect.Response[porter.GetFeedResponse], error)
}

// NewLibrarianSephirahPorterServiceClient constructs a client for the
// librarian.sephirah.v1.porter.LibrarianSephirahPorterService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLibrarianSephirahPorterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LibrarianSephirahPorterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	librarianSephirahPorterServiceMethods := porter.File_librarian_sephirah_v1_porter_sephirah_porter_service_proto.Services().ByName("LibrarianSephirahPorterService").Methods()
	return &librarianSephirahPorterServiceClient{
		refreshToken: connect.NewClient[porter.RefreshTokenRequest, porter.RefreshTokenResponse](
			httpClient,
			baseURL+LibrarianSephirahPorterServiceRefreshTokenProcedure,
			connect.WithSchema(librarianSephirahPorterServiceMethods.ByName("RefreshToken")),
			connect.WithClientOptions(opts...),
		),
		acquireUserToken: connect.NewClient[porter.AcquireUserTokenRequest, porter.AcquireUserTokenResponse](
			httpClient,
			baseURL+LibrarianSephirahPorterServiceAcquireUserTokenProcedure,
			connect.WithSchema(librarianSephirahPorterServiceMethods.ByName("AcquireUserToken")),
			connect.WithClientOptions(opts...),
		),
		getNotifyTargetItems: connect.NewClient[porter.GetNotifyTargetItemsRequest, porter.GetNotifyTargetItemsResponse](
			httpClient,
			baseURL+LibrarianSephirahPorterServiceGetNotifyTargetItemsProcedure,
			connect.WithSchema(librarianSephirahPorterServiceMethods.ByName("GetNotifyTargetItems")),
			connect.WithClientOptions(opts...),
		),
		upsertFeed: connect.NewClient[porter.UpsertFeedRequest, porter.UpsertFeedResponse](
			httpClient,
			baseURL+LibrarianSephirahPorterServiceUpsertFeedProcedure,
			connect.WithSchema(librarianSephirahPorterServiceMethods.ByName("UpsertFeed")),
			connect.WithClientOptions(opts...),
		),
		getFeed: connect.NewClient[porter.GetFeedRequest, porter.GetFeedResponse](
			httpClient,
			baseURL+LibrarianSephirahPorterServiceGetFeedProcedure,
			connect.WithSchema(librarianSephirahPorterServiceMethods.ByName("GetFeed")),
			connect.WithClientOptions(opts...),
		),
	}
}

// librarianSephirahPorterServiceClient implements LibrarianSephirahPorterServiceClient.
type librarianSephirahPorterServiceClient struct {
	refreshToken         *connect.Client[porter.RefreshTokenRequest, porter.RefreshTokenResponse]
	acquireUserToken     *connect.Client[porter.AcquireUserTokenRequest, porter.AcquireUserTokenResponse]
	getNotifyTargetItems *connect.Client[porter.GetNotifyTargetItemsRequest, porter.GetNotifyTargetItemsResponse]
	upsertFeed           *connect.Client[porter.UpsertFeedRequest, porter.UpsertFeedResponse]
	getFeed              *connect.Client[porter.GetFeedRequest, porter.GetFeedResponse]
}

// RefreshToken calls librarian.sephirah.v1.porter.LibrarianSephirahPorterService.RefreshToken.
func (c *librarianSephirahPorterServiceClient) RefreshToken(ctx context.Context, req *connect.Request[porter.RefreshTokenRequest]) (*connect.Response[porter.RefreshTokenResponse], error) {
	return c.refreshToken.CallUnary(ctx, req)
}

// AcquireUserToken calls
// librarian.sephirah.v1.porter.LibrarianSephirahPorterService.AcquireUserToken.
func (c *librarianSephirahPorterServiceClient) AcquireUserToken(ctx context.Context, req *connect.Request[porter.AcquireUserTokenRequest]) (*connect.Response[porter.AcquireUserTokenResponse], error) {
	return c.acquireUserToken.CallUnary(ctx, req)
}

// GetNotifyTargetItems calls
// librarian.sephirah.v1.porter.LibrarianSephirahPorterService.GetNotifyTargetItems.
func (c *librarianSephirahPorterServiceClient) GetNotifyTargetItems(ctx context.Context, req *connect.Request[porter.GetNotifyTargetItemsRequest]) (*connect.Response[porter.GetNotifyTargetItemsResponse], error) {
	return c.getNotifyTargetItems.CallUnary(ctx, req)
}

// UpsertFeed calls librarian.sephirah.v1.porter.LibrarianSephirahPorterService.UpsertFeed.
func (c *librarianSephirahPorterServiceClient) UpsertFeed(ctx context.Context, req *connect.Request[porter.UpsertFeedRequest]) (*connect.Response[porter.UpsertFeedResponse], error) {
	return c.upsertFeed.CallUnary(ctx, req)
}

// GetFeed calls librarian.sephirah.v1.porter.LibrarianSephirahPorterService.GetFeed.
func (c *librarianSephirahPorterServiceClient) GetFeed(ctx context.Context, req *connect.Request[porter.GetFeedRequest]) (*connect.Response[porter.GetFeedResponse], error) {
	return c.getFeed.CallUnary(ctx, req)
}

// LibrarianSephirahPorterServiceHandler is an implementation of the
// librarian.sephirah.v1.porter.LibrarianSephirahPorterService service.
type LibrarianSephirahPorterServiceHandler interface {
	// `Tiphereth` Use valid refresh_token and get two new token, a refresh_token can only be used once
	RefreshToken(context.Context, *connect.Request[porter.RefreshTokenRequest]) (*connect.Response[porter.RefreshTokenResponse], error)
	// `Tiphereth` `Porter` Obtain access_token of a specific user after user authorization.
	// This token can be used to perform actions on behalf of the user.
	AcquireUserToken(context.Context, *connect.Request[porter.AcquireUserTokenRequest]) (*connect.Response[porter.AcquireUserTokenResponse], error)
	// `Netzach` `Porter`
	GetNotifyTargetItems(context.Context, *connect.Request[porter.GetNotifyTargetItemsRequest]) (*connect.Response[porter.GetNotifyTargetItemsResponse], error)
	// `Yesod` `Porter`
	UpsertFeed(context.Context, *connect.Request[porter.UpsertFeedRequest]) (*connect.Response[porter.UpsertFeedResponse], error)
	// `Yesod` `Porter`
	GetFeed(context.Context, *connect.Request[porter.GetFeedRequest]) (*connect.Response[porter.GetFeedResponse], error)
}

// NewLibrarianSephirahPorterServiceHandler builds an HTTP handler from the service implementation.
// It returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLibrarianSephirahPorterServiceHandler(svc LibrarianSephirahPorterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	librarianSephirahPorterServiceMethods := porter.File_librarian_sephirah_v1_porter_sephirah_porter_service_proto.Services().ByName("LibrarianSephirahPorterService").Methods()
	librarianSephirahPorterServiceRefreshTokenHandler := connect.NewUnaryHandler(
		LibrarianSephirahPorterServiceRefreshTokenProcedure,
		svc.RefreshToken,
		connect.WithSchema(librarianSephirahPorterServiceMethods.ByName("RefreshToken")),
		connect.WithHandlerOptions(opts...),
	)
	librarianSephirahPorterServiceAcquireUserTokenHandler := connect.NewUnaryHandler(
		LibrarianSephirahPorterServiceAcquireUserTokenProcedure,
		svc.AcquireUserToken,
		connect.WithSchema(librarianSephirahPorterServiceMethods.ByName("AcquireUserToken")),
		connect.WithHandlerOptions(opts...),
	)
	librarianSephirahPorterServiceGetNotifyTargetItemsHandler := connect.NewUnaryHandler(
		LibrarianSephirahPorterServiceGetNotifyTargetItemsProcedure,
		svc.GetNotifyTargetItems,
		connect.WithSchema(librarianSephirahPorterServiceMethods.ByName("GetNotifyTargetItems")),
		connect.WithHandlerOptions(opts...),
	)
	librarianSephirahPorterServiceUpsertFeedHandler := connect.NewUnaryHandler(
		LibrarianSephirahPorterServiceUpsertFeedProcedure,
		svc.UpsertFeed,
		connect.WithSchema(librarianSephirahPorterServiceMethods.ByName("UpsertFeed")),
		connect.WithHandlerOptions(opts...),
	)
	librarianSephirahPorterServiceGetFeedHandler := connect.NewUnaryHandler(
		LibrarianSephirahPorterServiceGetFeedProcedure,
		svc.GetFeed,
		connect.WithSchema(librarianSephirahPorterServiceMethods.ByName("GetFeed")),
		connect.WithHandlerOptions(opts...),
	)
	return "/librarian.sephirah.v1.porter.LibrarianSephirahPorterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LibrarianSephirahPorterServiceRefreshTokenProcedure:
			librarianSephirahPorterServiceRefreshTokenHandler.ServeHTTP(w, r)
		case LibrarianSephirahPorterServiceAcquireUserTokenProcedure:
			librarianSephirahPorterServiceAcquireUserTokenHandler.ServeHTTP(w, r)
		case LibrarianSephirahPorterServiceGetNotifyTargetItemsProcedure:
			librarianSephirahPorterServiceGetNotifyTargetItemsHandler.ServeHTTP(w, r)
		case LibrarianSephirahPorterServiceUpsertFeedProcedure:
			librarianSephirahPorterServiceUpsertFeedHandler.ServeHTTP(w, r)
		case LibrarianSephirahPorterServiceGetFeedProcedure:
			librarianSephirahPorterServiceGetFeedHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLibrarianSephirahPorterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLibrarianSephirahPorterServiceHandler struct{}

func (UnimplementedLibrarianSephirahPorterServiceHandler) RefreshToken(context.Context, *connect.Request[porter.RefreshTokenRequest]) (*connect.Response[porter.RefreshTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("librarian.sephirah.v1.porter.LibrarianSephirahPorterService.RefreshToken is not implemented"))
}

func (UnimplementedLibrarianSephirahPorterServiceHandler) AcquireUserToken(context.Context, *connect.Request[porter.AcquireUserTokenRequest]) (*connect.Response[porter.AcquireUserTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("librarian.sephirah.v1.porter.LibrarianSephirahPorterService.AcquireUserToken is not implemented"))
}

func (UnimplementedLibrarianSephirahPorterServiceHandler) GetNotifyTargetItems(context.Context, *connect.Request[porter.GetNotifyTargetItemsRequest]) (*connect.Response[porter.GetNotifyTargetItemsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("librarian.sephirah.v1.porter.LibrarianSephirahPorterService.GetNotifyTargetItems is not implemented"))
}

func (UnimplementedLibrarianSephirahPorterServiceHandler) UpsertFeed(context.Context, *connect.Request[porter.UpsertFeedRequest]) (*connect.Response[porter.UpsertFeedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("librarian.sephirah.v1.porter.LibrarianSephirahPorterService.UpsertFeed is not implemented"))
}

func (UnimplementedLibrarianSephirahPorterServiceHandler) GetFeed(context.Context, *connect.Request[porter.GetFeedRequest]) (*connect.Response[porter.GetFeedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("librarian.sephirah.v1.porter.LibrarianSephirahPorterService.GetFeed is not implemented"))
}
