// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: librarian/sephirah/v1/sephirah.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TuiHub.Protos.Librarian.Sephirah.V1 {

  /// <summary>Holder for reflection information generated from librarian/sephirah/v1/sephirah.proto</summary>
  public static partial class SephirahReflection {

    #region Descriptor
    /// <summary>File descriptor for librarian/sephirah/v1/sephirah.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SephirahReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRsaWJyYXJpYW4vc2VwaGlyYWgvdjEvc2VwaGlyYWgucHJvdG8SFWxpYnJh",
            "cmlhbi5zZXBoaXJhaC52MRohbGlicmFyaWFuL3NlcGhpcmFoL3YxL2JpbmFo",
            "LnByb3RvGiJsaWJyYXJpYW4vc2VwaGlyYWgvdjEvZ2VidXJhLnByb3RvGiNs",
            "aWJyYXJpYW4vc2VwaGlyYWgvdjEvbmV0emFjaC5wcm90bxolbGlicmFyaWFu",
            "L3NlcGhpcmFoL3YxL3RpcGhlcmV0aC5wcm90bxohbGlicmFyaWFuL3NlcGhp",
            "cmFoL3YxL3llc29kLnByb3RvMvImChhMaWJyYXJpYW5TZXBoaXJhaFNlcnZp",
            "Y2USWwoIR2V0VG9rZW4SJi5saWJyYXJpYW4uc2VwaGlyYWgudjEuR2V0VG9r",
            "ZW5SZXF1ZXN0GicubGlicmFyaWFuLnNlcGhpcmFoLnYxLkdldFRva2VuUmVz",
            "cG9uc2USZwoMUmVmcmVzaFRva2VuEioubGlicmFyaWFuLnNlcGhpcmFoLnYx",
            "LlJlZnJlc2hUb2tlblJlcXVlc3QaKy5saWJyYXJpYW4uc2VwaGlyYWgudjEu",
            "UmVmcmVzaFRva2VuUmVzcG9uc2USagoNR2VuZXJhdGVUb2tlbhIrLmxpYnJh",
            "cmlhbi5zZXBoaXJhaC52MS5HZW5lcmF0ZVRva2VuUmVxdWVzdBosLmxpYnJh",
            "cmlhbi5zZXBoaXJhaC52MS5HZW5lcmF0ZVRva2VuUmVzcG9uc2USYQoKQ3Jl",
            "YXRlVXNlchIoLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5DcmVhdGVVc2VyUmVx",
            "dWVzdBopLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5DcmVhdGVVc2VyUmVzcG9u",
            "c2USYQoKVXBkYXRlVXNlchIoLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5VcGRh",
            "dGVVc2VyUmVxdWVzdBopLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5VcGRhdGVV",
            "c2VyUmVzcG9uc2USWAoHR2V0VXNlchIlLmxpYnJhcmlhbi5zZXBoaXJhaC52",
            "MS5HZXRVc2VyUmVxdWVzdBomLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5HZXRV",
            "c2VyUmVzcG9uc2USXgoJTGlzdFVzZXJzEicubGlicmFyaWFuLnNlcGhpcmFo",
            "LnYxLkxpc3RVc2Vyc1JlcXVlc3QaKC5saWJyYXJpYW4uc2VwaGlyYWgudjEu",
            "TGlzdFVzZXJzUmVzcG9uc2USZAoLTGlua0FjY291bnQSKS5saWJyYXJpYW4u",
            "c2VwaGlyYWgudjEuTGlua0FjY291bnRSZXF1ZXN0GioubGlicmFyaWFuLnNl",
            "cGhpcmFoLnYxLkxpbmtBY2NvdW50UmVzcG9uc2USagoNVW5MaW5rQWNjb3Vu",
            "dBIrLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5VbkxpbmtBY2NvdW50UmVxdWVz",
            "dBosLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5VbkxpbmtBY2NvdW50UmVzcG9u",
            "c2UScwoQTGlzdExpbmtBY2NvdW50cxIuLmxpYnJhcmlhbi5zZXBoaXJhaC52",
            "MS5MaXN0TGlua0FjY291bnRzUmVxdWVzdBovLmxpYnJhcmlhbi5zZXBoaXJh",
            "aC52MS5MaXN0TGlua0FjY291bnRzUmVzcG9uc2USZQoKVXBsb2FkRmlsZRIo",
            "LmxpYnJhcmlhbi5zZXBoaXJhaC52MS5VcGxvYWRGaWxlUmVxdWVzdBopLmxp",
            "YnJhcmlhbi5zZXBoaXJhaC52MS5VcGxvYWRGaWxlUmVzcG9uc2UoATABEmsK",
            "DERvd25sb2FkRmlsZRIqLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5Eb3dubG9h",
            "ZEZpbGVSZXF1ZXN0GisubGlicmFyaWFuLnNlcGhpcmFoLnYxLkRvd25sb2Fk",
            "RmlsZVJlc3BvbnNlKAEwARJ3ChBTaW1wbGVVcGxvYWRGaWxlEi4ubGlicmFy",
            "aWFuLnNlcGhpcmFoLnYxLlNpbXBsZVVwbG9hZEZpbGVSZXF1ZXN0Gi8ubGli",
            "cmFyaWFuLnNlcGhpcmFoLnYxLlNpbXBsZVVwbG9hZEZpbGVSZXNwb25zZSgB",
            "MAESfQoSU2ltcGxlRG93bmxvYWRGaWxlEjAubGlicmFyaWFuLnNlcGhpcmFo",
            "LnYxLlNpbXBsZURvd25sb2FkRmlsZVJlcXVlc3QaMS5saWJyYXJpYW4uc2Vw",
            "aGlyYWgudjEuU2ltcGxlRG93bmxvYWRGaWxlUmVzcG9uc2UoATABEl4KCUNy",
            "ZWF0ZUFwcBInLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5DcmVhdGVBcHBSZXF1",
            "ZXN0GigubGlicmFyaWFuLnNlcGhpcmFoLnYxLkNyZWF0ZUFwcFJlc3BvbnNl",
            "El4KCVVwZGF0ZUFwcBInLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5VcGRhdGVB",
            "cHBSZXF1ZXN0GigubGlicmFyaWFuLnNlcGhpcmFoLnYxLlVwZGF0ZUFwcFJl",
            "c3BvbnNlElsKCExpc3RBcHBzEiYubGlicmFyaWFuLnNlcGhpcmFoLnYxLkxp",
            "c3RBcHBzUmVxdWVzdBonLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5MaXN0QXBw",
            "c1Jlc3BvbnNlEmEKClJlZnJlc2hBcHASKC5saWJyYXJpYW4uc2VwaGlyYWgu",
            "djEuUmVmcmVzaEFwcFJlcXVlc3QaKS5saWJyYXJpYW4uc2VwaGlyYWgudjEu",
            "UmVmcmVzaEFwcFJlc3BvbnNlEl4KCU1lcmdlQXBwcxInLmxpYnJhcmlhbi5z",
            "ZXBoaXJhaC52MS5NZXJnZUFwcHNSZXF1ZXN0GigubGlicmFyaWFuLnNlcGhp",
            "cmFoLnYxLk1lcmdlQXBwc1Jlc3BvbnNlEmEKClNlYXJjaEFwcHMSKC5saWJy",
            "YXJpYW4uc2VwaGlyYWgudjEuU2VhcmNoQXBwc1JlcXVlc3QaKS5saWJyYXJp",
            "YW4uc2VwaGlyYWgudjEuU2VhcmNoQXBwc1Jlc3BvbnNlEmQKC0dldEJpbmRB",
            "cHBzEikubGlicmFyaWFuLnNlcGhpcmFoLnYxLkdldEJpbmRBcHBzUmVxdWVz",
            "dBoqLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5HZXRCaW5kQXBwc1Jlc3BvbnNl",
            "EmQKC1B1cmNoYXNlQXBwEikubGlicmFyaWFuLnNlcGhpcmFoLnYxLlB1cmNo",
            "YXNlQXBwUmVxdWVzdBoqLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5QdXJjaGFz",
            "ZUFwcFJlc3BvbnNlEmoKDUdldEFwcExpYnJhcnkSKy5saWJyYXJpYW4uc2Vw",
            "aGlyYWgudjEuR2V0QXBwTGlicmFyeVJlcXVlc3QaLC5saWJyYXJpYW4uc2Vw",
            "aGlyYWgudjEuR2V0QXBwTGlicmFyeVJlc3BvbnNlEnMKEENyZWF0ZUFwcFBh",
            "Y2thZ2USLi5saWJyYXJpYW4uc2VwaGlyYWgudjEuQ3JlYXRlQXBwUGFja2Fn",
            "ZVJlcXVlc3QaLy5saWJyYXJpYW4uc2VwaGlyYWgudjEuQ3JlYXRlQXBwUGFj",
            "a2FnZVJlc3BvbnNlEnMKEFVwZGF0ZUFwcFBhY2thZ2USLi5saWJyYXJpYW4u",
            "c2VwaGlyYWgudjEuVXBkYXRlQXBwUGFja2FnZVJlcXVlc3QaLy5saWJyYXJp",
            "YW4uc2VwaGlyYWgudjEuVXBkYXRlQXBwUGFja2FnZVJlc3BvbnNlEnAKD0xp",
            "c3RBcHBQYWNrYWdlcxItLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5MaXN0QXBw",
            "UGFja2FnZXNSZXF1ZXN0Gi4ubGlicmFyaWFuLnNlcGhpcmFoLnYxLkxpc3RB",
            "cHBQYWNrYWdlc1Jlc3BvbnNlEnMKEEFzc2lnbkFwcFBhY2thZ2USLi5saWJy",
            "YXJpYW4uc2VwaGlyYWgudjEuQXNzaWduQXBwUGFja2FnZVJlcXVlc3QaLy5s",
            "aWJyYXJpYW4uc2VwaGlyYWgudjEuQXNzaWduQXBwUGFja2FnZVJlc3BvbnNl",
            "EnkKElVuQXNzaWduQXBwUGFja2FnZRIwLmxpYnJhcmlhbi5zZXBoaXJhaC52",
            "MS5VbkFzc2lnbkFwcFBhY2thZ2VSZXF1ZXN0GjEubGlicmFyaWFuLnNlcGhp",
            "cmFoLnYxLlVuQXNzaWduQXBwUGFja2FnZVJlc3BvbnNlEnoKEVJlcG9ydEFw",
            "cFBhY2thZ2VzEi8ubGlicmFyaWFuLnNlcGhpcmFoLnYxLlJlcG9ydEFwcFBh",
            "Y2thZ2VzUmVxdWVzdBowLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5SZXBvcnRB",
            "cHBQYWNrYWdlc1Jlc3BvbnNlKAEwARJ5ChJVcGxvYWRHYW1lU2F2ZUZpbGUS",
            "MC5saWJyYXJpYW4uc2VwaGlyYWgudjEuVXBsb2FkR2FtZVNhdmVGaWxlUmVx",
            "dWVzdBoxLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5VcGxvYWRHYW1lU2F2ZUZp",
            "bGVSZXNwb25zZRJ/ChREb3dubG9hZEdhbWVTYXZlRmlsZRIyLmxpYnJhcmlh",
            "bi5zZXBoaXJhaC52MS5Eb3dubG9hZEdhbWVTYXZlRmlsZVJlcXVlc3QaMy5s",
            "aWJyYXJpYW4uc2VwaGlyYWgudjEuRG93bmxvYWRHYW1lU2F2ZUZpbGVSZXNw",
            "b25zZRJzChBMaXN0R2FtZVNhdmVGaWxlEi4ubGlicmFyaWFuLnNlcGhpcmFo",
            "LnYxLkxpc3RHYW1lU2F2ZUZpbGVSZXF1ZXN0Gi8ubGlicmFyaWFuLnNlcGhp",
            "cmFoLnYxLkxpc3RHYW1lU2F2ZUZpbGVSZXNwb25zZRJ5ChJDcmVhdGVOb3Rp",
            "ZnlUYXJnZXQSMC5saWJyYXJpYW4uc2VwaGlyYWgudjEuQ3JlYXRlTm90aWZ5",
            "VGFyZ2V0UmVxdWVzdBoxLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5DcmVhdGVO",
            "b3RpZnlUYXJnZXRSZXNwb25zZRJ5ChJVcGRhdGVOb3RpZnlUYXJnZXQSMC5s",
            "aWJyYXJpYW4uc2VwaGlyYWgudjEuVXBkYXRlTm90aWZ5VGFyZ2V0UmVxdWVz",
            "dBoxLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5VcGRhdGVOb3RpZnlUYXJnZXRS",
            "ZXNwb25zZRJ2ChFMaXN0Tm90aWZ5VGFyZ2V0cxIvLmxpYnJhcmlhbi5zZXBo",
            "aXJhaC52MS5MaXN0Tm90aWZ5VGFyZ2V0c1JlcXVlc3QaMC5saWJyYXJpYW4u",
            "c2VwaGlyYWgudjEuTGlzdE5vdGlmeVRhcmdldHNSZXNwb25zZRJzChBDcmVh",
            "dGVOb3RpZnlGbG93Ei4ubGlicmFyaWFuLnNlcGhpcmFoLnYxLkNyZWF0ZU5v",
            "dGlmeUZsb3dSZXF1ZXN0Gi8ubGlicmFyaWFuLnNlcGhpcmFoLnYxLkNyZWF0",
            "ZU5vdGlmeUZsb3dSZXNwb25zZRJzChBVcGRhdGVOb3RpZnlGbG93Ei4ubGli",
            "cmFyaWFuLnNlcGhpcmFoLnYxLlVwZGF0ZU5vdGlmeUZsb3dSZXF1ZXN0Gi8u",
            "bGlicmFyaWFuLnNlcGhpcmFoLnYxLlVwZGF0ZU5vdGlmeUZsb3dSZXNwb25z",
            "ZRJwCg9MaXN0Tm90aWZ5Rmxvd3MSLS5saWJyYXJpYW4uc2VwaGlyYWgudjEu",
            "TGlzdE5vdGlmeUZsb3dzUmVxdWVzdBouLmxpYnJhcmlhbi5zZXBoaXJhaC52",
            "MS5MaXN0Tm90aWZ5Rmxvd3NSZXNwb25zZRJzChBDcmVhdGVGZWVkQ29uZmln",
            "Ei4ubGlicmFyaWFuLnNlcGhpcmFoLnYxLkNyZWF0ZUZlZWRDb25maWdSZXF1",
            "ZXN0Gi8ubGlicmFyaWFuLnNlcGhpcmFoLnYxLkNyZWF0ZUZlZWRDb25maWdS",
            "ZXNwb25zZRJzChBVcGRhdGVGZWVkQ29uZmlnEi4ubGlicmFyaWFuLnNlcGhp",
            "cmFoLnYxLlVwZGF0ZUZlZWRDb25maWdSZXF1ZXN0Gi8ubGlicmFyaWFuLnNl",
            "cGhpcmFoLnYxLlVwZGF0ZUZlZWRDb25maWdSZXNwb25zZRJwCg9MaXN0RmVl",
            "ZENvbmZpZ3MSLS5saWJyYXJpYW4uc2VwaGlyYWgudjEuTGlzdEZlZWRDb25m",
            "aWdzUmVxdWVzdBouLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5MaXN0RmVlZENv",
            "bmZpZ3NSZXNwb25zZRJqCg1MaXN0RmVlZEl0ZW1zEisubGlicmFyaWFuLnNl",
            "cGhpcmFoLnYxLkxpc3RGZWVkSXRlbXNSZXF1ZXN0GiwubGlicmFyaWFuLnNl",
            "cGhpcmFoLnYxLkxpc3RGZWVkSXRlbXNSZXNwb25zZRJtCg5Hcm91cEZlZWRJ",
            "dGVtcxIsLmxpYnJhcmlhbi5zZXBoaXJhaC52MS5Hcm91cEZlZWRJdGVtc1Jl",
            "cXVlc3QaLS5saWJyYXJpYW4uc2VwaGlyYWgudjEuR3JvdXBGZWVkSXRlbXNS",
            "ZXNwb25zZRJkCgtHZXRGZWVkSXRlbRIpLmxpYnJhcmlhbi5zZXBoaXJhaC52",
            "MS5HZXRGZWVkSXRlbVJlcXVlc3QaKi5saWJyYXJpYW4uc2VwaGlyYWgudjEu",
            "R2V0RmVlZEl0ZW1SZXNwb25zZRJ2ChFHZXRCYXRjaEZlZWRJdGVtcxIvLmxp",
            "YnJhcmlhbi5zZXBoaXJhaC52MS5HZXRCYXRjaEZlZWRJdGVtc1JlcXVlc3Qa",
            "MC5saWJyYXJpYW4uc2VwaGlyYWgudjEuR2V0QmF0Y2hGZWVkSXRlbXNSZXNw",
            "b25zZUJdWjVnaXRodWIuY29tL3R1aWh1Yi9wcm90b3MvcGtnL2xpYnJhcmlh",
            "bi9zZXBoaXJhaC92MTt2MaoCI1R1aUh1Yi5Qcm90b3MuTGlicmFyaWFuLlNl",
            "cGhpcmFoLlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TuiHub.Protos.Librarian.Sephirah.V1.BinahReflection.Descriptor, global::TuiHub.Protos.Librarian.Sephirah.V1.GeburaReflection.Descriptor, global::TuiHub.Protos.Librarian.Sephirah.V1.NetzachReflection.Descriptor, global::TuiHub.Protos.Librarian.Sephirah.V1.TipherethReflection.Descriptor, global::TuiHub.Protos.Librarian.Sephirah.V1.YesodReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
