name: check-for-pr

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup bufbuild  
        uses: bufbuild/buf-setup-action@v1.23.0

      - name: Check
        run: make buf-lint