name: check-for-pr

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 'oldstable'

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/tuihub/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Setup Rust environment
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup Dart environment
        uses: dart-lang/setup-dart@v1.4

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Setup bufbuild  
        uses: bufbuild/buf-setup-action@v1.32.2

      - name: Check
        run: make check