name: generate-doc-page

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: pseudomuto/protoc-gen-doc

    steps:
      - uses: actions/checkout@v3

      - name: Build documents
        run: make docs

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        
      - name: generate docsify
        run: |
          npm i docsify-cli -g &&
          docsify g .
          
      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main