name: generate-and-check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
        with:
          go-version: '>=1.18.0'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
      
      - name: Setup .NET environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/tuihub/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Setup Rust environment
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install Protoc Plugins
        run: make install-plugins

      - name: Setup bufbuild  
        uses: bufbuild/buf-setup-action@v1.7.0

      - name: Build
        run: make generate
          
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main

      - name: Apply Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic changes

      - name: Create .NET source package
        run: dotnet nuget pack TuiHub.Protos.nuspec
      - name: Publish .NET package to GPR
        run: dotnet nuget push *.nupkg